# _config.yml

title: "Jekyll Actions Demo"

exclude: 
    - "alignments"
    - "charter"
    - "contexts"
    - "examples"
    - "rif"
    - "scripts"
    - "servicedescription"
    - "spec"
    - "translations"
    - "vocabularies"
    - "READNE,nd"
