# _config.yml

title: "GeoSPARQL Working Group Github Page"
description: "Rescources and development versions of the GeoSPARQL standard"
email: geosparql.swg@lists.opengeospatial.org

collections:
  posts:
    output: true
    

paginate: 5
paginate_path: "/blog/page:num/"
  

plugins:
  - jekyll-paginate

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

theme: minima
exclude: 
    - "alignments"
    - "charter"
    - "contexts"
    - "examples"
    - "rif"
    - "scripts"
    - "servicedescription"
    - "spec"
    - "translations"
    - "vocabularies"
    - "READNE.md"
