# _config.yml

title: "Jekyll Actions Demo"

collections:
  posts:
    output: true

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate-v2

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

theme: minima
exclude: 
    - "alignments"
    - "charter"
    - "contexts"
    - "examples"
    - "rif"
    - "scripts"
    - "servicedescription"
    - "spec"
    - "translations"
    - "vocabularies"
    - "READNE.md"
