# _config.yml

title: "GeoSPARQL Working Group Github Page"
description: "Rescources and development versions of the GeoSPARQL standard"
email: geosparql.swg@lists.opengeospatial.org

collections:
  posts:
    output: true
    permalink: /blog/:path/
  pages:
    output: true
    permalink: /:path/

markdown: kramdown

kramdown:  
  parse_block_html: true
  syntax_highlighter: rouge
  input: GFM

pagination:
  enabled: true
  per_page: 5
  offset: 2
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-paginate-v2

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

theme: minima
exclude: 
    - "alignments"
    - "charter"
    - "contexts"
    - "examples"
    - "rif"
    - "scripts"
    - "servicedescription"
    - "spec"
    - "translations"
    - "vocabularies"
    - "READNE.md"
