# _config.yml

title: "GeoSPARQL Working Group Github Page"
description: "Rescources and development versions of the GeoSPARQL standard"
email: geosparql.swg@lists.opengeospatial.org

collections:
  posts:
    output: true
    

#paginate: 5
#paginate_path: "/blog/page:num/"

paginate: nil
paginate_path: nil

pagination:
  enabled: true
  per_page: 3
  offset: 2
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-paginate

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

theme: minima
exclude: 
    - "alignments"
    - "charter"
    - "contexts"
    - "examples"
    - "rif"
    - "scripts"
    - "servicedescription"
    - "spec"
    - "translations"
    - "vocabularies"
    - "READNE.md"
