== Preface
The GeoSPARQL standard defines:

* a set of SPARQL <<SPARQL>> extension functions
* a set of RIF <<RIFCORE>> rules
* a core RDF/OWL <<RDF>>,<<OWL2>> ontology for geographic information based on the General Feature Model <<ISO19109>>, Simple Features <<ISO19125-1>>, Feature Geometry <<ISO19107>> and SQL MM <<ISO13249>>
* a Functions & Rules vocabulary, derived from the ontology
* SHACL <<SHACL>> shapes for RDF data validation, and
* a Simple Features feature types vocabulary

This document is only one part of the GeoSPARQL standard's resources that contain the above listed information. This document has the role of _specification_ and authoratitivly defines many of the standard's elements. Further description of the standard's parts and their roles is given in <<GeoSPARQL Standard structure>>. This standard's _Profile_ declaration, containing formal links to and descriptions of, its various resources is available at the GeoSPARQL definitional IRI:

* <http://www.opengis.net/def/geosparql>

== Submitting organizations
The following organizations submitted this Implementation Specification to the Open Geospatial Consortium Inc.:

[loweralpha]
.. Australian Bureau of Meteorology
.. Bentley Systems, Inc.
.. CSIRO
.. Defence Geospatial Information Working Group (DGIWG)
.. GeoConnections - Natural Resources Canada
.. Interactive Instruments GmbH
.. GeoScape Australia
.. Mainz University Of Applied Sciences
.. Oracle America
.. Ordnance Survey
.. Raytheon Company
.. SURROUND Australia Pty Ltd.
.. Traverse Technologies, Inc.
.. US Geological Survey (USGS)


=== Submission contact points
All questions regarding this submission should be directed to the editor or the submitters:

|===
|CONTACT | COMPANY

| Matthew Perry | Oracle America
| John Herring | Oracle America
| Nicholas J. Car | SURROUND Australia Pty Ltd.
| Timo Homburg | Mainz University Of Applied Sciences
| Simon J.D. Cox | CSIRO
|===

== Revision history

|===
|Date | Release | Author | Paragraph modified | Description

| 27 Oct. 2009 | Draft | Matthew Perry | Clause 6 | Technical Draft
| 11 Nov. 2009 | Draft | John R. Herring | All | Creation
| 06 Jan. 2010 | Draft | John R. Herring | All | Comment responses
| 30 March 2010 | Draft | Matthew Perry | All | Comment responses
| 26 Oct. 2010 | Draft | Matthew Perry | All | Revision based on working group discussion
| 28 Jan. 2011 | Draft | Matthew Perry | All | Revision based on working group discussion
| 18 April 2011 | Draft | Matthew Perry | All | Restructure with multiple conformance classes
| 02 May 2011 | Draft | Matthew Perry | Clause 6 and Clause 8 | Move Geometry Class from core to geometryExtension
| 05 May 2011 | Draft | Matthew Perry | All | Update URIs
| 13 Jan. 2012 | Draft | Matthew Perry | All | Revision based on Public RFC
| 16 April 2012 | Draft | Matthew Perry | All | Revision based on adoption vote comments
| 19 July 2012 | 1.0 | Matthew Perry | All | Revision of URIs based on OGC Naming Authority recommendations
| 09 Oct. 2020 | 1.1 Draft | Joseph Abhayaratna | All | Establishment of the 1.1 Specification
| 10 Oct. 2020

to

15 March 2021 

| 1.1 Draft | GeoSPARQL 1.1 SWG | All | Addition of GeoSPARQL 1.1 elements
|===

== Changes to the OGC® Abstract Specification
The OGC® Abstract Specification does not require changes to accommodate this OGC® standard.

== Foreword
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights. However, to date, no such rights have been claimed or identified.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the specification set forth in this document, and to provide supporting documentation.