== Normative references

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. However, parties to agreements based on this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below. For undated references, the latest edition of the normative document referred to applies.

* <<ISO19125-1>>, _ISO 19125-1: Geographic information — Simple feature access — Part 1: Common architecture_

* <<OGC07-036>>, _OGC 07-036: Geography Markup Language (GML) Encoding Standard_, Version 3.2.1 (27 August 2007).

* <<IETF3987>>, Internet Engineering Task Force, _RFC 3987: Internationalized Resource Identifiers (IRIs)_. IETF Request for Comment (January 2005). <https://tools.ietf.org/html/rfc3987>

* <<RIFCORE>>, _RIF Core Dialect (Second Edition)_, W3C Recommendation (5 February 2013) <http://www.w3.org/TR/rif-core/>

* <<SPARQL>>, _SPARQL 1.1 Query Language_, W3C Recommendation (21 March 2013). <https://www.w3.org/TR/sparql11-query/>

* <<SPARQLENT>>, _SPARQL 1.1 Entailment Regimes_, W3C Recommendation (21 March 2013). <https://www.w3.org/TR/sparql11-entailment/>

* <<SPARQLPROT>>, _SPARQL 1.1 Protocol_, W3C Recommendation (21 March 2013)> <http://www.w3.org/TR/sparql11-protocol/>

* <<SPARQLRESX>>, _SPARQL Query Results XML Format (Second Edition)_, W3C Recommendation (21 March 2013). <https://www.w3.org/TR/rdf-sparql-XMLres/>

* <<SPARQLRESJ>>, _SPARQL 1.1 Query Results JSON Format_, W3C Recommendation (21 March 2013). <http://www.w3.org/TR/sparql11-results-json/>