=== Normative references

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. However, parties to agreements based on this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below. For undated references, the latest edition of the normative document referred to applies.

ISO 19125-1, _Geographic information — Simple feature access — Part 1: Common architecture_

OGC 07-036, _Geography Markup Language (GML) Encoding Standard_, Version 3.2.1

Internet Engineering Task Force, _RFC 3987: Internationalized Resource Identifiers (IRIs)_. IETF Request for Comment (January 2005). <https://tools.ietf.org/html/rfc3987>

W3C RIF Core, _RIF Core Dialect_, W3C Recommendation (22 June 2010)

W3C SPARQL, _SPARQL Query Language for RDF_, W3C Recommendation (15 January 2008)

W3C SPARQL Entailment, _SPARQL 1.1 Entailment Regimes_, W3C Recommendation 

W3C SPARQL Protocol, _SPARQL Protocol for RDF_, W3C Recommendation (15 January 2008)

W3C SPARQL Result Format, _SPARQL Query Results XML Format_, W3C Recommendation (15 January 2008)

