== Terms and definitions

For the purposes of this document, the terms and definitions given in the above normative references apply, as well as those reproduced or created in this section.

=== Semantic Web

The following terms and their definitions relate to Semantic Web models, tools and methods.

==== RDF

The Resource Description Framework (RDF) is a framework for representing information in the Web. RDF graphs are sets of subject-predicate-object triples, where the elements may be IRIs, blank nodes, or datatyped literals. They are used to express descriptions of resources. <<RDF>>

==== RDFS

RDF Schema provides a data-modelling vocabulary for RDF data. RDF Schema is an extension of the basic RDF vocabulary. <<RDFS>>

==== OWL

The OWL 2 Web Ontology Language, informally OWL 2, is an ontology language for the Semantic Web with formally defined meaning. OWL 2 ontologies provide classes, properties, individuals, and data values and are stored as Semantic Web documents. OWL 2 ontologies can be used along with information written in RDF, and OWL 2 ontologies themselves are primarily exchanged as RDF documents. <<OWL2>>

==== SPARQL

SPARQL is a query language for RDF. The results of SPARQL queries can be result sets or RDF graphs. <<SPARQL>>

=== Spatial

The following terms and their definitions relate to spatial science and data.

==== coordinate system
A coordinate system is a  set of mathematical rules for specifying how coordinates are to be assigned to points.

==== coordinate reference system
A coordinate reference system (CRS) is a coordinate system that is related to an object by a datum.

==== datum
A datum is a parameter or set of parameters that define the position of the origin, the scale, and the orientation of a coordinate system.

==== discrete global grid system

A discrete global grid system (DGGS) is a spatial reference system that represents the Earth, or any other globe-like object, with a tessellation of nested cells. Generally, a DGGS will exhaustively partition the globe in closely packed hierarchical tessellations, each cell representing a homogenous value, with a unique identifier or indexing that allows for linear ordering, parent-child operations, and nearest neighbour algebraic operations.

==== spatial reference system

A spatial reference system (SRS) is a system for establishing spatial position. A spatial reference system can use geographic identifiers (place names, for example), coordinates (in which case it is a coordinate reference system), or identifiers with structured geometry (in which case it is a discrete global grid system).


