== Terms and definitions

For the purposes of this document, the terms and definitions given in the above normative references, as well as those reproduced or created in this section apply.

=== Semantic Web

The following terms and their definitions relate to the Semantic Web models, tools and methods.

==== RDF

The Resource Description Framework (RDF) is a framework for representing information in the Web. RDF graphs are sets of subject-predicate-object triples, where the elements may be IRIs, blank nodes, or datatyped literals. They are used to express descriptions of resources. <<RDF>>

==== RDFS

RDF Schema provides a data-modelling vocabulary for RDF data. RDF Schema is an extension of the basic RDF vocabulary. <<RDFS>>

==== OWL

The OWL 2 Web Ontology Language, informally OWL 2, is an ontology language for the Semantic Web with formally defined meaning. OWL 2 ontologies provide classes, properties, individuals, and data values and are stored as Semantic Web documents. OWL 2 ontologies can be used along with information written in RDF, and OWL 2 ontologies themselves are primarily exchanged as RDF documents. <<OWL2>>

=== Spatial

The following terms and their definitions relate to spatial science and data.
