== Conventions

=== Symbols and abbreviated terms

In this specification, the following common acronyms are used:

[frame=none, grid=none, cols="1, 6"]
|===
| CRS | Coordinate Reference System
| DGGS | Discrete Global Grid System
| GeoJSON | Geographic JavaScript Object Notation
| GFM | General Feature Model (as defined in ISO 19109)
| GML | Geography Markup Language
| KML | Keyhole Markup Language
| OWL | OWL 2 Web Ontology Language
| RCC | Region Connection Calculus
| RDF | Resource Description Framework
| RDFS | RDF Schema
| RIF | Rule Interchange Format
| SPARQL | SPARQL Protocol and RDF Query Language
| SRS | Spatial Reference System
| WKT | Well Known Text (as defined by Simple Features or ISO 19125) 
| W3C | World Wide Web Consortium (http://www.w3.org/)
| XML | Extensible Markup Language
|===

=== Namespaces

The following IRI namespace prefixes are used throughout this document:

[frame=none, grid=none, cols="1, 6"]
|===
| ogc: | http://www.opengis.net/
| ex: | http://example.com/
| geo: | http://www.opengis.net/ont/geosparql#
| geof: | http://www.opengis.net/def/function/geosparql/
| geor: | http://www.opengis.net/def/rule/geosparql/
| sf: | http://www.opengis.net/ont/sf#
| skos: | http://www.w3.org/2004/02/skos/core#
| gml: | http://www.opengis.net/ont/gml#
| my: | http://example.org/ApplicationSchema#
| xsd: | http://www.w3.org/2001/XMLSchema#
| rdf: | http://www.w3.org/1999/02/22-rdf-syntax-ns# 
| rdfs: | http://www.w3.org/2000/01/rdf-schema#
| owl: | http://www.w3.org/2002/07/owl#
|===

=== Placeholder IRIs

The IRI http://www.opengis.net/def/geomLiteral[`ogc:geomLiteral`] is used in requirement specifications as a placeholder for the geometry literal serialization used in a fully-qualified conformance class, e.g. http://www.opengis.net/ont/geosparql#wktLiteral[`+<http://www.opengis.net/ont/geosparql#wktLiteral>+`].
The IRI http://www.opengis.net/def/asGeomLiteral[`ogc:asGeomLiteral`] is used in requirement specifications as a placeholder for the geometry literal serialization property used in a fully-qualified conformance class, e.g. http://www.opengis.net/ont/geosparql#asWKT[`geo:asWKT`].

=== RDF Serializations

Three RDF serializations are used in this document. Terse RDF Triple Language (turtle) <<TURTLE>> is used for RDF snippets placed within the main body of the document, and turtle, JSON-LD <<JSON-LD>> & RDF/XML <<RDFXML>> is used for the examples in _Annex B — GeoSPARQL Examples_.

