== Core

This clause establishes the *core* requirements class, with IRI `/req/core`, which has a single corresponding conformance class, *core*, with IRI `/conf/core`. This requirements class defines a set of classes and properties for representing geospatial data. The resulting vocabulary can be used to construct SPARQL graph patterns for querying appropriately modeled geospatial data. RDFS and OWL vocabulary have both been used so that the vocabulary can be understood by systems that support only RDFS entailment and by systems that support OWL-based reasoning.

=== SPARQL

|===
| *Req 1* Implementations shall support the SPARQL Query Language for RDF <<SPARQL>>, the SPARQL Protocol <<SPARQLPROT>> and the SPARQL Query Results XML <<SPARQLRESX>> and JSON <<SPARQLRESJ>> Formats.
| `/req/core/sparql-protocol`
|===

=== Classes

Three main classes are defined: http://www.opengis.net/ont/geosparql#SpatialObject[`geo:SpatialObject`], http://www.opengis.net/ont/geosparql#SpatialMeasure[`geo:SpatialMeasure`] and http://www.opengis.net/ont/geosparql#Feature[`geo:Feature`]. The class http://www.opengis.net/ont/geosparql#Feature[`geo:Feature`] is equivalent to the UML class `Feature` defined in <<ISO19109>>.

==== Class: geo:SpatialObject

The class http://www.opengis.net/ont/geosparql#SpatialObject[`geo:SpatialObject`] is defined by the following:

```turtle
geo:SpatialObject a rdfs:Class, owl:Class ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "Spatial Object"@en ;
    skos:definition "The class Spatial Object represents everything that can 
                    have a spatial representation. It is superclass of feature 
                    and geometry"@en .
```

|===
| *Req 2* Implementations shall allow the RDFS class http://www.opengis.net/ont/geosparql#SpatialObject[`geo:SpatialObject`] to be used in SPARQL graph patterns.
|`/req/core/spatial-object-class`
|===

*Example:*

```turtle
eg:x a geo:SpatialObject ;
     skos:prefLabel "Object X";
.
```

==== Class: geo:SpatialMeasure

The class http://www.opengis.net/ont/geosparql#SpatialMeasure[`geo:SpatialMeasure`] is defined by the following:

```turtle
geo:SpatialMeasure a rdfs:Class, owl:Class ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "Spatial Measure"@en ;
    skos:definition "This class represents a measurement of some dimension 
                    of a feature's spatial presence."@en .
```

|===
| *Req 3* Implementations shall allow the RDFS class http://www.opengis.net/ont/geosparql#SpatialMeasure[`geo:SpatialMeasure`] to be used in SPARQL graph patterns.
|`/req/core/spatial-measure-class`
|===

==== Class: geo:Feature

The class http://www.opengis.net/ont/geosparql#Feature[`geo:Feature`] is equivalent to the class `GFI_Feature` <<ISO19156>> and is defined by the following:



```turtle
geo:Feature a rdfs:Class, owl:Class ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "Feature"@en ;
    rdfs:subClassOf geo:SpatialObject ;
    owl:disjointWith geo:Geometry ;
    skos:definition "This class represents the top-level feature type. This
                    class is equivalent to GFI_Feature defined in ISO 19156, 
                    and it is superclass of all feature types."@en .
```

|===
| *Req 4* Implementations shall allow the RDFS class http://www.opengis.net/ont/geosparql#Feature[`geo:Feature`] to be used in SPARQL graph patterns.
|`/req/core/feature-class`
|===

