=== Geometry Extension (serialization, version)

This clause establishes the _Geometry Extension (serialization, version)_ parameterized requirements class, with URI `/req/geometry-extension`, which has a single corresponding conformance class _Geometry Extension (serialization, version)_, with URI `/conf/geometry-extension`. This requirements class defines a vocabulary for asserting and querying information about geometry data, and it defines query functions for operating on geometry data.

As part of the vocabulary, an RDFS datatype is defined for encoding detailed geometry information as a literal value. A literal representation of a geometry is needed so that geometric values may be treated as a single unit. Such a representation allows geometries to be passed to external functions for computations and to be returned from a query.

Other schemes for encoding simple geometry data in RDF have been proposed. The W3C Basic Geo vocabulary (http://www.w3.org/2003/01/geo/) is one popular vocabulary. These simple vocabularies have limitations, for example the inability to specify different datums and coordinate systems, and were therefore not used in GeoSPARQL. Note that most existing geometry data encoded using these vocabularies can easily be converted into GeoSPARQL representations. The SPARQL query below creates `geo:wktLiteral` values from W3C Basic Geo geometries.

```
PREFIX w3cGeo: <http://www.w3.org/2003/01/geo/wgs84_pos#> 
PREFIX geo: <http://www.opengis.net/#geosparql>

SELECT (STRDT(CONCAT("POINT(",?long," ",?lat,")"), 
              geo:wktLiteral) AS ?wktLit)
WHERE { ?point w3cGeo:long ?long . 
        ?point w3cGeo:lat ?lat }
```

==== Parameters

The following parameters are defined for the _Geometry Extension_ requirements class.

*serialization*: Specifies the serialization standard to use when generating geometry
literals and also the supported geometry types.

Note that the serialization chosen strongly affects the geometry conceptualization. The WKT serialization aligns the geometry types with ISO 19125 Simple Features [ISO 19125-1], and the GML serialization aligns the geometry types with ISO 19107 Spatial Schema [6].

*version*: Specifies the version of the serialization format used.

==== Geometry Classes and Properties

A single root geometry class is defined: `geo:Geometry`. The class `geo:Geometry` is equivalent to the UML class `GM_Object` defined in [6]. In addition, properties are defined for describing geometry data and for associating geometries with features.

===== Class: geo:Geometry

The class `geo:Geometry` is equivalent to `GM_Object` [6] and is defined by the following:

```
geo:Geometry a rdfs:Class, 
               owl:Class;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>; 
    rdfs:label "Geometry"@en;
    rdfs:subClassOf geo:SpatialObject;
    owl:disjointWith geo:Feature;
    rdfs:comment "The class represents the top-level geometry type. This class 
                 is equivalent to the UML class GM_Object defined in ISO 19107, 
                 and it is superclass of all geometry types."@en .
```

|===
|*Req 8* Implementations shall allow the RDFS class `geo:Geometry` to be used in SPARQL graph patterns.
|`/req/geometry-extension/geometry-class`
|===

==== Standard Properties for geo:Feature

Properties are defined for associating geometries with features.

|===
|*Req 9* Implementations shall allow the properties `geo:hasGeometry`, 
`geo:hasDefaultGeometry`, geo:hasLength, geo:hasArea, geo:hasVolume & geo:hasSpatialResolution to be used in SPARQL graph patterns.
|`/req/geometry-extension/feature-properties`
|===

===== Property: geo:hasGeometry

The property `geo:hasGeometry` is used to link a feature with a geometry that represents its spatial extent. A given feature may have many associated geometries.

```
geo:hasGeometry a rdf:Property, 
                  owl:ObjectProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "has Geometry"@en;
    rdfs:comment "A spatial representation for a given feature."@en;     
    rdfs:domain geo:Feature;
    rdfs:range geo:Geometry .
```

===== Property: geo:hasDefaultGeometry

The property `geo:hasDefaultGeometry` is used to link a feature with its default geometry. The default geometry is the geometry that should be used for spatial calculations in the absence of a request for a specific geometry (e.g. in the case of query rewrite).

```
geo:hasDefaultGeometry a rdf:Property, 
                            owl:ObjectProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "has Default Geometry"@en;
    rdfs:comment "The default geometry to be used in spatial calculations, 
                 usually the most detailed geometry."@en; 
    rdfs:subPropertyOf geo:hasGeometry;
    rdfs:domain geo:Feature; 
    rdfs:range geo:Geometry .
```

GeoSPARQL does not restrict the cardinality of the `geo:hasDefaultGeometry` property. It is thus possible for a feature to have more than one distinct default geometry or to have no default geometry. This situation does not result in a query processing error; SPARQL graph pattern matching simply proceeds as normal. Certain queries may, however, give logically inconsistent results. For example, if a feature `my:f1` has two asserted default geometries, and those two geometries are disjoint polygons, the query below could return a non-zero count on a system supporting the GeoSPARQL Query Rewrite Extension (rule `geor:sfDisjoint`).

```
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT (COUNT(*) AS ?cnt)
WHERE { :f1 geo:sfDisjoint :f1 }
```

Such cases are application-specific data modeling errors and are therefore outside of the scope of the GeoSPARQL specification.

===== Property: geo:hasLength

The property `geo:hasLength` is used to indicate the length of a `geo:Feature`. In the case of a one-dimensional `geo:Feature`, it is the simple length. In the case of a two-dimensional `geo:Feature`, it is interpreted to mean the perimeter length. The range of the property is `geo:SpatialMeasure`, which encodes the length value expressed as a scalar quantity which also includes the units of measure, and potentially uncertainty and other properties.

```
geo:hasLength a rdf:Property, 
              owl:ObjectProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "has length"@en;
    rdfs:comment "The length of a Feature, expressed as a Spatial Measure."@en; 
    rdfs:domain geo:Feature; 
    rdfs:range geo:SpatialMeasure .
```

A consistency check can be applied to geometries indicating this property and the `geo:dimension` property: the integer range value of a `geo:dimension` property for a geometry with a `geo:hasLength` property must be either 1 or 2.

===== Property: geo:hasArea

The property `geo:hasArea` is used to indicate the area of a `geo:Feature`. The range of the property is `geo:SpatialMeasure`, which encodes the area value expressed as a scalar quantity which also includes the units of measure, and potentially uncertainty and other properties.

```
geo:hasArea a rdf:Property, 
              owl:ObjectProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "has area"@en;
    rdfs:comment "The two-dimensional area of a Feature, expressed as a Spatial Measure."@en; 
    rdfs:domain geo:Feature; 
    rdfs:range geo:SpatialMeasure .
```

A consistency check can be applied to geometries indicating this property and the `geo:dimension` property: the integer range value of a `geo:dimension` property for a geometry with a `geo:hasLength` property must be 2.

===== Property: geo:hasVolume

The property `geo:hasVolume` is used to indicate the area of a `geo:Feature`. The range of the property is `geo:SpatialMeasure`, which encodes the volume value expressed as a scalar quantity which also includes the units of measure, and potentially uncertainty and other properties.

```
geo:hasVolume a rdf:Property, 
              owl:ObjectProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "has volume"@en;
    rdfs:comment "The volume of a Feature, expressed as a Spatial Measure"@en; 
    rdfs:domain geo:Feature; 
    rdfs:range geo:SpatialMeasure .
```

A consistency check can be applied to geometries indicating this property and the `geo:dimension` property: the integer range value of a `geo:dimension` property for a geometry with a `geo:hasLength` property must be 3.

==== Standard Properties for geo:Geometry

Properties are defined for describing geometry metadata.

|===
|*Req 10* Implementations shall allow the properties `geo:dimension`, `geo:coordinateDimension`, `geo:spatialDimension`, `geo:isEmpty`, `geo:isSimple`, `geo:hasSerialization` , `geo:inCRS` to be used in SPARQL graph patterns.
|`/req/geometry-extension/geometry-properties`
|===

===== Property: geo:dimension

The dimension is the topological dimension of this geometric object, which must be less than or equal to the coordinate dimension. In non-homogeneous collections, this will return the largest topological dimension of the contained objects.

```
geo:dimension a rdf:Property,
                owl:DatatypeProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "dimension"@en;
    rdfs:comment "The topological dimension of this geometric object, which
                 must be less than or equal to the coordinate dimension. In 
                 non-homogeneous collections, this is the largest 
                 topological dimension of the contained objects."@en;
    rdfs:domain geo:Geometry;
    rdfs:range xsd:integer .
```

===== Property: geo:coordinateDimension

The coordinate dimension is the dimension of direct positions (coordinate tuples) used in the definition of this geometric object.

```
geo:coordinateDimension a rdf:Property,
                          owl:DatatypeProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "coordinate dimension"@en;
    rdfs:comment "The number of measurements or axes needed to describe the
                 position of this geometry in a coordinate system."@en;
    rdfs:domain geo:Geometry;
    rdfs:range xsd:integer .
```

===== Property: geo:spatialDimension

The spatial dimension is the dimension of the spatial portion of the direct positions (coordinate tuples) used in the definition of this geometric object. If the direct positions do not carry a measure coordinate, this will be equal to the coordinate dimension.

```
geo:spatialDimension a rdf:Property,
                       owl:DatatypeProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "spatial dimension"@en;
    rdfs:comment "The number of measurements or axes needed to describe the
                 spatial position of this geometry in a coordinate
                 system."@en;
    rdfs:domain geo:Geometry;
    rdfs:range xsd:integer .
```

===== Property: geo:hasSpatialResolution

The property `geo:hasSpatialResolution` is used to indicate resolution of the elements within literal representations of a geometry. Since this property is defined for a `geo:Geometry`, all literal representations of that geometry must have the same spatial resolution.

```
geo:hasSpatialResolution a rdf:Property, 
              owl:ObjectProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "has spatial resolution"@en;
    rdfs:comment "The spatial resolution of a Geometry"@en; 
    rdfs:domain geo:Geometry .
```

====== Property: geo:isEmpty


The `geo:isEmpty` Boolean will be set to true only if the geometry contains no points.

```
geo:isEmpty a rdf:Property, owl:DatatypeProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "is empty"@en;
    rdfs:comment "(true) if this geometric object is the empty Geometry. If
                 true, then this geometric object represents the empty point
                 set for the coordinate space."@en; 
    rdfs:domain geo:Geometry;
    rdfs:range xsd:boolean .
```

====== Property: geo:isSimple

The `geo:isSimple` Boolean will be set to true, only if the geometry contains no self- intersections, with the possible exception of its boundary.

```
geo:isSimple a rdf:Property, 
               owl:DatatypeProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "is simple"@en;
    rdfs:comment "(true) if this geometric object has no anomalous geometric
                points, such as self intersection or self tangency."@en; 
    rdfs:domain geo:Geometry;
    rdfs:range xsd:boolean .    
```

===== Property: geo:hasSerialization

The `geo:hasSerialization` property is used to connect a geometry with its text- based serialization (e.g., its WKT serialization).

```
geo:hasSerialization a rdf:Property, 
                       owl:DatatypeProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>; 
    rdfs:label "has serialization"@en;
    rdfs:comment "Connects a geometry object with its text-based
                 serialization."@en;
    rdfs:domain geo:Geometry; 
    rdfs:range rdfs:Literal .
```

===== Property: geo:inCRS

The `geo:inCRS` property is used to connect a geometry with the CRS used for its representation which affects measurements of its size (length, area, volume).

```
geo:inCRS a rdf:Property, 
            owl:ObjectProperty;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>; 
    rdfs:label "in CRS"@en;
    rdfs:comment "A Coordinate Reference System, as recorded in a 
                 vocabulary of them."@en;
    rdfs:domain geo:SpatialMeasure; 
    rdfs:range skos:Concept .
```

==== Requirements for WKT Serialization (serialization=WKT)

This section establishes the requirements for representing geometry data in RDF based on WKT as defined by Simple Features [ISO 19125-1].

===== RDFS Datatypes

This section defines one RDFS Datatype: `+http://www.opengis.net/ont/geosparql#wktLiteral+`.

*RDFS Datatype: geo:wktLiteral*

```
geo:wktLiteral a rdfs:Datatype;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "Well-known Text Literal"@en;
    rdfs:comment "A Well-known Text serialization of a geometry object."@en .
```

|===
|*Req 11* All RDFS Literals of type `geo:wktLiteral` shall consist of an optional URI identifying the coordinate reference system followed by Simple Features Well Known Text (WKT) describing a geometric value. Valid `geo:wktLiterals` are formed by concatenating a valid, absolute URI as defined in [RFC 2396], one or more spaces (Unicode U+0020 character) as a separator, and a WKT string as defined in Simple Features [ISO 19125-1].
|`/req/geometry-extension/wkt-literal`
|===

For `geo:wktLiterals`, the beginning URI identifies the spatial reference system for
the geometry. The OGC maintains a set of CRS URIs under the
`+http://www.opengis.net/def/crs/+` namespace. This leading spatial reference
system URI is optional. In the absence of a leading spatial reference system URI, the
following spatial reference system URI will be assumed:
`+<http://www.opengis.net/def/crs/OGC/1.3/CRS84>+`
This URI denotes WGS 84 longitude-latitude.

|===
|*Req 12* The URI `+<http://www.opengis.net/def/crs/OGC/1.3/CRS84>+` shall be assumed as the spatial reference system for `geo:wktLiteral`s that do not specify an explicit spatial reference system URI..
|`/req/geometry-extension/wkt-literal-default-srs`
|===

|===
|*Req 13* Coordinate tuples within `geo:wktLiteral`s shall be interpreted using the axis order defined in the spatial reference system used.
|`/req/geometry-extension/wkt-axis-order`
|===

The example `geo:wktLiteral` below encodes a point geometry using the default WGS84 geodetic longitude-latitude spatial reference system for Simple Features 1.0:

```
"Point(-83.38 33.95)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>
```

A second example below encodes the same point using `+<http://www.opengis.net/def/crs/EPSG/0/4326>+`: a WGS 84 geodetic latitude-longitude spatial reference system (note that this spatial reference system defines a different axis order):

```
"<http://www.opengis.net/def/crs/EPSG/0/4326>
Point(33.95 -83.38)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>
```

|===
|*Req 14* An empty RDFS Literal of type `geo:wktLiteral` shall be interpreted as an empty geometry.
|`/req/geometry-extension/wkt-literal-empty`
|===

===== Serialization Properties

The `geo:asWKT` property is defined to link a geometry with its WKT serialization.

*Property: geo:asWKT*

|===
|*Req 15* Implementations shall allow the RDF property `geo:asWKT` to be used in SPARQL graph patterns.
|`/req/geometry-extension/geometry-as-wkt-literal`
|===

The property `geo:asWKT` is used to link a geometric element with its WKT serialization.

```
geo:asWKT a rdf:Property,
            owl:DatatypeProperty;
    rdfs:subPropertyOf geo:hasSerialization;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "as WKT"@en;
    rdfs:comment "The WKT serialization of a geometry."@en;
    rdfs:domain geo:Geometry;
    rdfs:range geo:wktLiteral .
```

==== Requirements for GML Serialization (serialization=GML)

This section establishes requirements for representing geometry data in RDF based on GML as defined by Geography Markup Language Encoding Standard [OGC 07-036].

===== RDFS Datatypes

This section defines one RDFS Datatype:
`http://www.opengis.net/ont/geosparql#gmlLiteral.`

*RDFS Datatype: geo:gmlLiteral*

```
geo:gmlLiteral a rdfs:Datatype;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>; 
    rdfs:label "GML literal"@en;
    rdfs:comment "The datatype of GML literal values"@en .
```

Valid `geo:gmlLiteral`s are formed by encoding geometry information as a valid element from the GML schema that implements a subtype of `GM_Object`. For example, in GML 3.2.1 this is every element directly or indirectly in the substitution group of the element `{http://www.opengis.net/ont/gml/3.2}AbstractGeometry`. In GML 3.1.1 and GML 2.1.2 this is every element directly or indirectly in the substitution group of the element `{http://www.opengis.net/ont/gml}_Geometry`.

|===
|*Req 16* All `geo:gmlLiteral`s shall consist of a valid element from the GML schema that implements a subtype of `GM_Object` as defined in [OGC 07-036].
|`/req/geometry-extension/gml-literal`
|===

The example `geo:gmlLiteral` below encodes a point geometry in the WGS 84
geodetic longitude-latitude spatial reference system using GML version 3.2:

```
"<gml:Point 
        srsName=\"http://www.opengis.net/def/crs/OGC/1.3/CRS84\" 
        xmlns:gml=\"http://www.opengis.net/ont/gml\">
    <gml:pos>-83.38 33.95</gml:pos>
</gml:Point>"^^<http://www.opengis.net/ont/geosparql#gmlLiteral>
```

|===
|*Req 17* An empty `geo:gmlLiteral` shall be interpreted as an empty geometry.
|`/req/geometry-extension/gml-literal-empty`
|===

|===
|*Req 18* Implementations shall document supported GML profiles.
|`/req/geometry-extension/gml-profile`
|===

===== Serialization Properties

This document defines the `geo:asGML` property to link a geometry with its serialization.

*Property: geo:asGML*

|===
|*Req 19* Implementations shall allow the RDF property `geo:asGML` to be used in SPARQL graph patterns.
|`/req/geometry-extension/geometry-as-gml-literal`
|===


The property `geo:asGML` is used to link a geometric element with its GML serialization.

```
geo:asGML a rdf:Property; 
    rdfs:subPropertyOf geo:hasSerialization;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "as GML"@en;
    rdfs:comment "The GML serialization of a geometry."@en; 
    rdfs:domain geo:Geometry;
    rdfs:range geo:gmlLiteral .
```


==== Requirements for GeoJSON Serialization (serialization=GEOJSON)

This section establishes the requirements for representing geometry data in RDF based on GeoJSON.

===== RDFS Datatypes

This section defines one RDFS Datatype: `+http://www.opengis.net/ont/geosparql#geoJSONLiteral+`.

*RDFS Datatype: geo:geoJSONLiteral*

```
geo:geoJSONLiteral a rdfs:Datatype;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "GeoJSON Literal"@en;
    rdfs:comment "A GeoJSON serialization of a geometry object."@en .
```

Valid `geo:geoJSONLiteral`s are formed by encoding geometry information as a Geometry object as defined in the GeoJSON specification [RFC 7946].

|===
|*Req 20* All `geo:geoJSONLiteral`s shall consist of the Geometry objects as defined in the GeoJSON specification [RFC 7946].
|`/req/geometry-extension/geoJSON-literal`
|===

|===
|*Req 21* All RDFS Literals of type `geo:geoJSONLiteral` do not contain a CRS definition. All literals of this type shall according to the GeoJSON specification only be encoded in and assumed to use the WGS84 geodetic longitude-latitude spatial reference system (urn:ogc:def:crs:OGC::CRS84).
|`/req/geometry-extension/geoJSON-literal-crs`
|===

The example `geo:geoJSONLiteral` below encodes a point geometry using the default WGS84 geodetic longitude-latitude spatial reference system for Simple Features 1.0:

```
"{\"type\":\"Point\", \"coordinates\":[-83.38,33.95]}"^^<http://www.opengis.net/ont/geosparql#geoJSONLiteral>
```

|===
|*Req 22* An empty RDFS Literal of type `geo:geoJSONLiteral` shall be interpreted as an empty geometry, i.e. {"geometry":null} in GeoJSON .
|`/req/geometry-extension/geoJSON-literal-empty`
|===

===== Serialization Properties

The `geo:asGeoJSON` property is defined to link a geometry with its GeoJSON serialization.

*Property: geo:asGeoJSON*

|===
|*Req 23* Implementations shall allow the RDF property `geo:asGeoJSON` to be used in SPARQL graph patterns.
|`/req/geometry-extension/geometry-as-geojson-literal`
|===

The property `geo:asGeoJSON` is used to link a geometric element with its GeoJSON serialization.

```
geo:asGeoJSON a rdf:Property,
            owl:DatatypeProperty;
    rdfs:subPropertyOf geo:hasSerialization;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "as GeoJSON"@en;
    rdfs:comment "The GeoJSON serialization of a geometry."@en;
    rdfs:domain geo:Geometry;
    rdfs:range geo:geoJSONLiteral .
```

==== Requirements for KML Serialization (serialization=KML)

This section establishes the requirements for representing geometry data in RDF based on KML.

===== RDFS Datatypes

This section defines one RDFS Datatype: `+http://www.opengis.net/ont/geosparql#kmlLiteral+`.

*RDFS Datatype: geo:kmlLiteral*

```
geo:kmlLiteral a rdfs:Datatype;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "KML Literal"@en;
    rdfs:comment "A KML serialization of a geometry object."@en .
```

Valid `geo:kmlLiteral`s are formed by encoding geometry information as a Geometry object as defined in the KML specification [https://www.ogc.org/standards/kml/].

|===
|*Req XX* All `geo:kmlLiteral`s shall consist of the Geometry objects as defined in the KML specification [https://www.ogc.org/standards/kml/].
|`/req/geometry-extension/kml-literal`
|===

|===
|*Req XX* All RDFS Literals of type `geo:kmlLiteral` do not contain a CRS definition. All literals of this type shall according to the KML specification only be encoded in and assumed to use the WGS84 geodetic longitude-latitude spatial reference system (urn:ogc:def:crs:OGC::CRS84).
|`/req/geometry-extension/kml-literal-crs`
|===

The example `geo:kmlLiteral` below encodes a point geometry using the default WGS84 geodetic longitude-latitude spatial reference system for Simple Features 1.0:

```
"<Point xmlns=\"http://www.opengis.net/kml/2.2\"><coordinates>-83.38,33.95</coordinates></Point>"^^<http://www.opengis.net/ont/geosparql#kmlLiteral>
```

|===
|*Req XX* An empty RDFS Literal of type `geo:kmlLiteral` shall be interpreted as an empty geometry .
|`/req/geometry-extension/kml-literal-empty`
|===

===== Serialization Properties

The `geo:asKML` property is defined to link a geometry with its KML serialization.

*Property: geo:asKML*

|===
|*Req XX* Implementations shall allow the RDF property `geo:asKML` to be used in SPARQL graph patterns.
|`/req/geometry-extension/geometry-as-kml-literal`
|===

The property `geo:asKML` is used to link a geometric element with its KML serialization.

```
geo:asKML a rdf:Property,
            owl:DatatypeProperty;
    rdfs:subPropertyOf geo:hasSerialization;
    rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.1>;
    rdfs:label "as KML"@en;
    rdfs:comment "The KML serialization of a geometry."@en;
    rdfs:domain geo:Geometry;
    rdfs:range geo:kmlLiteral .
```


==== Non-topological Query Functions

This clause defines SPARQL functions for performing non-topological spatial operations.

|===
|*Req 24* Implementations shall support `geof:distance`, `geof:buffer`, `geof:convexHull`, `geof:intersection`, `geof:union`, `geof:difference`, `geof:symDifference`, `geof:envelope` and `geof:boundary` as SPARQL extension functions, consistent with the definitions of the corresponding functions (`distance`, `buffer`, `convexHull`, `intersection`, `difference`, `symDifference`, `envelope` and `boundary` respectively) in Simple Features [ISO 19125-1].
|`/req/geometry-extension/query-functions`
|===

An invocation of any of the following functions with invalid arguments produces an error. An invalid argument includes any of the following:

- An argument of an unexpected type
- An invalid geometry literal value
- A geometry literal from a spatial reference system that is incompatible with the spatial reference system used for calculations
- An invalid units URI

For further discussion of the effects of errors during FILTER evaluation, consult Section 11 of the SPARQL specification [W3C SPARQL] (http://www.w3.org/TR/rdf-sparql- query/#tests).

Note that returning values instead of raising an error serves as an extension mechanism of SPARQL.

From Section 11.3.1 of the SPARQL specification [W3C SPARQL] (http://www.w3.org/TR/rdf-sparql-query/#operatorExtensibility):

[quote]
SPARQL language extensions may provide additional associations between operators and operator functions; this amounts to adding rows to the table above. No additional operator may yield a result that replaces any result other than a type error in the semantics defined above. The consequence of this rule is that SPARQL extensions will produce at least the same solutions as an unextended implementation, and may, for some queries, produce more solutions.

This extension mechanism is intended to allow GeoSPARQL implementations to simultaneously support multiple geometry serializations. For example, a system that supports `geo:wktLiteral` serializations may also support `geo:gmlLiteral` serializations and consequently would not raise an error if it encounters multiple geometry datatypes while processing a given query.

Several non-topological query functions use a unit of measure URI. The OGC has defined some standard units of measure URIs under the `+http://www.opengis.net/def/uom/OGC/1.0/+` namespace, for example `+<http://www.opengis.net/def/uom/OGC/1.0/metre>+`.

===== Function: geof:distance


```
geof:distance (geom1: ogc:geomLiteral, geom2: ogc:geomLiteral, 
               units: xsd:anyURI): xsd:double
```

Returns the shortest distance in units between any two Points in the two geometric
objects as calculated in the spatial reference system of `geom1`.

===== Function: geof:buffer

```
geof:buffer (geom: ogc:geomLiteral, radius: xsd:double, 
             units: xsd:anyURI): ogc:geomLiteral
```

This function returns a geometric object that represents all Points whose distance from `geom1` is less than or equal to the `radius` measured in `units`. Calculations are in the spatial reference system of `geom1`.

===== Function: geof:convexHull

```
geof:convexHull (geom1: ogc:geomLiteral): ogc:geomLiteral
```

This function returns a geometric object that represents all Points in the convex hull of `geom1`. Calculations are in the spatial reference system of `geom1`.

===== Function: geof:intersection

```
geof:intersection (geom1: ogc:geomLiteral,
                   geom2: ogc:geomLiteral): ogc:geomLiteral
```

This function returns a geometric object that represents all Points in the intersection of `geom1` with `geom2`. Calculations are in the spatial reference system of `geom1`.

===== Function: geof:union

```
geof:union (geom1: ogc:geomLiteral, geom2: ogc:geomLiteral, 
            ): ogc:geomLiteral
```

This function returns a geometric object that represents all Points in the union of `geom1` with `geom2`. Calculations are in the spatial reference system of `geom1`.

===== Function: geof:difference

```
geof:difference (geom1: ogc:geomLiteral, geom2: ogc:geomLiteral, 
                 ): ogc:geomLiteral
```

This function returns a geometric object that represents all Points in the set difference of `geom1` with `geom2`. Calculations are in the spatial reference system of `geom1`.

===== Function: geof:symDifference

```
geof:symDifference (geom1: ogc:geomLiteral, 
                    geom2: ogc:geomLiteral,
                    ): ogc:geomLiteral
```

This function returns a geometric object that represents all Points in the set symmetric difference of `geom1` with `geom2`. Calculations are in the spatial reference system of `geom1`.

===== Function: geof:envelope

```
geof:envelope (geom1: ogc:geomLiteral): ogc:geomLiteral
```

This function returns the minimum bounding box of `geom1`. Calculations are in the spatial reference system of `geom1`.

===== Function: geof:boundary

```
geof:boundary (geom1: ogc:geomLiteral): ogc:geomLiteral
```

This function returns the closure of the boundary of `geom1`. Calculations are in the spatial reference system of `geom1`.

|===
|*Req 25* Implementations shall support `geof:getSRID` as a SPARQL extension function.
|`/req/geometry-extension/srid-function`
|===

===== Function: geof:getsrid

```
geof:getSRID (geom: ogc:geomLiteral): xsd:anyURI
```

Returns the spatial reference system URI for `geom`.

