== Geometry Extension (serialization, version)

This clause establishes the _Geometry Extension (serialization, version)_ parameterized requirements class, with IRI `/req/geometry-extension`, which has a single corresponding conformance class _Geometry Extension (serialization, version)_, with IRI `/conf/geometry-extension`. This requirements class defines a vocabulary for asserting and querying information about geometry data, and it defines query functions for operating on geometry data.

As part of the vocabulary, an RDFS datatype is defined for encoding detailed geometry information as a literal value. A literal representation of a geometry is needed so that geometric values may be treated as a single unit. Such a representation allows geometries to be passed to external functions for computations and to be returned from a query.

Other schemes for encoding simple geometry data in RDF have been implemented. The W3C Basic Geo vocabularyfootnote:[http://www.w3.org/2003/01/geo/] was an early (2003) RDF vocabulary for "representing lat(itude), long(itude) and other information about spatially-located things, using WGS84 as a reference datum" and many widely used Semantic Web vocabularies contain some spatial data support. For example, _Dublin Core Terms_ provides a _Location_ classfootnote:[http://purl.org/dc/terms/Location] for "A spatial region or named place." and _schema.org_ provides a number of spatial object and geometry classes, such as `GeoCoordinates` footnote:[https://schema.org/GeoCoordinates] and `GeoShape` footnote:[https://schema.org/GeoShape]. 

Many vocabularies, such as these two, provide little specific support for detailed geometries and only support the WGS84 Coordinate Reference System (CSR).

Since 2012 and the first version of GeoSPARQL, many ontologies have imported GeoSPARQL, for example, the _ISA Programme Location Core Vocabulary_ footnote:[https://www.w3.org/ns/locn] whose usage notes provide examples containing GeoSPARQL literals and the use of GeoSPARQL's "geometry class". The W3C's more recent _Data Catalog Vocabulary, Version 2_ (DCAT2) standardfootnote:[https://www.w3.org/TR/vocab-dcat/#spatial-properties] similarly contains usage notes for `geometry`, `bbox` and other properties that suggest the use of GeoSPARQL literals.

Some of the properties defined in these vocabularies, such as DCAT2's `spatialResolution` have motivated the inclusion of new properties in this version of GeoSPARQL. In this case the equivalent property is <<Property: geo:hasSpatialResolution, `geo:hasSpatialResolution`>>. The GeoSPARQL 1.1 Standards Working Group charter <<CHARTER>> contains references to a number of vocabularies/ontologies that were influential in the generation of this verison of GeoSPARQL.

=== Parameters

The following parameters are defined for the _Geometry Extension_ requirements class.

serialization:: Specifies the serialization standard to use when generating geometry literals and also the supported geometry types.

NOTE: a serialization strongly affects the geometry conceptualization. The WKT serialization aligns the geometry types with _ISO 19125 Simple Features_ <<ISO19125-1>>, and the GML serialization aligns the geometry types with _ISO 19107 Spatial Schema_ <<ISO19107>>.

version:: Specifies the version of the serialization format used.

=== Geometry Class

A single root geometry class is defined: <<Class: geo:Geometry, `geo:Geometry`>>. In addition, properties are defined for describing geometry data and for associating geometries with features.

One container class is defined: <<Class: geo:GeometryCollection, Geometry Collection>>. 

==== Class: geo:Geometry

The class http://www.opengis.net/ont/geosparql#Geometry[`geo:Geometry`] is equivalent to `GM_Object` <<ISO19107>> and is defined by the following:

```turtle
geo:Geometry 
    a rdfs:Class, owl:Class ;
    rdfs:isDefinedBy geo: ; 
    skos:prefLabel "Geometry"@en ;
    rdfs:subClassOf geo:SpatialObject ;
    owl:disjointWith geo:Feature;
    skos:definition "The class represents the top-level geometry type. This class 
                    is equivalent to the UML class GM_Object defined in ISO 19107, 
                    and it is superclass of all geometry types."@en ;
.
```

|===
| *Req 11* Implementations shall allow the RDFS class <<Class: geo:Geometry, `geo:Geometry`>> to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-class[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-class`]
|===

==== Class: geo:GeometryCollection

The class <<Class: geo:GeometryCollection, Geometry Collection>> is defined by the following:

```turtle
geo:GeometryCollection
  a owl:Class ;
  rdfs:isDefinedBy geo: ;
  skos:prefLabel "Collection of geometry entities"@en ;
  skos:definition "The class Geometry Collection represents any collection of Geometry entities."@en ;
  rdfs:subClassOf geo:SpatialObjectCollection ;
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:allValuesFrom geo:Geometry ;
      owl:onProperty rdfs:member ;
    ] ;
.
```

The restriction imposed on the more general <<Class: SpatialObjectCollection, Spatial Object Collection>> that defines this class is that only instances of <<Class: Geometry, Geometry>> are allowed to be members of it and these are to be indicated with the `rdfs:member` property.

|===
| *Req 12* Implementations shall allow the RDFS class <<Class: geo:GeometryCollection, `geo:GeometryCollection`>> to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.1/req/core/geometry-collection-class[`http://www.opengis.net/spec/geosparql/1.1/req/core/geometry-collection-class`]
|===

=== Standard Properties for geo:Geometry

Properties are defined for describing geometry metadata.

|===
| *Req 13* Implementations shall allow the properties 
<<Property: geo:dimension, `geo:dimension`>>, 
<<Property: geo:coordinateDimension, `geo:coordinateDimension`>>, 
<<Property: geo:spatialDimension, `geo:spatialDimension`>>, 
<<Property: geo:isEmpty, `geo:isEmpty`>>, 
<<Property: geo:isSimple, `geo:isSimple`>> and 
<<Property: geo:hasSerialization, `geo:hasSerialization`>> 
to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-properties[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-properties`]
|===

==== Property: geo:dimension

The property http://www.opengis.net/ont/geosparql#dimension[`geo:dimension`] is used to link the a geometry object to its topological dimension, which must be less than or equal to the coordinate dimension. In non-homogeneous collections, this will return the largest topological dimension of the contained objects.

```turtle
geo:dimension 
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "dimension"@en ;
    skos:definition "The topological dimension of this geometric object, which
                    must be less than or equal to the coordinate dimension. In 
                    non-homogeneous collections, this is the largest 
                    topological dimension of the contained objects."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range xsd:integer ;
.
```

==== Property: geo:coordinateDimension

The property http://www.opengis.net/ont/geosparql#coordinateDimension[`geo:coordinateDimension`] is defined to link a geometry object to the dimension of direct positions (coordinate tuples) used in the geometry's definition.

```turtle
geo:coordinateDimension 
    a rdf:Property, owl:DatatypeProperty;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "coordinate dimension"@en ;
    skos:definition "The number of measurements or axes needed to describe the
                    position of this geometry in a coordinate system."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range xsd:integer ;
.
```

==== Property: geo:spatialDimension

The property http://www.opengis.net/ont/geosparql#spatialDimension[`geo:spatialDimension`] is defined to link a geometry object to the dimension of the spatial portion of the direct positions (coordinate tuples) used in its serializations. If the direct positions do not carry a measure coordinate, this will be equal to the coordinate dimension.

```turtle
geo:spatialDimension 
    a rdf:Property, owl:DatatypeProperty;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "spatial dimension"@en ;
    skos:definition "The number of measurements or axes needed to describe the
                    spatial position of this geometry in a coordinate system."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range xsd:integer ;
.
```

==== Property: geo:hasSpatialResolution

The property http://www.opengis.net/ont/geosparql#hasSpatialResolution[`geo:hasSpatialResolution`] is defined to indicate spatial resolution of the elements within a Geometry. Spatial resolution specifies the level of detail of a Geometry. It the smallest dinstinghuishable distance between adjacent coordinate sets. Therefore this property is not applicable to a point Geometry, because it consists of a single coordinate set.

Since this property is defined for a <<Class: geo:Geometry, `geo:Geometry`>>, all literal representations of that Geometry instance must have the same spatial resolution.

```turtle
geo:hasSpatialResolution 
    a rdf:Property, owl:ObjectProperty;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "has spatial resolution"@en ;
    skos:definition "The spatial resolution of a Geometry"@en ; 
    rdfs:domain geo:Geometry ;
.
```


==== Property: geo:hasMetricSpatialResolution

The property http://www.opengis.net/ont/geosparql#hasMetricSpatialResolution[`geo:hasMetricSpatialResolution`] is similar to <<Property: geo:hasSpatialResolution, `geo:hasSpatialResolution`>>, specifies that the unit of resolution distance is always meter (the standard distance unit of the International System of Units). 

```turtle
geo:hasMetricSpatialResolution 
    a rdf:Property, owl:ObjectProperty;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "has spatial resolution in meters"@en ;
    skos:definition "The spatial resolution of a Geometry in meters."@en ; 
    rdfs:domain geo:Geometry ;
    rdfs:range xsd:double ;
.
```


==== Property: geo:hasSpatialAccuracy

The property http://www.opengis.net/ont/geosparql#hasSpatialAccuracy[`geo:hasSpatialAccuracy`] is applicable when a Geometry is used to represent a Feature. It is expressed as a distance that indicates the truthfullness of the positions (coordinates) that define the Geometry. In this case accuracy defines a zone surrounding each coordinate within wich the real positions are known to be. The accuracy value defines this zone as a distance from the coordinate(s) in all directions (e.g. a line, a circle or a sphere, depending on spatial dimension).

```turtle
geo:hasSpatialAccuracy 
    a rdf:Property, owl:ObjectProperty;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "has spatial accuracy"@en ;
    skos:definition "The positional accuracy of the coordinates of a Geometry."@en ; 
    rdfs:domain geo:Geometry ;
.
```

==== Property: geo:hasMetricSpatialAccuracy

The property http://www.opengis.net/ont/geosparql#hasMetricSpatialAccuracy[`geo:hasMetricSpatialAccuracy`] is similar to <<Property: geo:hasSpatialAccuracy, has spatial accuracy>>, but it is easier to specify and use because the unit of distance is always meter (the standard distance unit of the International System of Units). 

```turtle
geo:hasMetricSpatialAccuracy 
    a rdf:Property, owl:ObjectProperty;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "has spatial accuracy in meters"@en ;
    skos:definition "The positional accuracy of the coordinates of a Geometry in meters."@en ; 
    rdfs:domain geo:Geometry ;
    rdfs:range xsd:double ;
.
```

==== Property: geo:isEmpty

The property http://www.opengis.net/ont/geosparql#isEmpty[`geo:isEmpty`] will indicate a Boolean object set to `true` if and only if the geometry contains no information.

```turtle
geo:isEmpty 
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "is empty"@en ;
    skos:definition "(true) if this geometric object is the empty Geometry. If
                    true, then this geometric object represents the empty point
                    set for the coordinate space."@en ; 
    rdfs:domain geo:Geometry ;
    rdfs:range xsd:boolean ;
.
```

==== Property: geo:isSimple

The property http://www.opengis.net/ont/geosparql#isSimple[`geo:isSimple`] will indicate a Boolean object set to `true`, only if the geometry contains no self-intersections, with the possible exception of its boundary.

```turtle
geo:isSimple 
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "is simple"@en ;
    skos:definition "(true) if this geometric object has no anomalous geometric
                    points, such as self intersection or self tangency."@en ; 
    rdfs:domain geo:Geometry ;
    rdfs:range xsd:boolean ;
.    
```

==== Property: geo:hasSerialization

The property http://www.opengis.net/ont/geosparql#hasSerialization[`geo:hasSerialization`] is defined to connect a geometry with its text-based serialization (e.g., its WKT serialization).

```turtle
geo:hasSerialization 
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:isDefinedBy geo: ; 
    skos:prefLabel "has serialization"@en ;
    skos:definition "Connects a geometry object with its text-based serialization."@en ;
    rdfs:domain geo:Geometry ; 
    rdfs:range rdfs:Literal ;
.
```

NOTE: this property is the generic property used to connect a geometry with its serialization. GeoSPARQL also contains a number of sub properties of this one for connecting serializations of common types with geometries, for example <<Property: geo:asGeoJSON, as GeoJSON>> which can be used for GeoJSON <<GEOJSON>> literals.

=== Geometry Serializations
This section establishes the requirements for representing geometry data in RDF based on different systems.

==== Well-Known Text (serialization=WKT)

This section establishes the requirements for representing geometry data in RDF based on Well-Known Text (WKT) as defined by Simple Features <<ISO19125-1>>. It defines one RDFS Datatype: <<RDFS Datatype: geo:wktLiteral, WKT Literal>> and one property, <<Function: geof:asWKT, as WKT>>.

===== RDFS Datatype: geo:wktLiteral

The datatype http://www.opengis.net/ont/geosparql#wktLiteral[`geo:wktLiteral`] is used to contain the Well-Known Text (WKT) serialization of a geometry.

```turtle
geo:wktLiteral 
    a rdfs:Datatype ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "Well-known Text literal"@en ;
    skos:definition "A Well-known Text serialization of a geometry object."@en ;
.
```

|===
| *Req 14* All RDFS Literals of type <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> shall consist of an optional IRI identifying the coordinate reference system and a required Well Known Text (WKT) description of a geometric value. Valid <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> instances are formed by either a WKT string as defined in <<ISO13249>> or by concatenating a valid absolute IRI, as defined in <<IETF3987>>, enclose in angled brackets (`<` & `>`) followed by a single space (Unicode U+0020 character) as a separator, and a WKT string as defined in <<ISO13249>>.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-literal[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-literal`]
|===

The following _ABNF_ <<IETF5234>> syntax specification formally defines this literal:

```
wktLiteral ::= opt-iri-and-space geometric-data

opt-iri-and-space = "<" IRI ">" LWSP / ""
```

The token `opt-iri-and-space` may be either an IRI and space or nothing (`""`), the token `IRI` (Internationalized Resource Identifier) is essentially a web address and is defined in <<IETF3987>> and the token `LWSP`, is one or more white space characters, as defined in <<IETF5234>>. `geometric-data` is the Well-Known Text representation of the geometry, defined in <<ISO13249>>.

In the absence of a leading spatial reference system IRI, the following spatial reference system IRI will be assumed: http://www.opengis.net/def/crs/OGC/1.3/CRS84[`+<http://www.opengis.net/def/crs/OGC/1.3/CRS84>+`]. This IRI denotes WGS 84 longitude-latitude.

|===
| *Req 15* The IRI http://www.opengis.net/def/crs/OGC/1.3/CRS84[`+<http://www.opengis.net/def/crs/OGC/1.3/CRS84>+`] shall be assumed as the spatial reference system for <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> instances that do not specify an explicit spatial reference system IRI.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-literal-default-srs[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-literal-default-srs`]
|===

The OGC maintains a set of SRS IRIs under the `+http://www.opengis.net/def/crs/+` namespace and IRIs from this set are recommended for use, however others may also be used, as long as they are valid IRIs.

|===
| *Req 16* Coordinate tuples within <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> shall be interpreted using the axis order defined in the spatial reference system used.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-axis-order[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-axis-order`]
|===

The example <<RDFS Datatype: geo:wktLiteral, WKT Literal>> below encodes a point geometry using the default WGS84 geodetic longitude-latitude spatial reference system:

```turtle
"Point(-83.38 33.95)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>
```

A second example below encodes the same point as encoded in the example above but using a SRS identified by http://www.opengis.net/def/SRS/EPSG/0/4326[`+http://www.opengis.net/def/SRS/EPSG/0/4326+`]: a WGS 84 geodetic latitude-longitude spatial reference system (note that this spatial reference system defines a different axis order):

```turtle
"<http://www.opengis.net/def/crs/EPSG/0/4326> Point(33.95 -83.38)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>
```

|===
| *Req 17* An empty RDFS Literal of type <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> shall be interpreted as an empty geometry.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-literal-empty[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/wkt-literal-empty`]
|===

===== Property: geo:asWKT

The property http://www.opengis.net/ont/geosparql#asWKT[`geo:asWKT`] is defined to link a geometry with its WKT serialization.

|===
| *Req 18* Implementations shall allow the RDF property <<Property: geo:asWKT, `geo:asWKT`>> to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-as-wkt-literal[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-as-wkt-literal`]
|===

```turtle
geo:asWKT 
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:subPropertyOf geo:hasSerialization ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "as WKT"@en ;
    skos:definition "The WKT serialization of a geometry."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range geo:wktLiteral ;
.
```

===== Function: geof:asWKT

```
geof:asWKT (geom: ogc:geomLiteral): geo:wktLiteral
```

The function http://www.opengis.net/def/function/geosparql/asWKT[`geof:asWKT`] converts `geom` to an equivalent WKT representation preserving the coordinate reference system. 

|===
| *Req 19* Implementations shall support <<Property: geo:asWKT, `geo:asWKT`>> as a SPARQL extension function.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asWKT-function[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asWKT-function`]
|===

==== Geography Markup Language (serialization=GML)

This section establishes requirements for representing geometry data in RDF based on GML as defined by Geography Markup Language Encoding Standard <<OGC07-036>>. It defines one RDFS Datatype:
<<RDFS Datatype: geo:gmlLiteral, GML Literal>> and one property, <<Function: geof:asGML, as GML>>.

===== RDFS Datatype: geo:gmlLiteral

The datatype http://www.opengis.net/ont/geosparql#gmlLiteral[`geo:gmlLiteral`] is used to contain the Geography Markup Language (GML) serialization of a geometry.

```turtle
geo:gmlLiteral 
    a rdfs:Datatype ;
    rdfs:isDefinedBy geo: ; 
    skos:prefLabel "GML literal"@en ;
    skos:definition "The datatype of GML literal values"@en ;
.
```

Valid <<RDFS Datatype: geo:gmlLiteral, GML Literal>> instances are formed by encoding geometry information as a valid element from the GML schema that implements a subtype of `GM_Object`. For example, in GML 3.2.1 this is every element directly or indirectly in the substitution group of the element `{http://www.opengis.net/ont/gml/3.2}AbstractGeometry`. In GML 3.1.1 and GML 2.1.2 this is every element directly or indirectly in the substitution group of the element `{http://www.opengis.net/ont/gml}_Geometry`.

|===
| *Req 20* All <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> instances shall consist of a valid element from the GML schema that implements a subtype of `GM_Object` as defined in <<OGC07-036>>.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/gml-literal[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/gml-literal`]
|===

The example <<RDFS Datatype: geo:gmlLiteral, GML Literal>> below encodes a point geometry in the WGS 84 geodetic longitude-latitude spatial reference system using GML version 3.2:

```turtle
"""
<gml:Point 
        srsName=\"http://www.opengis.net/def/crs/OGC/1.3/CRS84\" 
        xmlns:gml=\"http://www.opengis.net/ont/gml\">
    <gml:pos>-83.38 33.95</gml:pos>
</gml:Point>
"""^^<http://www.opengis.net/ont/geosparql#gmlLiteral>
```

|===
| *Req 21* An empty <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> shall be interpreted as an empty geometry.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/gml-literal-empty[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/gml-literal-empty`]
|===

|===
| *Req 22* Implementations shall document supported GML profiles.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/gml-profile[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/gml-profile`]
|===

===== Property: geo:asGML

The property http://www.opengis.net/ont/geosparql#asGML[`geo:asGML`] is defined to link a geometry with its GML serialization.

|===
| *Req 23* Implementations shall allow the RDF property <<Property: geo:asGML, `geo:asGML`>> to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-as-gml-literal[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-as-gml-literal`]
|===

```turtle
geo:asGML 
    a rdf:Property ; 
    rdfs:subPropertyOf geo:hasSerialization ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "as GML"@en ;
    skos:definition "The GML serialization of a geometry."@en ; 
    rdfs:domain geo:Geometry ;
    rdfs:range geo:gmlLiteral ;
.
```

===== Function: geof:asGML

```
geof:asGML (geom: ogc:geomLiteral, gmlProfile: xsd:string): geo:gmlLiteral
```

The function http://www.opengis.net/def/function/geosparql/asGML[`geof:asGML`] converts `geom` to an equivalent GML representation defined by a gmlProfile version string preserving the coordinate reference system. 

|===
| *Req 24* Implementations shall support <<Function: geof:asGML, `geof:asGML`>> as a SPARQL extension function.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asGML-function[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asGML-function`]
|===

==== GeoJSON (serialization=GEOJSON)

This section establishes requirements for representing geometry data in RDF based on GeoJSON as defined by <<GeoJSON>>. It defines one RDFS Datatype:
<<RDFS Datatype: geo:geoJSONLiteral, GeoJSON Literal>> and one property, <<Function: geof:asGeoJSON, as GeoJSON>>.

===== RDFS Datatype: geo:geoJSONLiteral

The datatype http://www.opengis.net/ont/geosparql#gmlLiteral[`geo:geoJSONLiteral`] is used to contain the Geo JavaScript Object Notation (GeoJSON) serialization of a geometry.

```turtle
geo:geoJSONLiteral a rdfs:Datatype ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "GeoJSON Literal"@en ;
    skos:definition "A GeoJSON serialization of a geometry object."@en .
```

Valid <<RDFS Datatype: geo:geoJSONLiteral, GeoJSON Literal>> instances are formed by encoding geometry information as a Geometry object as defined in the GeoJSON specification <<GEOJSON>>.

|===
| *Req 25* All <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> instances shall consist of the Geometry objects as defined in the GeoJSON specification <<GEOJSON>>.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geojson-literal[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geojson-literal`]
|===

|===
| *Req 26* RDFS Literals of type <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> do not contain a SRS definition. All literals of this type shall, according to the GeoJSON specification, be encoded only in, and be assumed to use, the WGS84 geodetic longitude-latitude spatial reference system (http://www.opengis.net/def/crs/OGC/1.3/CRS84[`http://www.opengis.net/def/crs/OGC/1.3/CRS84`]).
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geojson-literal-srs[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geojson-literal-srs`]
|===

The example <<RDFS Datatype: geo:geoJSONLiteral, GeoJSON Literal>> below encodes a point geometry using the default WGS84 geodetic longitude-latitude spatial reference system for Simple Features 1.0:

```turtle
"""
{"type": "Point", "coordinates": [-83.38,33.95]}
"""^^<http://www.opengis.net/ont/geosparql#geoJSONLiteral>
```

|===
| *Req 27* An empty RDFS Literal of type <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> shall be interpreted as an empty geometry, i.e. `{"geometry": null}` in GeoJSON .
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geojson-literal-empty[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geojson-literal-empty`]
|===

===== Property: geo:asGeoJSON

The property http://www.opengis.net/ont/geosparql#asGeoJSON[`geo:asGeoJSON`] is defined to link a geometry with its GeoJSON serialization.

|===
| *Req 28* Implementations shall allow the RDF property <<Property: geo:asGeoJSON, `geo:asGeoJSON`>> to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geometry-as-geojson-literal[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geometry-as-geojson-literal`]
|===

```turtle
geo:asGeoJSON 
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:subPropertyOf geo:hasSerialization ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "as GeoJSON"@en ;
    skos:definition "The GeoJSON serialization of a geometry."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range geo:geoJSONLiteral ;
.
```

===== Function: geof:asGeoJSON

```
geof:asGeoJSON (geom: ogc:geomLiteral): geo:geoJSONLiteral
```

The function http://www.opengis.net/def/function/geosparql/asGeoJSON[`geof:asGeoJSON`] converts `geom` to an equivalent GeoJSON representation. Coordinates are converted to the CRS84 coordinate system, the only valid coordinate system to be used in a GeoJSON literal. 

|===
| *Req 29* Implementations shall support <<Function: geof:asGeoJSON, `geof:asGeoJSON`>> as a SPARQL extension function.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asGeoJSON-function[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asGeoJSON-function`]
|===

==== Keyhole Markup Language (serialization=KML)

This section establishes requirements for representing geometry data in RDF based on KML as defined by <<OGCKML>>. It defines one RDFS Datatype:
<<RDFS Datatype: geo:kmlLiteral, KML Literal>> and one property, <<Function: geof:asKML, as KML>>.

===== RDFS Datatype: geo:kmlLiteral

The datatype http://www.opengis.net/ont/geosparql#kmlLiteral[`geo:kmlLiteral`] is used to contain the Keyhole Markup Language (KML) serialization of a geometry.

```turtle
geo:kmlLiteral 
    a rdfs:Datatype ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "KML Literal"@en ;
    skos:definition "A KML serialization of a geometry object."@en ;
.
```

Valid <<RDFS Datatype: geo:kmlLiteral, KML Literal>> instances are formed by encoding geometry information as a Geometry object as defined in the KML specification <<OGCKML>>.

|===
| *Req 30* All <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> instances shall consist of the Geometry objects as defined in the KML specification <<OGCKML>>.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/kml-literal[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/kml-literal`]
|===

|===
| *Req 31* RDFS Literals of type <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> do not contain a SRS definition. All literals of this type shall according to the KML specification only be encoded in and assumed to use the WGS84 geodetic longitude-latitude spatial reference system (http://www.opengis.net/def/crs/OGC/1.3/CRS84[`http://www.opengis.net/def/crs/OGC/1.3/CRS84`]).
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/kml-literal-srs[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/kml-literal-srs`]
|===

The example <<RDFS Datatype: geo:kmlLiteral, KML Literal>> below encodes a point geometry using the default WGS84 geodetic longitude-latitude spatial reference system for Simple Features 1.0:

```turtle
"""
<Point xmlns=\"http://www.opengis.net/kml/2.2\">
    <coordinates>-83.38,33.95</coordinates>
</Point>
"""^^<http://www.opengis.net/ont/geosparql#kmlLiteral>
```

|===
| *Req 32* An empty RDFS Literal of type <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> shall be interpreted as an empty geometry .
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/kml-literal-empty[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/kml-literal-empty`]
|===

===== Property: geo:asKML

The property http://www.opengis.net/ont/geosparql#asKML[`geo:asKML`] is defined to link a geometry with its KML serialization.

|===
| *Req 33* Implementations shall allow the RDF property <<Property: geo:asKML, `geo:asKML`>> to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geometry-as-kml-literal[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geometry-as-kml-literal`]
|===

The property <<Property: geo:asKML, as KML>> is used to link a geometric element with its KML serialization.

```turtle
geo:asKML 
    a rdf:Property, owl:DatatypeProperty;
    rdfs:subPropertyOf geo:hasSerialization ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "as KML"@en ;
    skos:definition "The KML serialization of a geometry."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range geo:kmlLiteral ;
.
```

===== Function: geof:asKML

```
geof:asKML (geom: ogc:geomLiteral): geo:kmlLiteral
```

The function http://www.opengis.net/def/function/geosparql/asKML[`geof:asKML`] converts `geom` to an equivalent KML representation. Coordinates are converted to the CRS84 coordinate system, the only valid coordinate system to be used in a KML literal. 

|===
| *Req 34* Implementations shall support <<Function: geof:asKML, `geof:asKML`>> as a SPARQL extension function.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asKML-function[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asKML-function`]
|===

==== Discrete Global Grid System (serialization=DGGS)

This section establishes the requirements for representing Discrete Global Grid System (DGGS) geometry data as RDF literals. The form of representation is specific to individual DGGS implementations: known DGGSes are not compatible or even very similar. 

Here is defined one RDFS Datatypes:
http://www.opengis.net/ont/geosparql#dggsLiteral[`+http://www.opengis.net/ont/geosparql#dggsLiteral+`] and one property, http://www.opengis.net/ont/geosparql#asDGGS[`+http://www.opengis.net/ont/geosparql#asDGGS+`]. 

NOTE: The datatype defined here is for an abstract DGGS implementation (<<RDFS Datatype: geo:dggsLiteral, DGGS Literal>>) but concrete ones should be used in real implementations. For example, the AusPIX DGGS <<AUSPIX>> might implement something similar to `ex:auspixDggsLiteral`.

===== RDFS Datatype: geo:dggsLiteral

The datatype http://www.opengis.net/ont/geosparql#dggsLiteral[`geo:dggsLiteral`] is used to contain the Discrete Global Grid System (DGGS) serialization of a geometry.

```turtle
geo:dggsLiteral 
    a rdfs:Datatype ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "DGGS Literal"@en ;
    skos:definition "A textual serialization of a Discrete Global Grid System (DGGS) geometry object."@en 
.
```

Valid <<RDFS Datatype: geo:dggsLiteral, DGGS Literal>> instances are formed by encoding geometry information according to specific DGGS implementation. The specific implementation should be indicated by use of a subclass of the `geo:dggsLiteral` datatype. 

|===
| *Req 35* All RDFS Literals of type <<RDFS Datatype: geo:dggsLiteral, `geo:dggsLiteral`>> shall consist of a DGGS geometry serialization formulated according to a specific DGGS.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/dggs-literal[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/dggs-literal`]
|===

|===
| *Req 36* An empty RDFS Literal of type <<RDFS Datatype: geo:dggsLiteral, `geo:dggsLiteral`>>, or one of its data subtypes, shall be interpreted as an empty `geo:Geometry`.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/dggs-literal-empty[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/dggs-literal-empty`]
|===

An example of a literal for concrete DGGS, AusPIX, could be

```turtle
ex:auspixDggsLiteral 
    a rdfs:Datatype ;
    skos:prefLabel "AusPIX DGGS Literal"@en ;
    skos:definition "A textual serialization of an AusPIX Discrete Global Grid System (DGGS) geometry object."@en ;
.
```

A single _Cell_ geometry encoded according to the AusPIX DGGS using the example literal above is given below. The single cell value of _R3234_ is analogous to either a `Point` or simple `Polygon` in WKT geometries.

```turtle
"CellList (R3234)"^^<http://example.com#auspixDggsLiteral>
```

NOTE: What `R3234` means, or the meaning of any other element within a concrete DGGS literal is not handled by GeoSPARQL but is expected to be handled by that DGGS' specification, just as GeoPSARQL does not delve into the internals of other geometry formats such as WKT or GeoJSON.

===== Property: geo:asDGGS

The property http://www.opengis.net/ont/geosparql#asDGGS[`geo:asDGGS`] is defined to link a geometry with its DGGS serialization.

|===
| *Req 38* Implementations shall allow the RDF property 
<<Property: geo:asDGGS, `geo:asDGGS`>> 
to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geometry-as-dggs-literal[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/geometry-as-dggs-literal`]
|===

```turtle
geo:asDGGS 
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:subPropertyOf geo:hasSerialization ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "as DGGS"@en ;
    skos:definition "A DGGS serialization of a geometry."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range geo:dggsLiteral ;
.
```

NOTE: It is expected that this property will be used to indicate specific DGGS data types, such as the example `ex:auspixDggsLiteral`, described above, as opposed to the generic <<RDFS Datatype: geo:dggsLiteral, DGGS Literal>>.

===== Function: geof:asDGGS

```
geof:asDGGS (geom: ogc:geomLiteral, specificDggsDatatype: xsd:anyURI): geo:DggsLiteral
```

The function http://www.opengis.net/def/function/geosparql/asDGGS[`geof:asDGGS`] converts `geom` to an equivalent DGGS representation, formulated according to the specific DGGS literal indicated using the `specificDggsDatatype` parameter.

|===
| *Req 39* Implementations shall support <<Function: geof:asDGGS, `geof:asDGGS`>>  as a SPARQL extension function.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asDGGS-function[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asDGGS-function`]
|===

=== Non-topological Query Functions

This clause defines SPARQL functions for performing non-topological spatial operations.

|===
| *Req 40* Implementations shall support the functions 
<<Function: geof:distance, `geof:distance`>>, 
<<Function: geof:buffer, `geof:buffer`>>, 
<<Function: geof:intersection, `geof:intersection`>>, 
<<Function: geof:union, `geof:union`>>, 
<<Function: geof:isEmpty, `geof:isEmpty`>>, 
<<Function: geof:isSimple, `geof:isSimple`>>, 
<<Function: geof:area, `geof:area`>>, 
<<Function: geof:length, `geof:length`>>,
<<Function: geof:numGeometries, `geof:numGeometries`>>,
<<Function: geof:geometryN, `geof:geometryN`>>, 
<<Function: geof:transform, `geof:transform`>>,
<<Function: geof:dimension, `geof:dimension`>>, 
<<Function: geof:difference, `geof:difference`>>, 
<<Function: geof:symDifference, `geof:symDifference`>>, 
<<Function: geof:envelope, `geof:envelope`>> and 
<<Function: geof:boundary, `geof:boundary`>> 
as SPARQL extension functions, consistent with the definitions of their corresponding functions in Simple Features <<ISO19125-1>> (`distance`, `buffer`, `intersection`, `union`, `isEmpty`, `isSimple`, `area`, `length`, `numGeometries`, `geometryN`, `transform`, `dimension`, `difference`, `symDifference`, `envelope` and `boundary` respectively) and other attached definitions and also 
http://www.opengis.net/def/function/geosparql/minX[`geof:maxX`],
http://www.opengis.net/def/function/geosparql/maxY[`geof:maxY`], 
http://www.opengis.net/def/function/geosparql/maxZ[`geof:maxZ`],  
http://www.opengis.net/def/function/geosparql/minX[`geof:minX`], 
http://www.opengis.net/def/function/geosparql/minY[`geof:minY`] and 
http://www.opengis.net/def/function/geosparql/minZ[`geof:minZ`]
SPARQL extension functions.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/query-functions[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/query-functions`]
|===

An invocation of any of the following functions with invalid arguments produces an error. An invalid argument includes any of the following:

* An argument of an unexpected type
* An invalid geometry literal value
* A geometry literal from a spatial reference system that is incompatible with the spatial reference system used for calculations
* An invalid units IRI

For further discussion of the effects of errors during FILTER evaluation, consult Section 17footnote:[<https://www.w3.org/TR/sparql11-query/#expressions>] of the SPARQL specification <<SPARQL>>.

Note that returning values instead of raising an error serves as an extension mechanism of SPARQL.

From Section 17.3.1footnote:[<https://www.w3.org/TR/sparql11-query/#operatorExtensibility>] of the SPARQL specification <<SPARQL>>:

[quote]
SPARQL language extensions may provide additional associations between operators and operator functions; ... No additional operator may yield a result that replaces any result other ... . The consequence of this rule is that SPARQL `FILTER` s will produce at least the same intermediate bindings after applying a `FILTER` as an unextended implementation.

This extension mechanism enables GeoSPARQL implementations to simultaneously support multiple geometry serializations. For example, a system that supports <<RDFS Datatype: geo:wktLiteral, WKT Literal>> serializations may also support <<RDFS Datatype: geo:gmlLiteral, GML Literal>> serializations and consequently would not raise an error if it encounters multiple geometry datatypes while processing a given query.

NOTE: Several non-topological query functions use a unit of measure IRI. The OGC has recommended units of measure vocabularies for use, see the OGC Definitions Serverfootnote:[https://www.ogc.org/def-server].

==== Function: geof:distance

```
geof:distance (geom1: ogc:geomLiteral, 
               geom2: ogc:geomLiteral, 
               units: xsd:anyURI): xsd:double
```

Returns the shortest distance between any two Points in the two geometric objects. Calculations are in spatial reference system of `geom1`.

==== Function: geof:buffer

```
geof:buffer (geom: ogc:geomLiteral, 
             radius: xsd:double, 
             units: xsd:anyURI): ogc:geomLiteral
```

Returns a geometric object that represents all Points whose distance from `geom1` is less than or equal to the `radius` measured in `units`. Calculations are in the spatial reference system of `geom1`.

==== Function: geof:isEmpty

```
geof:isEmpty (geom1: ogc:geomLiteral): xsd:boolean
```

Returns true if `geom1` is an empty geometry, i.e. contains no coordinates.

==== Function: geof:isSimple

```
geof:isSimple (geom1: ogc:geomLiteral): xsd:boolean
```

Returns true if `geom1` is a simple geometry, i.e. has no anomalous geometric points, such as self intersection or self tangency.

==== Function: geof:area

```
geof:area (geom1: ogc:geomLiteral): xsd:double
```

Returns the area of `geom1` in squaremeters.

==== Function: geof:length

```
geof:length (geom1: ogc:geomLiteral): xsd:double
```

Returns the length of `geom1` in meters.

==== Function: geof:dimension

```
geof:dimension (geom1: ogc:geomLiteral): xsd:integer
```

Returns the dimension of `geom1`.

==== Function: geof:numGeometries

```
geof:numGeometries (geom1: ogc:geomLiteral): xsd:integer
```

Returns the number of geometries of `geom1`.

==== Function: geof:geometryN

```
geof:geometryN (geom1: ogc:geomLiteral): xsd:integer
```

Returns the nth geometry of `geom1` if it is a GeometryCollection .

==== Function: geof:transform

```
geof:transform (geom: ogc:geomLiteral, srsIRI: xsd:anyURI): ogc:geomLiteral
```

http://www.opengis.net/def/function/geosparql/transform[geof:transform] converts `geom` to a spatial reference system defined by srsIRI. The function raises an error if a transformation is not mathematically possible.

NOTE: We recommend that implementers use the same literal type as a result of this function that is passed as a parameter to this function.

==== Function: geof:intersection

```
geof:intersection (geom1: ogc:geomLiteral,
                   geom2: ogc:geomLiteral): ogc:geomLiteral
```

Returns a geometric object that represents all Points in the intersection of `geom1` with `geom2`. Calculations are in the spatial reference system of `geom1`.

==== Function: geof:union

```
geof:union (geom1: ogc:geomLiteral, 
            geom2: ogc:geomLiteral): ogc:geomLiteral
```

This function returns a geometric object that represents all Points in the union of `geom1` with `geom2`. Calculations are in the spatial reference system of `geom1`.

==== Function: geof:difference

```
geof:difference (geom1: ogc:geomLiteral, 
                 geom2: ogc:geomLiteral): ogc:geomLiteral
```

This function returns a geometric object that represents all Points in the set difference of `geom1` with `geom2`. Calculations are in the spatial reference system of `geom1`.

==== Function: geof:symDifference

```
geof:symDifference (geom1: ogc:geomLiteral, 
                    geom2: ogc:geomLiteral): ogc:geomLiteral
```

This function returns a geometric object that represents all Points in the set symmetric difference of `geom1` with `geom2`. Calculations are in the spatial reference system of `geom1`.

==== Function: geof:envelope

```
geof:envelope (geom1: ogc:geomLiteral): ogc:geomLiteral
```

This function returns the minimum bounding box - a rectangle - of `geom1`. Calculations are in the spatial reference system of `geom1`.

==== Function: geof:boundary

```
geof:boundary (geom1: ogc:geomLiteral): ogc:geomLiteral
```

This function returns the closure of the boundary of `geom1`. Calculations are in the spatial reference system of `geom1`.

==== Function: geof:convexHull

```
geof:convexHull (geom1: ogc:geomLiteral): ogc:geomLiteral
```

The function http://www.opengis.net/def/function/geosparql/convexHull[`geof:convexHull`] returns a geometric object that represents all Points in the convex hull of `geom1`. Calculations are in the spatial reference system of `geom1`.


==== Function: geof:maxX

```
geof:maxX (geom: ogc:geomLiteral): xsd:double
```

The function http://www.opengis.net/def/function/geosparql/maxX[`geof:maxX`] returns the maximum X coordinate for `geom`.

==== Function: geof:maxY

```
geof:maxY (geom: ogc:geomLiteral): xsd:double
```

The function http://www.opengis.net/def/function/geosparql/maxY[`geof:maxY`] returns the maximum Y coordinate for `geom`.

==== Function: geof:maxZ

```
geof:maxZ (geom: ogc:geomLiteral): xsd:double
```

The function http://www.opengis.net/def/function/geosparql/maxZ[`geof:maxZ`] returns the maximum Z coordinate for `geom`.

==== Function: geof:minX

```
geof:minX (geom: ogc:geomLiteral): xsd:double
```

The function http://www.opengis.net/def/function/geosparql/minX[`geof:minX`] returns the minimum X coordinate for `geom`.

==== Function: geof:minY

```
geof:minY (geom: ogc:geomLiteral): xsd:double
```

The function http://www.opengis.net/def/function/geosparql/minY[`geof:minY`] returns the minimum Y coordinate for `geom`.

==== Function: geof:minZ

```
geof:minZ (geom: ogc:geomLiteral): xsd:double
```

The function http://www.opengis.net/def/function/geosparql/minZ[`geof:minZ`] returns the minimum Z coordinate for `geom`.

==== Function: geof:getSRID

```
geof:getSRID (geom: ogc:geomLiteral): xsd:anyURI
```

Returns the spatial reference system IRI for `geom`.

|===
| *Req 41* Implementations shall support http://www.opengis.net/def/function/geosparql/getSRID[`geof:getSRID`] as a SPARQL extension function.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/srid-function[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/srid-function`]
|===

=== Spatial Aggregate Functions
This clause defines SPARQL functions for performing spatial aggregations of data.

|===
| *Req 42* Implementations shall support 
<<Function: geof:aggBoundingBox,`geof:aggBoundingBox`>>, 
<<Function: geof:aggBoundingCircle,`geof:aggBoundingCircle`>>, 
<<Function: geof:aggCentroid,`geof:aggCentroid`>>, 
<<Function: geof:aggConcatLines,`geof:aggConcatLines`>>, 
<<Function: geof:aggConcaveHull,`geof:aggConcaveHull`>>, 
<<Function: geof:aggConvexHull,`geof:aggConvexHull`>> and 
<<Function: geof:aggUnion,`geof:aggUnion`>>
as a SPARQL extension functions.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/sa-functions[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/sa-functions`]
|===

==== Function: geof:aggBoundingBox
```
geof:aggBoundingBox (geom: ogc:geomLiteral): ogc:geomLiteral
```

The function http://www.opengis.net/def/function/geosparql/aggBoundingBox[`geof:aggBoundingBox`] calculates a minimum bounding box - rectangle - of the set of given geometries.

==== Function: geof:aggBoundingCircle
```
geof:aggBoundingCircle (geom: ogc:geomLiteral): ogc:geomLiteral
```

The function http://www.opengis.net/def/function/geosparql/aggBoundingCircle[`geof:aggBoundingCircle`] calculates a minimum bounding circle of the set of given geometries.

==== Function: geof:aggCentroid

```
geof:aggCentroid (geom: ogc:geomLiteral): ogc:geomLiteral
```

The function http://www.opengis.net/def/function/geosparql/aggCentroid[`geof:aggCentroid`] valculates the centroid of the set of given geometries.

==== Function: geof:aggConcatLines

```
geof:aggConcatLines (geom: ogc:geomLiteral): ogc:geomLiteral
```

The function http://www.opengis.net/def/function/geosparql/aggConcatLines[`geof:aggConcatLines`]  Concatenates a set of LineStrings.

==== Function: geof:aggConcaveHull

```
geof:aggConcaveHull (geom: ogc:geomLiteral, targetPercent: xsd:double): ogc:geomLiteral
```

The function http://www.opengis.net/def/function/geosparql/aggConcaveHull[`geof:aggConcaveHull`] calculates the concave hull of the set of given geometries.

==== Function: geof:aggConvexHull

```
geof:aggConvexHull (geom: ogc:geomLiteral): ogc:geomLiteral
```

The function http://www.opengis.net/def/function/geosparql/aggConvexHull[`geof:aggConvexHull`] calculates the convex hull of the set of given geometries.

NOTE: This function is similar in name to <<Function: geof:aggConvexHull, geof:aggConvexHull>> used to calculate the convex hull of just one geometry.

==== Function: geof:aggUnion

```
geof:aggUnion (geom: ogc:geomLiteral): ogc:geomLiteral
```

The function http://www.opengis.net/def/function/geosparql/aggUnion[`geof:aggUnion`] calculates the union of the set of given geometries.

NOTE: This function is similar in name to <<Function: geof:aggUnion, geof:aggUnion>> used to calculate the union of just two geometries.
