[#geometry_style_extension]
== Geometry Style Extension

This section establishes the introduction of geometry styles into the GeoSPARQL standard.

A geometry style is a set of instructions which allow for the representation of the geometry in a given context.

==== Class: geo:Style

The class http://www.opengis.net/ont/geosparql#Style[`geo:Style`] depicts the abstract representation of the style of a geospatial feature and is defined by the following:

```turtle
geo:Style
    a rdfs:Class, owl:Class ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "Style"@en ;
    skos:definition "A representation of a way to style a geospatial feature on e.g. a map representation."@en ;
    skos:note "A Feature Style expresses one or many style representations which can be used to display a spatial object in a suitable rendering."@en ;
.
```

[#req_core_style-class]
|===
| *Req {counter:req}* Implementations shall allow the RDFS class <<Class: geo:Style, `geo:Style`>> to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.0/req/core/style-class[`http://www.opengis.net/spec/geosparql/1.0/req/core/style-class`]
|===

==== Property: geo:hasStyle

The property http://www.opengis.net/ont/geosparql#hasStyle[`geo:hasStyle`] links a <<Class: geo:SpatialObject, `geo:SpatialObject`>> to a <<Class: geo:Style, `geo:Style`>> representation.

```turtle
ex:mystyle rdf:type geo:Style .
ex:myfeature rdf:type geo:Feature .
ex:myfeature_geom rdf:type sf:Point .
ex:myfeature geo:hasGeometry ex:myfeature_geom .
ex:myfeature geo:hasStyle geo:mystyle .
.
```

==== Property: geo:markerIcon

The property http://www.opengis.net/ont/geosparql#markerIcon[`geo:markerIcon`] links a <<Class: geo:Style, `geo:Style`>> to a representation of an icon which can be used on map representation as a marker or along or within a geometry. The value of this property may either be an SVG representation in a geo:svgLiteral or a link to an image representation, represented as an xsd:anyURI.

```turtle
ex:mystyle rdf:type geo:Style .
ex:mystyle geo:markerIcon "<svg>...</svg>"^^geo:svgLiteral .
ex:mystyle geo:markerIcon "http://......jpg"^^xsd:anyURI .
```

==== Property: geo:asGeoCSS

The property http://www.opengis.net/ont/geosparql#asGeoCSS[`geo:asGeoCSS`] links a <<Class: geo:Style, `geo:Style`>> to a serialization of the style in CSS rendered in a geo:geocssLiteral.

```turtle
ex:mystyle rdf:type geo:Style .
ex:mystyle geo:asGeoCSS "stroke:black,fill:red,stroke-width:3,fill-opacity:0.6"^^geo:geocssLiteral
.
```

==== Datatype: geo:geocssLiteral

The literal http://www.opengis.net/ont/geosparql#geocssLiteral[`geo:geocssLiteral`] encodes a subset of CSS statements which are applicable to geometry representations.
The subset of CSS statements is limited to the statements which are applicable to SVG representations.
In particular these are the following attributes:

```css
fill: color
stroke: color
stroke-width: number
fill-opacity: number
```

==== Datatype: geo:svgLiteral

The literal http://www.opengis.net/ont/geosparql#svgLiteral[`geo:svgLiteral`] encodes a SVG representation in plain text.

```svg
ex:mystyle geo:markerIcon "<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"/></svg>"^^geo:svgLiteral .
```



