== RDFS Entailment Extension (relation_family, serialization, version)

This clause establishes the _RDFS Entailment Extension (relation_family, serialization, version)_ parameterized requirements class, with IRI `/req/rdfs-entailment-extension`, which defines a mechanism for matching implicitly-derived RDF triples in GeoSPARQL queries. This class is parameterized to give implementations flexibility in the topological relation families and geometry types that they choose to support. This requirements class has a single corresponding conformance class _RDFS Entailment Extension (relation_family, serialization, version)_, `with IRI /conf/rdfs-entailment-extension`.

=== Parameters

* *relation_family*: Specifies the set of topological spatial relations to support.  
* *serialization*: Specifies the serialization standard to use for geometry literals.  
* *version*: Specifies the version of the serialization format used.  

=== Common Requirements

The basic mechanism for supporting RDFS entailment has been defined by the W3C SPARQL 1.1 RDFS Entailment Regime <<SPARQLENT>>.

[#req_rdfs_entailment_extension_bgp-rdfs-ent]
|===
| *Req 50* Basic graph pattern matching shall use the semantics defined by the RDFS Entailment Regime <<SPARQLENT>>.
|http://www.opengis.net/spec/geosparql/1.0/req/rdfs-entailment-extension/bgp-rdfs-ent[`http://www.opengis.net/spec/geosparql/1.0/req/rdfs-entailment-extension/bgp-rdfs-ent`]
|===

=== WKT Serialization (serialization=WKT)

This section establishes the requirements for representing geometry data in RDF based on WKT as defined by Simple Features <<ISO19125-1>>.

==== Geometry Class Hierarchy

The Simple Features specification presents a geometry class hierarchy. It is straightforward to represent this class hierarchy in RDFS and OWL by constructing IRIs for geometry classes using the following pattern: `+http://www.opengis.net/ont/sf#{geometry class}+` and by asserting appropriate http://www.w3.org/2000/01/rdf-schema#subClassOf[`rdfs:subClassOf`] statements. The _Simple Features Vocabulary_ resource within GeoSPARQL 1.1 (simpling resource to this specification) does this. The following list gived the class hierarchy with each indented item being a subclass of the item in the line above. The class heirarchy starts with GeoSPARQL's `geo:Geometry` class of which `sf:Geometry` is a subclass:

```
geo:Geometry
    sf:Geometry
        sf:Curve
            sf:LineString
                sf:Line
                sf:LinearRing
        sf:GeometryCollection
            sf:MultiCurve
                sf:MultiLineString
            sf:MultiPoint
            sf:MultiSurface
                sf:MultiPolygon
        sf:Point
        sf:Surface
            sf:Polygon
                sf:Envelope
                sf:Triangle
            sf:PolyhedralSurface
                sf:TIN
```

The following example RDF snippet below encodes the _Simple Features vocabulary_ Polygon class:

```turtle
sf:Polygon 
    a rdfs:Class, owl:Class ;
    rdfs:isDefinedBy <http://www.opengis.net/ont/sf> ;
    skos:prefLabel "Polygon"@en ;
    rdfs:subClassOf sf:Surface ;
    skos:definition "A planar surface defined by 1 exterior boundary and 0 or 
                    more interior boundaries"@en ;
.
```



[#req_rdfs_entailment_extension_wkt-geometry-types]
|===
| *Req 51* Implementations shall support graph patterns involving terms from an RDFS/OWL class hierarchy of geometry types consistent with the one in the specified version of Simple Features <<ISO19125-1>>.
|http://www.opengis.net/spec/geosparql/1.0/req/rdfs-entailment-extension/wkt-geometry-types[`http://www.opengis.net/spec/geosparql/1.0/req/rdfs-entailment-extension/wkt-geometry-types`]
|===

=== GML Serialization (serialization=GML)

This section establishes requirements for representing geometry data in RDF based on GML as defined by Geography Markup Language Encoding Standard <<OGC07-036>>.

==== Geometry Class Hierarchy

An RDF/OWL class hierarchy can be generated from the GML schema that implements `GM_Object` by constructing IRIs for geometry classes using the following pattern: `+http://www.opengis.net/ont/gml#{GML Element}+` and by asserting appropriate http://www.w3.org/2000/01/rdf-schema#subClassOf[`rdfs:subClassOf`] statements.

The example RDF snippet below encodes the Polygon class from GML 3.2.

```turtle
gml:Polygon 
    a rdfs:Class, owl:Class ;
    skos:prefLabel "Polygon"@en ;
    rdfs:subClassOf gml:SurfacePatch ;
    skos:definition "A planar surface defined by 1 exterior boundary and 0 or
                    more interior boundaries."@en ;
.
```
[#req_rdfs_entailment_extension_gml-geometry-types]
|===
| *Req 52* Implementations shall support graph patterns involving terms from an RDFS/OWL class hierarchy of geometry types consistent with the GML schema that implements `GM_Object` using the specified _version_ of GML <<OGC07-036>>.
|http://www.opengis.net/spec/geosparql/1.0/req/rdfs-entailment-extension/gml-geometry-types[`http://www.opengis.net/spec/geosparql/1.0/req/rdfs-entailment-extension/gml-geometry-types`]
|===
