= Annex A (normative) Abstract Test Suite

== A.1 Conformance Class: _Core_

*Conformance Class IRI*: `/conf/core` 

=== A.1.1 `/conf/core/sparql-protocol`

*Requirement*: `/req/core/sparql-protocol`

Implementations shall support the SPARQL Query Language for RDF <<SPARQL>>, the SPARQL Protocol for RDF <<SPARQLPROT>> and the SPARQL Query Results XML Format <<SPARQLRESX>>.

[loweralpha]
.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that the implementation accepts SPARQL queries and returns the correct results in the correct format, according to the SPARQL Query Language for RDF, the SPARQL Protocol for RDF and SPARQL Query Results XML Format W3C specifications.
.. *Reference*: <<_sparql_2>>
.. *Test Type*: Capabilities

=== A.1.2 `/conf/core/spatial-object-class`

*Requirement*: `/req/core/spatial-object-class`

Implementations shall allow the RDFS class geo:SpatialObject to be used in SPARQL graph 
patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving geo:SpatialObject return the correct result on a test dataset.
.. *Reference*: <<_class_geospatialobject>>
.. *Test Type*: Capabilities

=== A.1.3 `/conf/core/spatial-measure-class`

*Requirement*: `/req/core/spatial-measure-class`
Implementations shall allow the RDFS class geo:SpatialMeasure to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving geo:SpatialMeasure return the correct result on a test dataset.
.. *Reference*: <<_class_geospatialmeasure>>
.. *Test Type*: Capabilities

=== A.1.3 `/conf/core/feature-class`

*Requirement*: `/req/core/feature-class`
Implementations shall allow the RDFS class geo:Feature to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving geo:Feature return the correct result on a test dataset.
.. *Reference*: <<_class_geofeature>>
.. *Test Type*: Capabilities

== A.2 Conformance Class: Topology Vocabulary Extension (relation_family) 

*Conformance Class IRI*: `/conf/topology-vocab-extension`

=== A.2.1 relation_family = Simple Features
==== A.2.1.1 `/conf/topology-vocab-extension/sf-spatial-relations`
*Requirement*: `/req/topology-vocab-extension/sf-spatial-relations`
Implementations shall allow the properties `geo:sfEquals`, `geo:sfDisjoint`, `geo:sfIntersects`, `geo:sfTouches`, `geo:sfCrosses`, `geo:sfWithin`, `geo:sfContains`, `geo:sfOverlaps` to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_simple_features_relation_family_relation_familysimple_features>>
.. *Test Type*: Capabilities

=== A.2.2 relation_family = Egenhofer
==== A.2.2.1 `/conf/topology-vocab-extension/eh-spatial-relations`
*Requirement*: `/req/topology-vocab-extension/eh-spatial-relations`
Implementations shall allow the properties `geo:ehEquals`, `geo:ehDisjoint`, `geo:ehMeet`, `geo:ehOverlap`, `geo:ehCovers`, `geo:ehCoveredBy`, `geo:ehInside`, `geo:ehContains` to be used in SPARQL graph patterns. 

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_egenhofer_relation_family_relation_familyegenhofer>>
.. *Test Type*: Capabilities

=== A.2.3 relation_family = RCC8
==== A.2.3.1 `/conf/topology-vocab-extension/rcc8-spatial-relations`
*Requirement*: `/req/topology-vocab-extension/rcc8-spatial-relations`
Implementations shall allow the properties `geo:rcc8eq`, `geo:rcc8dc`, `geo:rcc8ec`, `geo:rcc8po`, `geo:rcc8tppi`, `geo:rcc8tpp`, `geo:rcc8ntpp`, `geo:rcc8ntppi` to be used in SPARQL graph patterns

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_rcc8_relation_family_relation_familyrcc8>>
.. *Test Type*: Capabilities

== A.3 Conformance Class: Geometry Extension (serialization, version) 

*Conformance Class IRI*: `/conf/geometry-extension`

=== A.3.1 Tests for all Serializations
==== A.3.1.1 `/conf/geometry-extension/geometry-class`
*Requirement*: `/req/geometry-extension/geometry-class`
Implementations shall allow the RDFS class `geo:Geometry` to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving `geo:Geometry` return the correct result on a test dataset
.. *Reference*: <<_class_geogeometry>>
.. *Test Type*: Capabilities

==== A.3.1.2 `/conf/geometry-extension/feature-properties`
*Requirement*: `/req/geometry-extension/feature-properties`
Implementations shall allow the properties `geo:hasGeometry` and `geo:hasDefaultGeometry` to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_standard_properties_for_geofeature>>
.. *Test Type*: Capabilities

==== A.3.1.3 `/conf/geometry-extension/geometry-properties`
*Requirement*: `/req/geometry-extension/geometry-properties`
Implementations shall allow the properties `geo:dimension`, `geo:coordinateDimension`, `geo:spatialDimension`, `geo:isEmpty`, `geo:isSimple`, `geo:hasSerialization` to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_standard_properties_for_geogeometry>>
.. *Test Type*: Capabilities

==== A.3.1.4 `/conf/geometry-extension/query-functions`
*Requirement*: `/req/geometry-extension/query-functions`  
Implementations shall support `geof:distance`, `geof:buffer`, `geof:convexHull`, `geof:intersection`, `geof:union`, `geof:difference`, `geof:symDifference`, `geof:envelope` and `geof:boundary` as SPARQL extension functions, consistent with the definitions of the corresponding functions (distance, buffer, convexHull, intersection, difference, symDifference, envelope and boundary respectively) in Simple Features <<ISO19125-1>>.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving each of the following functions returns the correct result for a test dataset when using the specified serialization and version: `geof:distance`, `geof:buffer`, `geof:convexHull`, `geof:intersection`, `geof:union`, `geof:difference`, `geof:symDifference`, `geof:envelope` and `geof:boundary`. 
.. *Reference*: <<_non_topological_query_functions>>
.. *Test Type*: Capabilities

==== A.3.1.5 `/conf/geometry-extension/srid-function`
*Requirement*: `/req/geometry-extension/srid-function`
Implementations shall support `geof:getSRID as a SPARQL extension function.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that a SPARQL query involving the `geof:getSRID` function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_function_geofgetsrid>>
.. *Test Type*: Capabilities

=== A.3.2 serialization = WKT

==== A.3.2.1 `/conf/geometry-extension/wkt-literal`
*Requirement*: `/req/geometry-extension/wkt-literal`
All `geo:wktLiteral` instances shall consist of an optional IRI identifying the Spatial Reference System (SRS) followed by Simple Features Well Known Text (WKT) describing a geometric value. Valid `geo:wktLiteral` instances are formed by concatenating a valid, absolute IRI as defined in <<IETF3987>>, one or more spaces (Unicode U+0020 character) as a separator, and a WKT string as defined in Simple Features <<ISO19125-1>>.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving `geo:wktLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geowktliteral>>
.. *Test Type*: Capabilities

==== A.3.2.2 `/conf/geometry-extension/wkt-literal-default-srs`
*Requirement*: `/req/geometry-extension/wkt-literal-default-srs`
The IRI <http://www.opengis.net/def/crs/OGC/1.3/CRS84> shall be assumed as the SRS for `geo:wktLiterals` that do not specify an explicit SRS IRI.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving `geo:wktLiteral` values without an explicit encoded SRS IRI return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geowktliteral>>
.. *Test Type*: Capabilities

==== A.3.2.3 `/conf/geometry-extension/wkt-axis-order`
*Requirement*: `/req/geometry-extension/wkt-axis-order`
Coordinate tuples within geo:wktLiterals shall be interpreted using the axis order defined in the SRS used.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving `geo:wktLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geowktliteral>>
.. *Test Type*: Capabilities

==== A.3.2.4 `/conf/geometry-extension/wkt-literal-empty`
*Requirement*: `/req/geometry-extension/wkt-literal-empty`
An empty RDFS Literal of type geo:wktLiteral shall be interpreted as an empty geometry.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving empty `geo:wktLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geowktliteral>>
.. *Test Type*: Capabilities

==== A.3.2.5 `/conf/geometry-extension/geometry-as-wkt-literal`
*Requirement*: `/req/geometry-extension/geometry-as-wkt-literal`
Implementations shall allow the RDF property `geo:asWKT` to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving the `geo:asWKT` property return the correct result for a test dataset.
.. *Reference*: <<_property_geoaswkt>>
.. *Test Type*: Capabilities

=== A.3.3 serialization = GML
==== A.3.3.1 `/conf/geometry-extension/gml-literal`
*Requirement*: `/req/geometry-extension/gml-literal`
All `geo:gmlLiteral` instances shall consist of a valid element from the GML schema that implements a subtype of GM_Object as defined in [OGC 07-036].

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving `geo:gmlLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geogmlliteral>>
.. *Test Type*: Capabilities

==== A.3.3.2 `/conf/geometry-extension/gml-literal-empty`
*Requirement*: `/req/geometry-extension/gml-literal-empty`
An empty `geo:gmlLiteral` shall be interpreted as an empty geometry.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving empty `geo:gmlLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geogmlliteral>>
.. *Test Type*: Capabilities

==== A.3.3.3 `/conf/geometry-extension/gml-profile`
*Requirement*: `/req/geometry-extension/gml-profile`
Implementations shall document supported GML profiles.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Examine the implementation’s documentation to verify that the supported GML profiles are documented.
.. *Reference*: <<_rdfs_datatype_geogmlliteral>>
.. *Test Type*: Documentation

==== A.3.3.4 `/conf/geometry-extension/geometry-as-gml-literal`
*Requirement*: `/req/geometry-extension/geometry-as-gml-literal` 
Implementations shall allow the RDF property geo:asGML to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving the `geo:asGML` property return the correct result for a test dataset.
.. *Reference*: <<_property_geoasgml>>
.. *Test Type*: Capabilities

=== A.3.4 serialization = GEOJSON
==== A.3.4.1 `/req/geometry-extension/geojson-literal`
*Requirement*: `/req/geometry-extension/geojson-literal`
All `geo:geoJsonLiteral` instances shall consist of valid JSON that conforms to the GeoJSON specification <<GEOJSON>>

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving `geo:geoJSONLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_property_geoasgml>>
.. *Test Type*: Capabilities

==== A.3.4.2 `/req/geometry-extension/geojson-literal-srs`
*Requirement*: `/req/geometry-extension/geojson-literal-default-srs`
The IRI <http://www.opengis.net/def/crs/OGC/1.3/CRS84> shall be assumed as the SRS for `geo:geoJSONLiteral` instances that do not specify an explicit SRS IRI.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving `geo:geoJSONLiteral` values without an explicit encoded SRS IRI return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geogeojsonliteral>>
.. *Test Type*: Capabilities

==== A.3.4.3 `/req/geometry-extension/geojson-literal-empty`
*Requirement*: `/req/geometry-extension/geojson-literal-empty`
An empty `geo:geoJSONLiteral` shall be interpreted as an empty geometry.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving empty `geo:geoJSONLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geogeojsonliteral>>
.. *Test Type*: Capabilities

==== A.3.4.4 `/req/geometry-extension/geometry-as-geojson-literal`
*Requirement*: `/req/geometry-extension/geometry-as-geojson-literal` 
Implementations shall allow the RDF property `geo:asGeoJSON` to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving the `geo:asGeoJSON` property return the correct result for a test dataset.
.. *Reference*: <<_property_geoasgeojson>>
.. *Test Type*: Capabilities

=== A.3.5 serialization = KML
==== A.3.5.1 `/req/geometry-extension/kml-literal`
*Requirement*: `/req/geometry-extension/kml-literal`
All `geo:kmlLiteral` instances shall consist of a valid element from the KML schema that implements a `kml:AbstractObjectGroup` as defined in <<OGCKML>>.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving `geo:kmlLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geomklliteral>>
.. *Test Type*: Capabilities

==== A.3.5.2 `/req/geometry-extension/kml-literal-srs`
*Requirement*: `/req/geometry-extension/wkt-literal-default-srs`
The IRI <http://www.opengis.net/def/crs/OGC/1.3/CRS84> shall be assumed as the SRS for `geo:kmlLiterals` that do not specify an explicit SRS IRI.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving geo:wktLiteral values without an explicit encoded SRS IRI return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geomklliteral>>
.. *Test Type*: Capabilities

==== A.3.5.3 `/req/geometry-extension/kml-literal-empty`
*Requirement*: `/req/geometry-extension/kml-literal-empty`
An empty `geo:kmlLiteral` shall be interpreted as an empty geometry.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving empty `geo:kmlLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geomklliteral>>
.. *Test Type*: Capabilities

==== A.3.5.4 `/req/geometry-extension/geometry-as-kml-literal`
*Requirement*: `/req/geometry-extension/geometry-as-kml-literal` 
Implementations shall allow the RDF property `geo:asKML` to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving the `geo:asKML` property return the correct result for a test dataset.
.. *Reference*: <<_property_geoaskml>>
.. *Test Type*: Capabilities

=== A.3.6 serialization = DGGS
==== A.3.6.1 `/req/geometry-extension/dggswkt-literal`
*Requirement*: `/req/geometry-extension/dggswkt-literal`
All RDFS Literals of type `geo:dggsWktLiteral` shall consist of a DGGS identifier, an IRI enclosed in '<' & '>', followed by one or more spaces (Unicode U+0020 character) and a DGGS geometry serialization formulated according to the identified DGGS.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving `geo:dggsWktLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_dggs_serialization_serializationdggs>>
.. *Test Type*: Capabilities

==== A.3.6.2 `/req/geometry-extension/dggswkt-literal-empty`
*Requirement*: `/req/geometry-extension/dggswkt-literal-empty`
An empty `geo:dggsWktLiteral` shall be interpreted as an empty geometry.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving empty `geo:dggsWktLiteral` values return the correct result for a test dataset.
.. *Reference*: <<_dggs_serialization_serializationdggs>>
.. *Test Type*: Capabilities

==== A.3.6.3 `/req/geometry-extension/geometry-as-dggswkt-literal`
*Requirement*: `/req/geometry-extension/geometry-as-dggswkt-literal` 
Implementations shall allow the RDF property `geo:asDggsWkt` to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving the `geo:asDggsWkt` property return the correct result for a test dataset.
.. *Reference*: <<_property_geoasdggswkt>>
.. *Test Type*: Capabilities

== A.4 Conformance Class: Geometry Topology Extension (relation_family, serialization, version)

*Conformance Class IRI*: `/conf/geometry-topology-extension`

=== A.4.1 Tests for all relation families
==== A.4.1.1 `/conf/geometry-topology-extension/relate-query-function`
*Requirement*: `/req/geometry-topology-extension/relate-query-function`
Implementations shall support `geof:relate` as a SPARQL extension function, consistent with the relate operator defined in Simple Features <<ISO19125-1>>.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving the `geof:relate function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_common_query_functions>>
.. *Test Type*: Capabilities

=== A.4.2 relation_family = Simple Features
==== A.4.2.1 `/conf/geometry-topology-extension/sf-query-functions`
*Requirement*: `/req/geometry-topology-extension/sf-query-functions`
Implementations shall support `geof:sfEquals`, `geof:sfDisjoint`, `geof:sfIntersects`, `geof:sfTouches`, `geof:sfCrosses`, `geof:sfWithin`, `geof:sfContains`, `geof:sfOverlaps` as SPARQL extension functions, consistent with their corresponding DE-9IM intersection patterns, as defined by Simple Features <<ISO19125-1>>.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving each of the following functions returns the correct result for a test dataset when using the specified serialization and version: `geof:sfEquals`, `geof:sfDisjoint`, `geof:sfIntersects`, `geof:sfTouches`, `geof:sfCrosses`, `geof:sfWithin`, `geof:sfContains`, `geof:sfOverlaps`.
.. *Reference*: <<_requirements_for_simple_features_relation_family_relation_familysimple_features>>
.. *Test Type*: Capabilities

=== A.4.3 relation_family = Egenhofer
==== A.4.3.1 `/conf/geometry-topology-extension/eh-query-functions`
*Requirement*: `/req/geometry-topology-extension/eh-query-functions`
Implementations shall support `geof:ehEquals`, `geof:ehDisjoint`, `geof:ehMeet`, `geof:ehOverlap`, `geof:ehCovers`, `geof:ehCoveredBy`, `geof:ehInside`, `geof:ehContains` as SPARQL extension functions, consistent with their corresponding DE-9IM intersection patterns, as defined by Simple Features [ISO 19125- 1].

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving each of the following functions returns the correct result for a test dataset when using the specified serialization and version: `geof:ehEquals`, `geof:ehDisjoint`, `geof:ehMeet`, `geof:ehOverlap`, `geof:ehCovers`, `geof:ehCoveredBy`, `geof:ehInside`, `geof:ehContains`.
.. *Reference*: <<_requirements_for_egenhofer_relation_family_relation_familyegenhofer>>
.. *Test Type*: Capabilities

=== A.4.4 relation_family = RCC8
==== A.4.4.1 `/conf/geometry-topology-extension/rcc8-query-functions`
*Requirement*: `/req/geometry-topology-extension/rcc8-query-functions
Implementations shall support `geof:rcc8eq`, `geof:rcc8dc`, `geof:rcc8ec`, `geof:rcc8po`, `geof:rcc8tppi`, `geof:rcc8tpp`, `geof:rcc8ntpp`, `geof:rcc8ntppi` as SPARQL extension functions, consistent with their corresponding DE-9IM intersection patterns, as defined by Simple Features <<ISO19125-1>>.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving each of the following functions returns the correct result for a test dataset when using the specified serialization and version: `geof:rcc8eq`, `geof:rcc8dc`, `geof:rcc8ec`, `geof:rcc8po`, `geof:rcc8tppi`, `geof:rcc8tpp`, `geof:rcc8ntpp`, `geof:rcc8ntppi`.
.. *Reference*: <<_requirements_for_rcc8_relation_family_relation_familyrcc8>>
.. *Test Type*: Capabilities

== A.5 Conformance Class: RDFS Entailment Extension (relation_family, serialization, version)

*Conformance Class IRI*: `/conf/rdfs-entailment-extension`

=== A.5.1 Tests for all implementations
==== A.5.1.1 `/conf/rdfsentailmentextension/bgp-rdfs-ent`
*Requirement*: `/req/rdfs-entailment-extension/bgp-rdfs-ent`
Basic graph pattern matching shall use the semantics defined by the RDFS Entailment Regime <<SPARQLENT>>.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving entailed RDF triples returns the correct result for a test dataset using the specified serialization, version and relation_family.
.. *Reference*: <<_common_requirements>>
.. *Test Type*: Capabilities

=== A.5.2 serialization=WKT
==== A.5.2.1 `/conf/rdfs-entailment-extension/wkt-geometry-types`
*Requirement*: `/req/rdfs-entailment-extension/wkt-geometry-types`
Implementations shall support graph patterns involving terms from an RDFS/OWL class hierarchy of geometry types consistent with the one in the specified version of Simple Features <<ISO19125-1>>.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving WKT Geometry types returns the correct result for a test dataset using the specified version of Simple Features. 
.. *Reference*: <<_geometry_class_hierarchy>>
.. *Test Type*: Capabilities

=== A.5.3 serialization=GML
==== A.5.3.1 `/conf/rdfs-entailment-extension/gml-geometry-types`
*Requirement*: `/req/rdfs-entailment-extension/gml-geometry-types` 
Implementations shall support graph patterns involving terms from an RDFS/OWL class hierarchy of geometry types consistent with the GML schema that implements GM_Object using the specified version of GML <<OGC07-036>>.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving GML Geometry types returns the correct result for a test dataset using the specified version of GML.
.. *Reference*: <<_geometry_class_hierarchy_2>>
.. *Test Type*: Capabilities

== A.6 Conformance Class: Query Rewrite Extension (relation_family, serialization, version)

*Conformance Class IRI*: `/conf/query-rewrite-extension`

=== A.6.1 relation_family = Simple Features
==== A.6.1.1 `/conf/query-rewrite-extension/sf-query-rewrite`
*Requirement*: `/req/query-rewrite-extension/sf-query-rewrite`
Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime <<SPARQLENT>> for the RIF rules <<RIFCORE>> `geor:sfEquals`, `geor:sfDisjoint`, `geor:sfIntersects`, `geor:sfTouches`, `geor:sfCrosses`, `geor:sfWithin`, `geor:sfContains`, `geor:sfOverlaps`.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that queries involving the following query transformation rules return the correct result for a test dataset when using the specified serialization and version: `geor:sfEquals`, `geor:sfDisjoint`, `geor:sfIntersects`, `geor:sfTouches`, `geor:sfCrosses`, `geor:sfWithin`, `geor:sfContains` and `geor:sfOverlaps`.
.. *Reference*: <<_requirements_for_simple_features_relation_family_relation_familysimple_features_2>>
.. *Test Type*: Capabilities

=== A.6.2 relation_family = Egenhofer
==== A.6.2.1 `/conf/query-rewrite-extension/eh-query-rewrite`
*Requirement*: `/req/query-rewrite-extension/eh-query-rewrite`
Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime <<SPARQLENT>> for the RIF rules <<RIFCORE>> `geor:ehEquals`, `geor:ehDisjoint`, `geor:ehMeet`, `geor:ehOverlap`, `geor:ehCovers`, `geor:ehCoveredBy`, `geor:ehInside`, `geor:ehContains`.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that queries involving the following query transformation rules return the correct result for a test dataset when using the specified serialization and version: `geor:ehEquals`, `geor:ehDisjoint`, `geor:ehMeet`, `geor:ehOverlap`, `geor:ehCovers`, `geor:ehCoveredBy`, `geor:ehInside`, `geor:ehContains`.
.. *Reference*: <<_requirements_for_egenhofer_relation_family_relation_familyegenhofer_2>>
.. *Test Type*: Capabilities

=== A.6.3 relation_family = RCC8
==== A.6.3.1 `/conf/query-rewrite-extension/rcc8-query-rewrite`
*Requirement*: `/req/query-rewrite-extension/rcc8-query-rewrite`
Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime <<SPARQLENT>> for the RIF rules <<RIFCORE>> `geor:rcc8eq`, `geor:rcc8dc`, `geor:rcc8ec`, `geor:rcc8po`, `geor:rcc8tppi`, `geor:rcc8tpp`, `geor:rcc8ntpp`, `geor:rcc8ntppi`.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: Verify that queries involving the following query transformation rules return the correct result for a test dataset when using the specified serialization and version: `geor:rcc8eq`, `geor:rcc8dc`, `geor:rcc8ec`, `geor:rcc8po`, `geor:rcc8tppi`, `geor:rcc8tpp`, `geor:rcc8ntpp`, `geor:rcc8ntppi`.
.. *Reference*: <<_requirements_for_rcc8_relation_family_relation_familyrcc8_2>>
.. *Test Type*: Capabilities
