= Annex A - Abstract Test Suite (normative)

== A.0 Overview

This Annex lists tests for the Conformance Classes defined in the main body sections of this Specification with links to their Requirements and test purpose method and type.
Conformance classes may be used to signify the compatibility of a given implementation to parts of the GeoSPARQL standard. 
They may be stated as part of a SPARQL 1.1 Service Description <<SPARQLSERVDESC>> .

== A.1 Conformance Class: Core

*Conformance Class IRI*: `/conf/core` 

=== A.1.1 SPARQL

==== A.1.1.1 `/conf/core/sparql-protocol`

*Requirement*: `/req/core/sparql-protocol`

Implementations shall support the SPARQL Query Language for RDF <<SPARQL>>, the SPARQL Protocol for RDF <<SPARQLPROT>> and the SPARQL Query Results XML Format <<SPARQLRESX>>.

[loweralpha]
.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that the implementation accepts SPARQL queries and returns the correct results in the correct format, according to the SPARQL Query Language for RDF, the SPARQL Protocol for RDF and SPARQL Query Results XML Format W3C specifications.
.. *Reference*: <<_sparql_2>>
.. *Test Type*: Capabilities

=== A.1.2 RDF Classes & Properties

==== A.1.2.1 `/conf/core/spatial-object-class`

*Requirement*: `/req/core/spatial-object-class`

Implementations shall allow the RDFS class <<Class: geo:SpatialObject, `geo:SpatialObject`>> to be used in SPARQL graph 
patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving <<Class: geo:SpatialObject, `geo:SpatialObject`>> return the correct result on a test dataset.
.. *Reference*: <<_class_geospatialobject>>
.. *Test Type*: Capabilities

==== A.1.2.2 `/conf/core/feature-class`

*Requirement*: `/req/core/feature-class`
Implementations shall allow the RDFS class <<Class: geo:Feature, `geo:Feature`>> to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving <<Class: geo:Feature, `geo:Feature`>> return the correct result on a test dataset.
.. *Reference*: <<_class_geofeature>>
.. *Test Type*: Capabilities

==== A.1.2.3 `/conf/core/spatial-object-collection-class`

*Requirement*: `/req/core/spatial-object-collection-class`

Implementations shall allow the RDFS class <<Class: geo:SpatialObjectCollection, `geo:SpatialObjectCollection`>> to be used in SPARQL graph 
patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving <<Class: geo:SpatialObjectCollection, `geo:SpatialObjectCollection`>> return the correct result on a test dataset.
.. *Reference*: <<_class_geospatialobjectcollection>>
.. *Test Type*: Capabilities

==== A.1.2.4 `/conf/core/feature-collection-class`

*Requirement*: `/req/core/feature-collection-class`

Implementations shall allow the RDFS class <<Class: geo:FeatureCollection, `geo:FeatureCollection`>> to be used in SPARQL graph 
patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving <<Class: geo:FeatureCollection, `geo:FeatureCollection`>> return the correct result on a test dataset.
.. *Reference*: <<_class_geofeaturecollection>>
.. *Test Type*: Capabilities

==== A.1.2.5 `/conf/core/spatial-object-properties`

Implementations shall allow the properties 
<<Property: geo:hasSize, `geo:hasSize`>>,
<<Property: geo:hasMetricSize, `geo:hasMetricSize`>>,
<<Property: geo:hasLength, `geo:hasLength`>>, 
<<Property: geo:hasMetricLength, `geo:hasMetricLength`>>,
<<Property: geo:hasPerimeterLength, `geo:hasPerimeterLength`>>, 
<<Property: geo:hasMetricPerimeterLength, `geo:hasMetricPerimeterLength`>>, 
<<Property: geo:hasArea, `geo:hasArea`>>,
<<Property: geo:hasMetricArea, `geo:hasMetricArea`>>,
<<Property: geo:hasVolume, `geo:hasVolume`>> and
<<Property: geo:hasMetricVolume, `geo:hasMetricVolume`>>.
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_standard_properties_for_geospatialobject>>
.. *Test Type*: Capabilities

== A.2 Conformance Class: Topology Vocabulary Extension

*Conformance Class IRI*: `/conf/topology-vocab-extension`

=== A.2.1 Simple Features Relation Family
==== A.2.1.1 `/conf/topology-vocab-extension/sf-spatial-relations`
*Requirement*: `/req/topology-vocab-extension/sf-spatial-relations`

Implementations shall allow the properties 
<<Property: geo:sfEquals, `geo:sfEquals`>>, 
<<Property: geo:sfDisjoint, `geo:sfDisjoint`>>, 
<<Property: geo:sfIntersects, `geo:sfIntersects`>>, 
<<Property: geo:sfTouches, `geo:sfTouches`>>, 
<<Property: geo:sfCrosses, `geo:sfCrosses`>>, 
<<Property: geo:sfWithin, `geo:sfWithin`>>, 
<<Property: geo:sfContains, `geo:sfContains`>> and 
<<Property: geo:sfOverlaps, `geo:sfOverlaps`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<Simple Features Relation Family>>
.. *Test Type*: Capabilities

=== A.2.2 Egenhofer Relation Family
==== A.2.2.1 `/conf/topology-vocab-extension/eh-spatial-relations`
*Requirement*: `/req/topology-vocab-extension/eh-spatial-relations`

Implementations shall allow the properties 
<<Property: geo:ehEquals, `geo:ehEquals`>>, 
<<Property: geo:ehDisjoint, `geo:ehDisjoint`>>, 
<<Property: geo:ehMeet, `geo:ehMeet`>>, 
<<Property: geo:ehOverlap, `geo:ehOverlap`>>, 
<<Property: geo:ehCovers, `geo:ehCovers`>>, 
<<Property: geo:ehCoveredBy, `geo:ehCoveredBy`>>, 
<<Property: geo:ehInside, `geo:ehInside`>> and
<<Property: geo:ehContains, `geo:ehContains`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<Egenhofer Relation Family>>
.. *Test Type*: Capabilities

=== A.2.3 RCC8 Relation Family
==== A.2.3.1 `/conf/topology-vocab-extension/rcc8-spatial-relations`
*Requirement*: `/req/topology-vocab-extension/rcc8-spatial-relations`

Implementations shall allow the properties 
<<Property: geo:rcc8eq, `geo:rcc8eq`>>, 
<<Property: geo:rcc8dc, `geo:rcc8dc`>>, 
<<Property: geo:rcc8ec, `geo:rcc8ec`>>, 
<<Property: geo:rcc8po, `geo:rcc8po`>>, 
<<Property: geo:rcc8tppi, `geo:rcc8tppi`>>, 
<<Property: geo:rcc8tpp, `geo:rcc8tpp`>>, 
<<Property: geo:rcc8ntpp, `geo:rcc8ntpp`>>, 
<<Property: geo:rcc8ntppi, `geo:rcc8ntppi`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<RCC8 Relation Family>>
.. *Test Type*: Capabilities

== A.3 Conformance Class: Geometry Extension

This Conformance Class applies to non-DGGS geometries. See <<A.3.DGGS Conformance Class: Geometry Extension - DGGS>> for DGGS geometries.

*Conformance Class IRI*: `/conf/geometry-extension`

=== A.3.1 Tests for all Serializations except DGGS
==== A.3.1.1 `/conf/geometry-extension/geometry-class`
*Requirement*: `/req/geometry-extension/geometry-class`

Implementations shall allow the RDFS class 
<<Class: geo:Geometry, `geo:Geometry`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving <<Class: geo:Geometry, `geo:Geometry`>> return the correct result on a test dataset
.. *Reference*: <<_class_geogeometry>>
.. *Test Type*: Capabilities

==== A.3.1.2 `/conf/geometry-extension/geometry-collection-class`
*Requirement*: `/req/geometry-extension/geometry-collection-class`

Implementations shall allow the RDFS class 
<<Class: geo:GeometryCollection, Geometry Collection>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving <<Class: geo:GeometryCollection, Geometry Collection>> return the correct result on a test dataset
.. *Reference*: <<_class_geogeometrycollection>>
.. *Test Type*: Capabilities

==== A.3.1.3 `/conf/geometry-extension/feature-properties`
*Requirement*: `/req/geometry-extension/feature-properties`

Implementations shall allow the properties 
<<Property: geo:hasGeometry, `geo:hasGeometry`>>, 
<<Property: geo:hasDefaultGeometry, `geo:hasDefaultGeometry`>>, 
<<Property: geo:hasLength, `geo:hasLength`>>, 
<<Property: geo:hasArea, `geo:hasArea`>>, 
<<Property: geo:hasVolume, `geo:hasVolume`>> 
<<Property: geo:hasCentroid, `geo:hasCentroid`>>, 
<<Property: geo:hasBoundingBox, `geo:hasBoundingBox`>> and 
<<Property: geo:hasSpatialResolution, `geo:hasSpatialResolution`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_standard_properties_for_geofeature>>
.. *Test Type*: Capabilities

==== A.3.1.4 `/conf/geometry-extension/geometry-properties`
*Requirement*: `/req/geometry-extension/geometry-properties`

Implementations shall allow the properties 
<<Property: geo:dimension, `geo:dimension`>>, 
<<Property: geo:coordinateDimension, `geo:coordinateDimension`>>, 
<<Property: geo:spatialDimension, `geo:spatialDimension`>>, 
<<Property: geo:isEmpty, `geo:isEmpty`>>, 
<<Property: geo:isSimple, `geo:isSimple`>> and 
<<Property: geo:hasSerialization, `geo:hasSerialization`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_standard_properties_for_geogeometry>>
.. *Test Type*: Capabilities

==== A.3.1.5 `/conf/geometry-extension/query-functions`
*Requirement*: `/req/geometry-extension/query-functions`  

Implementations shall support the functions 
<<Function: geof:distance, `geof:distance`>>, 
<<Function: geof:buffer, `geof:buffer`>>, 
<<Function: geof:intersection, `geof:intersection`>>, 
<<Function: geof:union, `geof:union`>>, 
<<Function: geof:isEmpty, `geof:isEmpty`>>, 
<<Function: geof:isSimple, `geof:isSimple`>>, 
<<Function: geof:area, `geof:area`>>, 
<<Function: geof:length, `geof:length`>>,
<<Function: geof:numGeometries, `geof:numGeometries`>>,
<<Function: geof:geometryN, `geof:geometryN`>>, 
<<Function: geof:transform, `geof:transform`>>,
<<Function: geof:dimension, `geof:dimension`>>, 
<<Function: geof:difference, `geof:difference`>>, 
<<Function: geof:symDifference, `geof:symDifference`>>, 
<<Function: geof:envelope, `geof:envelope`>> and 
<<Function: geof:boundary, `geof:boundary`>> 
as SPARQL extension functions, consistent with the definitions of their corresponding functions in Simple Features <<OGCSFACA>> <<ISO19125-1>> (`distance`, `buffer`, `intersection`, `union`, `isEmpty`, `isSimple`, `area`, `length`, `numGeometries`, `geometryN`, `transform`, `dimension`, `difference`, `symDifference`, `envelope` and `boundary` respectively) and other attached definitions and also 
http://www.opengis.net/def/function/geosparql/minX[`geof:maxX`],
http://www.opengis.net/def/function/geosparql/maxY[`geof:maxY`], 
http://www.opengis.net/def/function/geosparql/maxZ[`geof:maxZ`],  
http://www.opengis.net/def/function/geosparql/minX[`geof:minX`], 
http://www.opengis.net/def/function/geosparql/minY[`geof:minY`] and
http://www.opengis.net/def/function/geosparql/minZ[`geof:minZ`]
SPARQL extension functions.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving each of the following functions returns the correct result for a test dataset when using the specified serialization and version: 
<<Function: geof:distance, `geof:distance`>>, 
<<Function: geof:buffer, `geof:buffer`>>, 
<<Function: geof:intersection, `geof:intersection`>>, 
<<Function: geof:union, `geof:union`>>, 
<<Function: geof:isEmpty, `geof:isEmpty`>>, 
<<Function: geof:isSimple, `geof:isSimple`>>, 
<<Function: geof:area, `geof:area`>>, 
<<Function: geof:length, `geof:length`>>,
<<Function: geof:numGeometries, `geof:numGeometries`>>,
<<Function: geof:geometryN, `geof:geometryN`>>, 
<<Function: geof:transform, `geof:transform`>>,
<<Function: geof:dimension, `geof:dimension`>>, 
<<Function: geof:difference, `geof:difference`>>, 
<<Function: geof:symDifference, `geof:symDifference`>>, 
<<Function: geof:envelope, `geof:envelope`>> and 
<<Function: geof:boundary, `geof:boundary`>>. 
.. *Reference*: <<_non_topological_query_functions>>
.. *Test Type*: Capabilities

==== A.3.1.6 `/conf/geometry-extension/srid-function`
*Requirement*: `/req/geometry-extension/srid-function`

Implementations shall support 
<<Function: geof:getSRID, get SRID>> 
as a SPARQL extension function.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a SPARQL query involving the <<Function: geof:getSRID, get SRID>> function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_function_geofgetsrid>>
.. *Test Type*: Capabilities

==== A.3.1.7 `/conf/geometry-extension/sa-functions`
*Requirement*: `/req/geometry-extension/sa-functions`

Implementations shall support 
<<Function: geof:aggBoundingBox,`geof:aggBoundingBox`>>, 
<<Function: geof:aggBoundingCircle,`geof:aggBoundingCircle`>>, 
<<Function: geof:aggCentroid,`geof:aggCentroid`>>, 
<<Function: geof:aggConcaveHull,`geof:aggConcaveHull`>>, 
<<Function: geof:aggConvexHull,`geof:aggConvexHull`>> and 
<<Function: geof:aggUnion,`geof:aggUnion`>>
as a SPARQL extension functions.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these functions return the correct result for a test dataset.
.. *Reference*: <<_spatial_aggregate_functions>>
.. *Test Type*: Capabilities

=== A.3.2 WKT Serialization

==== A.3.2.1 `/conf/geometry-extension/wkt-literal`
*Requirement*: `/req/geometry-extension/wkt-literal`

All RDFS Literals of type <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> shall consist of an optional IRI identifying the coordinate reference system and a required Well Known Text (WKT) description of a geometric value. Valid <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> instances are formed by either a WKT string as defined in <<ISO13249>> or by concatenating a valid absolute IRI, as defined in <<IETF3987>>, enclose in angled brackets (`<` & `>`) followed by a single space (Unicode U+0020 character) as a separator, and a WKT string as defined in <<ISO13249>>.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving  <<RDFS Datatype: geo:wktLiteral, WKT Literal>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geowktliteral>>
.. *Test Type*: Capabilities

==== A.3.2.2 `/conf/geometry-extension/wkt-literal-default-srs`
*Requirement*: `/req/geometry-extension/wkt-literal-default-srs`

The IRI http://www.opengis.net/def/crs/OGC/1.3/CRS84[`+<http://www.opengis.net/def/crs/OGC/1.3/CRS84>+`] shall be assumed as the spatial reference system for <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> instances that do not specify an explicit spatial reference system IRI.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving  <<RDFS Datatype: geo:wktLiteral, WKT Literal>> values without an explicit encoded SRS IRI return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geowktliteral>>
.. *Test Type*: Capabilities

==== A.3.2.3 `/conf/geometry-extension/wkt-axis-order`
*Requirement*: `/req/geometry-extension/wkt-axis-order`

Coordinate tuples within <<RDFS Datatype: geo:wktLiteral, WKT Literal>> instances shall be interpreted using the axis order defined in the SRS used.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving  <<RDFS Datatype: geo:wktLiteral, WKT Literal>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geowktliteral>>
.. *Test Type*: Capabilities

==== A.3.2.4 `/conf/geometry-extension/wkt-literal-empty`
*Requirement*: `/req/geometry-extension/wkt-literal-empty`

An empty RDFS Literal of type <<RDFS Datatype: geo:wktLiteral, WKT Literal>> shall be interpreted as an empty geometry.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:wktLiteral, WKT Literal>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geowktliteral>>
.. *Test Type*: Capabilities

==== A.3.2.5 `/conf/geometry-extension/geometry-as-wkt-literal`
*Requirement*: `/req/geometry-extension/geometry-as-wkt-literal`

Implementations shall allow the RDF property <<Property: geo:asWKT, `geo:asWKT`>> to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving the <<Property: geo:asWKT, `geo:asWKT`>> property return the correct result for a test dataset.
.. *Reference*: <<_property_geoaswkt>>
.. *Test Type*: Capabilities

==== A.3.2.6 `/req/geometry-extension/asWKT-function`
*Requirement*: `/req/geometry-extension/asWKT-function` 

Implementations shall support <<Function: geof:asWKT, `geof:asWKT`>>, as a SPARQL extension function

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asWKT, `geof:asWKT`>> function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_function_geofaswkt>>
.. *Test Type*: Capabilities

=== A.3.3 GML Serialization
==== A.3.3.1 `/conf/geometry-extension/gml-literal`
*Requirement*: `/req/geometry-extension/gml-literal`

All <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> instances shall consist of a valid element from the GML schema that implements a subtype of GM_Object as defined in [OGC 07-036].

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geogmlliteral>>
.. *Test Type*: Capabilities

==== A.3.3.2 `/conf/geometry-extension/gml-literal-empty`
*Requirement*: `/req/geometry-extension/gml-literal-empty`

An empty <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> shall be interpreted as an empty geometry.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geogmlliteral>>
.. *Test Type*: Capabilities

==== A.3.3.3 `/conf/geometry-extension/gml-profile`
*Requirement*: `/req/geometry-extension/gml-profile`

Implementations shall document supported GML profiles.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Examine the implementation’s documentation to verify that the supported GML profiles are documented.
.. *Reference*: <<_rdfs_datatype_geogmlliteral>>
.. *Test Type*: Documentation

==== A.3.3.4 `/conf/geometry-extension/geometry-as-gml-literal`
*Requirement*: `/req/geometry-extension/geometry-as-gml-literal` 

Implementations shall allow the RDF property <<Property: geo:asWKT, `geo:asGML`>> to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving the <<Property: geo:asWKT, `geo:asGML`>> property return the correct result for a test dataset.
.. *Reference*: <<_property_geoasgml>>
.. *Test Type*: Capabilities

==== A.3.3.5 `/req/geometry-extension/asGML-function`
*Requirement*: `/req/geometry-extension/asGML-function` 

Implementations shall support <<Function: geof:asGML, `geof:asGML`>>, as a SPARQL extension function

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asGML, `geof:asGML`>> function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_function_geofasgml>>
.. *Test Type*: Capabilities

=== A.3.4 GeoJSON Serialization
==== A.3.4.1 `/req/geometry-extension/geojson-literal`
*Requirement*: `/req/geometry-extension/geojson-literal`

All <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> instances shall consist of valid JSON that conforms to the GeoJSON specification <<GEOJSON>>

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geogeojsonliteral>>
.. *Test Type*: Capabilities

==== A.3.4.2 `/req/geometry-extension/geojson-literal-srs`
*Requirement*: `/req/geometry-extension/geojson-literal-default-srs`

The IRI http://www.opengis.net/def/crs/OGC/1.3/CRS84[<http://www.opengis.net/def/crs/OGC/1.3/CRS84>] shall be assumed as the SRS for <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> instances that do not specify an explicit SRS IRI.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> values without an explicit encoded SRS IRI return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geogeojsonliteral>>
.. *Test Type*: Capabilities

==== A.3.4.3 `/req/geometry-extension/geojson-literal-empty`
*Requirement*: `/req/geometry-extension/geojson-literal-empty`

An empty <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> shall be interpreted as an empty geometry.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geogeojsonliteral>>
.. *Test Type*: Capabilities

==== A.3.4.4 `/req/geometry-extension/geometry-as-geojson-literal`
*Requirement*: `/req/geometry-extension/geometry-as-geojson-literal` 

Implementations shall allow the RDF property <<Property: geo:asGeoJSON, `geo:asGeoJSON`>> to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving the <<Property: geo:asGeoJSON, `geo:asGeoJSON`>> property return the correct result for a test dataset.
.. *Reference*: <<_property_geoasgeojson>>
.. *Test Type*: Capabilities

==== A.3.4.5 `/req/geometry-extension/asGeoJSON-function`
*Requirement*: `/req/geometry-extension/asGeoJSON-function` 

Implementations shall support <<Function: geof:asGeoJSON, `geof:asGeoJSON`>>, as a SPARQL extension function

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asGeoJSON, `geof:asGeoJSON`>> function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_function_geofasgeojson>>
.. *Test Type*: Capabilities

=== A.3.5 KML Serialization
==== A.3.5.1 `/req/geometry-extension/kml-literal`
*Requirement*: `/req/geometry-extension/kml-literal`

All <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> instances shall consist of a valid element from the KML schema that implements a `kml:AbstractObjectGroup` as defined in <<OGCKML>>.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geokmlliteral>>
.. *Test Type*: Capabilities

==== A.3.5.2 `/req/geometry-extension/kml-literal-srs`
*Requirement*: `/req/geometry-extension/kml-literal-default-srs`

The IRI http://www.opengis.net/def/crs/OGC/1.3/CRS84[<http://www.opengis.net/def/crs/OGC/1.3/CRS84>] shall be assumed as the SRS for <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> instances that do not specify an explicit SRS IRI.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>>  values without an explicit encoded SRS IRI return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geokmlliteral>>
.. *Test Type*: Capabilities

==== A.3.5.3 `/req/geometry-extension/kml-literal-empty`
*Requirement*: `/req/geometry-extension/kml-literal-empty`

An empty <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> shall be interpreted as an empty geometry.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geokmlliteral>>
.. *Test Type*: Capabilities

==== A.3.5.4 `/req/geometry-extension/geometry-as-kml-literal`
*Requirement*: `/req/geometry-extension/geometry-as-kml-literal` 

Implementations shall allow the RDF property <<Property: geo:asKML, `geo:asKML`>> to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving the <<Property: geo:asKML, `geo:asKML`>>  property return the correct result for a test dataset.
.. *Reference*: <<_property_geoaskml>>
.. *Test Type*: Capabilities

==== A.3.5.5 `/req/geometry-extension/asKML-function`
*Requirement*: `/req/geometry-extension/asKML-function` 

Implementations shall support <<Function: geof:asKML, `geof:asKML`>>, as a SPARQL extension function

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asKML, `geof:asKML`>> function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_function_geofaskml>>
.. *Test Type*: Capabilities

=== A.3.6 DGGS Serialization
==== A.3.6.1 `/req/geometry-extension/dggs-literal`
*Requirement*: `/req/geometry-extension/dggs-literal`

All RDFS Literals of type <<RDFS Datatype: geo:dggsLiteral, `geo:dggsLiteral`>> shall consist of an IRI identifying the specific DGGS and a representation of the DGGS geometry data. The IRI shall be enclosed in angled brackets (`<` & `>`) followed by whitespace as a separator, and then the DGGS geometry data, formulated according to the identified DGGS.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:dggsLiteral, `geo:dggsLiteral`>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geodggsliteral>>
.. *Test Type*: Capabilities

==== A.3.6.2 `/req/geometry-extension/dggs-literal-empty`
*Requirement*: `/req/geometry-extension/dggs-literal-empty`

An empty RDFS Literal of type <<RDFS Datatype: geo:dggsLiteral, `geo:dggsLiteral`>>, shall be interpreted as an empty `geo:Geometry`.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:dggsLiteral, `geo:dggsLiteral`>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geodggsliteral>>
.. *Test Type*: Capabilities

==== A.3.6.3 `/req/geometry-extension/geometry-as-dggs-literal`
*Requirement*: `/req/geometry-extension/geometry-as-dggs-literal` 

Implementations shall allow the RDF property <<Property: geo:asDGGS, `geo:asDGGS`>> to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving the <<Property: geo:asDGGS, `geo:asDGGS`>> property return the correct result for a test dataset.
.. *Reference*: <<_property_geoasdggs>>
.. *Test Type*: Capabilities

==== A.3.6.4 `/req/geometry-extension/asDGGS-function`
*Requirement*: `/req/geometry-extension/asDGGS-function` 

Implementations shall support <<Function: geof:asDGGS, `geof:asDGGS`>>, as a SPARQL extension function.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asDGGS, `geof:asDGGS`>> function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_function_geofasdggs>>
.. *Test Type*: Capabilities


== A.3.DGGS Conformance Class: Geometry Extension - DGGS

This conformance Class applies only to DGGS geometries. See <<A.3 Conformance Class: Geometry Extension>> for other geometries.

*Conformance Class IRI*: `/conf/geometry-extension`

=== A.3.DGGS.1 Tests for DGGS Serializations
==== A.3.DGGS.1.1 `/conf/geometry-extension/geometry-class`
*Requirement*: `/req/geometry-extension/geometry-class`

Implementations shall allow the RDFS class 
<<Class: geo:Geometry, `geo:Geometry`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving <<Class: geo:Geometry, `geo:Geometry`>> return the correct result on a test dataset
.. *Reference*: <<_class_geogeometry>>
.. *Test Type*: Capabilities

==== A.3.DGGS.1.2 `/conf/geometry-extension/geometry-collection-class`
*Requirement*: `/req/geometry-extension/geometry-collection-class`

Implementations shall allow the RDFS class 
<<Class: geo:GeometryCollection, `geo:GeometryCollection`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: check conformance with this requirement
.. *Test method*: verify that queries involving <<Class: geo:GeometryCollection, `geo:GeometryCollection`>> return the correct result on a test dataset
.. *Reference*: <<_class_geogeometrycollection>>
.. *Test Type*: Capabilities

==== A.3.DGGS.1.3 `/conf/geometry-extension/feature-properties`
*Requirement*: `/req/geometry-extension/feature-properties`

Implementations shall allow the properties 
<<Property: geo:hasGeometry, `geo:hasGeometry`>>, 
<<Property: geo:hasDefaultGeometry, `geo:hasDefaultGeometry`>>, 
<<Property: geo:hasLength, `geo:hasLength`>>, 
<<Property: geo:hasArea, `geo:hasArea`>>, 
<<Property: geo:hasVolume, `geo:hasVolume`>> 
<<Property: geo:hasCentroid, `geo:hasCentroid`>>, 
<<Property: geo:hasBoundingBox, `geo:hasBoundingBox`>> and 
<<Property: geo:hasSpatialResolution, `geo:hasSpatialResolution`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_standard_properties_for_geofeature>>
.. *Test Type*: Capabilities

==== A.3.DGGS.1.4 `/conf/geometry-extension/geometry-properties`
*Requirement*: `/req/geometry-extension/geometry-properties`

Implementations shall allow the properties 
<<Property: geo:dimension, `geo:dimension`>>, 
// <<Property: geo:coordinateDimension, `geo:coordinateDimension`>>, 
<<Property: geo:spatialDimension, `geo:spatialDimension`>>, 
<<Property: geo:isEmpty, `geo:isEmpty`>>, 
<<Property: geo:isSimple, `geo:isSimple`>> and 
<<Property: geo:hasSerialization, `geo:hasSerialization`>> 
to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these properties return the correct result for a test dataset.
.. *Reference*: <<_standard_properties_for_geogeometry>>
.. *Test Type*: Capabilities

==== A.3.DGGS.1.5 `/conf/geometry-extension/query-functions`
*Requirement*: `/req/geometry-extension/query-functions`  

Implementations shall support the functions 
<<Function: geof:distance, `geof:distance`>>, 
<<Function: geof:buffer, `geof:buffer`>>, 
<<Function: geof:intersection, `geof:intersection`>>, 
<<Function: geof:union, `geof:union`>>, 
<<Function: geof:isEmpty, `geof:isEmpty`>>, 
<<Function: geof:isSimple, `geof:isSimple`>>, 
<<Function: geof:area, `geof:area`>>, 
<<Function: geof:length, `geof:length`>>,
<<Function: geof:numGeometries, `geof:numGeometries`>>,
<<Function: geof:geometryN, `geof:geometryN`>>, 
<<Function: geof:transform, `geof:transform`>>,
<<Function: geof:dimension, `geof:dimension`>>, 
<<Function: geof:difference, `geof:difference`>>, 
<<Function: geof:symDifference, `geof:symDifference`>>, 
<<Function: geof:envelope, `geof:envelope`>> and 
<<Function: geof:boundary, `geof:boundary`>> 
as SPARQL extension functions
// , consistent with the definitions of their corresponding functions in Simple Features <<ISO19125-1>> (`distance`, `buffer`, `intersection`, `union`, `isEmpty`, `isSimple`, `area`, `length`, 
// `numGeometries`, `geometryN`, `transform`, `dimension`, `difference`, `symDifference`, `envelope` and `boundary` respectively) and other attached definitions and also 
// http://www.opengis.net/def/function/geosparql/minX[`geof:maxX`],
// http://www.opengis.net/def/function/geosparql/maxY[`geof:maxY`], 
// http://www.opengis.net/def/function/geosparql/maxZ[`geof:maxZ`],  
// http://www.opengis.net/def/function/geosparql/minX[`geof:minX`], 
// http://www.opengis.net/def/function/geosparql/minY[`geof:minY`] and
// http://www.opengis.net/def/function/geosparql/minZ[`geof:minZ`]
// SPARQL extension functions.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving each of the following functions returns the correct result for a test dataset when using the specified serialization and version: 
<<Function: geof:distance, `geof:distance`>>, 
<<Function: geof:buffer, `geof:buffer`>>, 
<<Function: geof:intersection, `geof:intersection`>>, 
<<Function: geof:union, `geof:union`>>, 
<<Function: geof:isEmpty, `geof:isEmpty`>>, 
<<Function: geof:isSimple, `geof:isSimple`>>, 
<<Function: geof:area, `geof:area`>>, 
<<Function: geof:length, `geof:length`>>,
<<Function: geof:numGeometries, `geof:numGeometries`>>,
<<Function: geof:geometryN, `geof:geometryN`>>, 
<<Function: geof:transform, `geof:transform`>>,
<<Function: geof:dimension, `geof:dimension`>>, 
<<Function: geof:difference, `geof:difference`>>, 
<<Function: geof:symDifference, `geof:symDifference`>>, 
<<Function: geof:envelope, `geof:envelope`>> and 
<<Function: geof:boundary, `geof:boundary`>>. 
.. *Reference*: <<_non_topological_query_functions>>
.. *Test Type*: Capabilities

==== A.3.DGGS.1.6 `/conf/geometry-extension/srid-function`
*Requirement*: `/req/geometry-extension/srid-function`

Implementations shall support 
<<Function: geof:getSRID, `geof:getSRID`>> 
as a SPARQL extension function.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a SPARQL query involving the <<Function: geof:getSRID, `geof:getSRID`>> function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_function_geofgetsrid>>
.. *Test Type*: Capabilities

==== A.3.DGGS.1.7 `/conf/geometry-extension/sa-functions`
*Requirement*: `/req/geometry-extension/sa-functions`

Implementations shall support 
<<Function: geof:aggBoundingBox,`geof:boundingBox`>>, 
<<Function: geof:aggBoundingCircle,`geof:boundingCircle`>>, 
<<Function: geof:aggCentroid,`geof:centroid`>>, 
<<Function: geof:aggConcatLines,`geof:concatLines`>>, 
<<Function: geof:aggConcaveHull,`geof:concaveHull`>>, 
<<Function: geof:aggConvexHull,`geof:convexHull`>> and 
<<Function: geof:aggUnion,`geof:union2`>>
as a SPARQL extension functions.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving these functions return the correct result for a test dataset.
.. *Reference*: <<_spatial_aggregate_functions>>
.. *Test Type*: Capabilities

// === A.3.DGGS.2 WKT Serialization

// ==== A.3.DGGS.2.1 `/conf/geometry-extension/wkt-literal`
// *Requirement*: `/req/geometry-extension/wkt-literal`

// All RDFS Literals of type <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> shall consist of an optional IRI identifying the coordinate reference system and a required Well Known Text (WKT) description of a geometric value. Valid <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> instances are formed by either a WKT string as defined in <<ISO13249>> or by concatenating a valid absolute IRI, as defined in <<IETF3987>>, enclose in angled brackets (`<` & `>`) followed by a single space (Unicode U+0020 character) as a separator, and a WKT string as defined in <<ISO13249>>.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving  <<RDFS Datatype: geo:wktLiteral, WKT Literal>> values return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geowktliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.2.2 `/conf/geometry-extension/wkt-literal-default-srs`
// *Requirement*: `/req/geometry-extension/wkt-literal-default-srs`

// The IRI http://www.opengis.net/def/crs/OGC/1.3/CRS84[`+<http://www.opengis.net/def/crs/OGC/1.3/CRS84>+`] shall be assumed as the spatial reference system for <<RDFS Datatype: geo:wktLiteral, `geo:wktLiteral`>> instances that do not specify an explicit spatial reference system IRI.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving  <<RDFS Datatype: geo:wktLiteral, WKT Literal>> values without an explicit encoded SRS IRI return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geowktliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.2.3 `/conf/geometry-extension/wkt-axis-order`
// *Requirement*: `/req/geometry-extension/wkt-axis-order`

// Coordinate tuples within <<RDFS Datatype: geo:wktLiteral, WKT Literal>> instances shall be interpreted using the axis order defined in the SRS used.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving  <<RDFS Datatype: geo:wktLiteral, WKT Literal>> values return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geowktliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.2.4 `/conf/geometry-extension/wkt-literal-empty`
// *Requirement*: `/req/geometry-extension/wkt-literal-empty`

// An empty RDFS Literal of type <<RDFS Datatype: geo:wktLiteral, WKT Literal>> shall be interpreted as an empty geometry.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:wktLiteral, WKT Literal>> values return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geowktliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.2.5 `/conf/geometry-extension/geometry-as-wkt-literal`
// *Requirement*: `/req/geometry-extension/geometry-as-wkt-literal`

// Implementations shall allow the RDF property <<Property: geo:asWKT, `geo:asWKT`>> to be used in SPARQL graph patterns.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving the <<Property: geo:asWKT, `geo:asWKT`>> property return the correct result for a test dataset.
// .. *Reference*: <<_property_geoaswkt>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.2.6 `/req/geometry-extension/asWKT-function`
// *Requirement*: `/req/geometry-extension/asWKT-function` 

// Implementations shall support <<Function: geof:asWKT, `geof:asWKT`>>, as a SPARQL extension function

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asWKT, `geof:asWKT`>> function returns the correct result for a test dataset when using the specified serialization and version.
// .. *Reference*: <<_function_geofaswkt>>
// .. *Test Type*: Capabilities

// === A.3.DGGS.3 GML Serialization
// ==== A.3.DGGS.3.1 `/conf/geometry-extension/gml-literal`
// *Requirement*: `/req/geometry-extension/gml-literal`

// All <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> instances shall consist of a valid element from the GML schema that implements a subtype of GM_Object as defined in [OGC 07-036].

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> values return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geogmlliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.3.2 `/conf/geometry-extension/gml-literal-empty`
// *Requirement*: `/req/geometry-extension/gml-literal-empty`

// An empty <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> shall be interpreted as an empty geometry.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:gmlLiteral, `geo:gmlLiteral`>> values return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geogmlliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.3.3 `/conf/geometry-extension/gml-profile`
// *Requirement*: `/req/geometry-extension/gml-profile`

// Implementations shall document supported GML profiles.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Examine the implementation’s documentation to verify that the supported GML profiles are documented.
// .. *Reference*: <<_rdfs_datatype_geogmlliteral>>
// .. *Test Type*: Documentation

// ==== A.3.DGGS.3.4 `/conf/geometry-extension/geometry-as-gml-literal`
// *Requirement*: `/req/geometry-extension/geometry-as-gml-literal` 

// Implementations shall allow the RDF property <<Property: geo:asWKT, `geo:asGML`>> to be used in SPARQL graph patterns.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving the <<Property: geo:asWKT, `geo:asGML`>> property return the correct result for a test dataset.
// .. *Reference*: <<_property_geoasgml>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.3.5 `/req/geometry-extension/asGML-function`
// *Requirement*: `/req/geometry-extension/asGML-function` 

// Implementations shall support <<Function: geof:asGML, `geof:asGML`>>, as a SPARQL extension function

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asGML, `geof:asGML`>> function returns the correct result for a test dataset when using the specified serialization and version.
// .. *Reference*: <<_function_geofasgml>>
// .. *Test Type*: Capabilities

// === A.3.DGGS.4 GeoJSON Serialization
// ==== A.3.DGGS.4.1 `/req/geometry-extension/geojson-literal`
// *Requirement*: `/req/geometry-extension/geojson-literal`

// All <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> instances shall consist of valid JSON that conforms to the GeoJSON specification <<GEOJSON>>

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> values return the correct result for a test dataset.
// .. *Reference*: <<_property_geoasgml>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.4.2 `/req/geometry-extension/geojson-literal-srs`
// *Requirement*: `/req/geometry-extension/geojson-literal-default-srs`

// The IRI http://www.opengis.net/def/crs/OGC/1.3/CRS84[<http://www.opengis.net/def/crs/OGC/1.3/CRS84>] shall be assumed as the SRS for <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> instances that do not specify an explicit SRS IRI.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> values without an explicit encoded SRS IRI return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geogeojsonliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.4.3 `/req/geometry-extension/geojson-literal-empty`
// *Requirement*: `/req/geometry-extension/geojson-literal-empty`

// An empty <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> shall be interpreted as an empty geometry.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:geoJSONLiteral, `geo:geoJSONLiteral`>> values return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geogeojsonliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.4.4 `/req/geometry-extension/geometry-as-geojson-literal`
// *Requirement*: `/req/geometry-extension/geometry-as-geojson-literal` 

// Implementations shall allow the RDF property <<Property: geo:asGeoJSON, `geo:asGeoJSON`>> to be used in SPARQL graph patterns.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving the <<Property: geo:asGeoJSON, `geo:asGeoJSON`>> property return the correct result for a test dataset.
// .. *Reference*: <<_property_geoasgeojson>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.4.5 `/req/geometry-extension/asGeoJSON-function`
// *Requirement*: `/req/geometry-extension/asGeoJSON-function` 

// Implementations shall support <<Function: geof:asGeoJSON, `geof:asGeoJSON`>>, as a SPARQL extension function

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asGeoJSON, `geof:asGeoJSON`>> function returns the correct result for a test dataset when using the specified serialization and version.
// .. *Reference*: <<_function_geofasgeojson>>
// .. *Test Type*: Capabilities

// === A.3.DGGS.5 KML Serialization
// ==== A.3.DGGS.5.1 `/req/geometry-extension/kml-literal`
// *Requirement*: `/req/geometry-extension/kml-literal`

// All <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> instances shall consist of a valid element from the KML schema that implements a `kml:AbstractObjectGroup` as defined in <<OGCKML>>.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> values return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geokmlliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.5.2 `/req/geometry-extension/kml-literal-srs`
// *Requirement*: `/req/geometry-extension/kml-literal-default-srs`

// The IRI http://www.opengis.net/def/crs/OGC/1.3/CRS84[<http://www.opengis.net/def/crs/OGC/1.3/CRS84>] shall be assumed as the SRS for <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> instances that do not specify an explicit SRS IRI.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>>  values without an explicit encoded SRS IRI return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geokmlliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.5.3 `/req/geometry-extension/kml-literal-empty`
// *Requirement*: `/req/geometry-extension/kml-literal-empty`

// An empty <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> shall be interpreted as an empty geometry.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:kmlLiteral, `geo:kmlLiteral`>> values return the correct result for a test dataset.
// .. *Reference*: <<_rdfs_datatype_geokmlliteral>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.5.4 `/req/geometry-extension/geometry-as-kml-literal`
// *Requirement*: `/req/geometry-extension/geometry-as-kml-literal` 

// Implementations shall allow the RDF property <<Property: geo:asKML, `geo:asKML`>> to be used in SPARQL graph patterns.

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that queries involving the <<Property: geo:asKML, `geo:asKML`>>  property return the correct result for a test dataset.
// .. *Reference*: <<_property_geoaskml>>
// .. *Test Type*: Capabilities

// ==== A.3.DGGS.5.5 `/req/geometry-extension/asKML-function`
// *Requirement*: `/req/geometry-extension/asKML-function` 

// Implementations shall support <<Function: geof:asKML, as KML>>, as a SPARQL extension function

// .. *Test purpose*: Check conformance with this requirement
// .. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asKML, `geof:asKML`>> function returns the correct result for a test dataset when using the specified serialization and version.
// .. *Reference*: <<_function_geofaskml>>
// .. *Test Type*: Capabilities

=== A.3.DGGS.2 DGGS Serialization
==== A.3.DGGS.2.1 `/req/geometry-extension/dggs-literal`
*Requirement*: `/req/geometry-extension/dggs-literal`

All RDFS Literals of type <<RDFS Datatype: geo:dggsLiteral, `geo:dggsLiteral`>> shall consist of a DGGS geometry serialization formulated according to a specific DGGS literal type identified by a datatype specializing this generic datatype.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries do not use use this datatype but instead use specializations of it.
.. *Reference*: <<_rdfs_datatype_geodggsliteral>>
.. *Test Type*: Capabilities

==== A.3.DGGS.2.2 `/req/geometry-extension/dggs-literal-empty`
*Requirement*: `/req/geometry-extension/dggs-literal-empty`

An empty <<RDFS Datatype: geo:dggsLiteral, `geo:dggsLiteral`>> shall be interpreted as an empty geometry.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving empty <<RDFS Datatype: geo:dggsLiteral, `geo:dggsLiteral`>> values return the correct result for a test dataset.
.. *Reference*: <<_rdfs_datatype_geodggsliteral>>
.. *Test Type*: Capabilities

==== A.3.DGGS.2.3 `/req/geometry-extension/geometry-as-dggs-literal`
*Requirement*: `/req/geometry-extension/geometry-as-dggs-literal` 

Implementations shall allow the RDF property <<Property: geo:asDGGS, `geo:asDGGS`>> to be used in SPARQL graph patterns.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving the <<Property: geo:asDGGS, `geo:asDGGS`>> property return the correct result for a test dataset.
.. *Reference*: <<_property_geoasdggs>>
.. *Test Type*: Capabilities

==== A.3.DGGS.2.4 `/req/geometry-extension/asDGGS-function`
*Requirement*: `/req/geometry-extension/asDGGS-function` 

Implementations shall support <<Function: geof:asDGGS, `geof:asDGGS`>>, as a SPARQL extension function

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving the <<Function: geof:asDGGS, `geof:asDGGS`>> function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_function_geofasdggs>>
.. *Test Type*: Capabilities

== A.4 Conformance Class: Geometry Topology Extension

*Conformance Class IRI*: `/conf/geometry-topology-extension`

=== A.4.1 Tests for all relation families
==== A.4.1.1 `/conf/geometry-topology-extension/relate-query-function`
*Requirement*: `/req/geometry-topology-extension/relate-query-function`

Implementations shall support 
<<Function: geof:relate, `geof:relate`>> 
as a SPARQL extension function, consistent with the relate operator defined in Simple Features <<OGCSFACA>> <<ISO19125-1>>.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving the http://www.opengis.net/def/function/geosparql/relate[`geof:relate`] function returns the correct result for a test dataset when using the specified serialization and version.
.. *Reference*: <<_common_query_functions>>
.. *Test Type*: Capabilities

=== A.4.2 Simple Features Relation Family
==== A.4.2.1 `/conf/geometry-topology-extension/sf-query-functions`
*Requirement*: `/req/geometry-topology-extension/sf-query-functions`

Implementations shall support 
http://www.opengis.net/def/function/geosparql/sfEquals[`geof:sfEquals`], 
http://www.opengis.net/def/function/geosparql/sfDisjoint[`geof:sfDisjoint`], 
http://www.opengis.net/def/function/geosparql/sfIntersects[`geof:sfIntersects`], 
http://www.opengis.net/def/function/geosparql/sfTouches[`geof:sfTouches`], 
http://www.opengis.net/def/function/geosparql/sfCrosses[`geof:sfCrosses`], 
http://www.opengis.net/def/function/geosparql/sfWithin[`geof:sfWithin`], 
http://www.opengis.net/def/function/geosparql/sfContains[`geof:sfContains`] and 
http://www.opengis.net/def/function/geosparql/sfOverlaps[`geof:sfOverlaps`] 
as SPARQL extension functions, consistent with their corresponding DE-9IM intersection patterns, as defined by Simple Features <<OGCSFACA>> <<ISO19125-1>>.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving each of the following functions returns the correct result for a test dataset when using the specified serialization and version: http://www.opengis.net/def/function/geosparql/sfEquals[`geof:sfEquals`], http://www.opengis.net/def/function/geosparql/sfDisjoint[`geof:sfDisjoint`], http://www.opengis.net/def/function/geosparql/efIntersects[`geof:sfIntersects`], http://www.opengis.net/def/function/geosparql/sfTouches[`geof:sfTouches`], http://www.opengis.net/def/function/geosparql/sfCrosses[`geof:sfCrosses`], http://www.opengis.net/def/function/geosparql/sfWithin[`geof:sfWithin`], http://www.opengis.net/def/function/geosparql/sfContains[`geof:sfContains`], http://www.opengis.net/def/function/geosparql/sfOverlaps[`geof:sfOverlaps`] .
.. *Reference*: <<Simple Features Relation Family>>
.. *Test Type*: Capabilities

=== A.4.3 Egenhofer Relation Family
==== A.4.3.1 `/conf/geometry-topology-extension/eh-query-functions`
*Requirement*: `/req/geometry-topology-extension/eh-query-functions`

Implementations shall support 
http://www.opengis.net/def/function/geosparql/ehEquals[`geof:ehEquals`], 
http://www.opengis.net/def/function/geosparql/ehDisjoint[`geof:ehDisjoint`], 
http://www.opengis.net/def/function/geosparql/ehMeet[`geof:ehMeet`], 
http://www.opengis.net/def/function/geosparql/ehOverlap[`geof:ehOverlap`], 
http://www.opengis.net/def/function/geosparql/ehCovers[`geof:ehCovers`], 
http://www.opengis.net/def/function/geosparql/ehCoveredBy[`geof:ehCoveredBy`], 
http://www.opengis.net/def/function/geosparql/ehInside[`geof:ehInside`] and 
http://www.opengis.net/def/function/geosparql/ehContains[`geof:ehContains`] 
as SPARQL extension functions, consistent with their corresponding DE-9IM intersection patterns, as defined by Simple Features <<OGCSFACA>> <<ISO19125-1>>.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving each of the following functions returns the correct result for a test dataset when using the specified serialization and version: http://www.opengis.net/def/function/geosparql/ehEquals[`geof:ehEquals`], http://www.opengis.net/def/function/geosparql/ehDisjoint[`geof:ehDisjoint`], http://www.opengis.net/def/function/geosparql/ehMeet[`geof:ehMeet`], http://www.opengis.net/def/function/geosparql/ehOverlap[`geof:ehOverlap`], http://www.opengis.net/def/function/geosparql/ehCovers[`geof:ehCovers`], http://www.opengis.net/def/function/geosparql/ehCoveredBy[`geof:ehCoveredBy`], http://www.opengis.net/def/function/geosparql/ehInside[`geof:ehInside`], http://www.opengis.net/def/function/geosparql/ehContains[`geof:ehContains`].
.. *Reference*: <<Egenhofer Relation Family>>
.. *Test Type*: Capabilities

=== A.4.4 RCC8 Relation Family
==== A.4.4.1 `/conf/geometry-topology-extension/rcc8-query-functions`
*Requirement*: `/req/geometry-topology-extension/rcc8-query-functions`

Implementations shall support 
http://www.opengis.net/def/function/geosparql/rcc8eq[`geof:rcc8eq`], 
http://www.opengis.net/def/function/geosparql/rcc8dc[`geof:rcc8dc`], 
http://www.opengis.net/def/function/geosparql/rcc8ec[`geof:rcc8ec`], 
http://www.opengis.net/def/function/geosparql/rcc8po[`geof:rcc8po`], 
http://www.opengis.net/def/function/geosparql/rcc8tppi[`geof:rcc8tppi`], 
http://www.opengis.net/def/function/geosparql/rcc8tpp[`geof:rcc8tpp`], 
http://www.opengis.net/def/function/geosparql/rcc8ntpp[`geof:rcc8ntpp`] and 
http://www.opengis.net/def/function/geosparql/rcc8ntppi[`geof:rcc8ntppi`] 
as SPARQL extension functions, consistent with their corresponding DE-9IM intersection patterns, as defined by Simple Features <<OGCSFACA>> <<ISO19125-1>>.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving each of the following functions returns the correct result for a test dataset when using the specified serialization and version: http://www.opengis.net/def/function/geosparql/rcc8eq[`geof:rcc8eq`], http://www.opengis.net/def/function/geosparql/rcc8dc[`geof:rcc8dc`], http://www.opengis.net/def/function/geosparql/rcc8ec[`geof:rcc8ec`], http://www.opengis.net/def/function/geosparql/rcc8po[`geof:rcc8po`], http://www.opengis.net/def/function/geosparql/rcc8tppi[`geof:rcc8tppi`], http://www.opengis.net/def/function/geosparql/rcc8tpp[`geof:rcc8tpp`], http://www.opengis.net/def/function/geosparql/rcc8ntpp[`geof:rcc8ntpp`], http://www.opengis.net/def/function/geosparql/rcc8ntppi[`geof:rcc8ntppi`] .
.. *Reference*: <<RCC8 Relation Family>>
.. *Test Type*: Capabilities

== A.5 Conformance Class: RDFS Entailment Extension

*Conformance Class IRI*: `/conf/rdfs-entailment-extension`

=== A.5.1 Tests for all implementations
==== A.5.1.1 `/conf/rdfsentailmentextension/bgp-rdfs-ent`
*Requirement*: `/req/rdfs-entailment-extension/bgp-rdfs-ent`

Basic graph pattern matching shall use the semantics defined by the RDFS Entailment Regime <<SPARQLENT>>.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving entailed RDF triples returns the correct result for a test dataset using the specified serialization, version and relation_family.
.. *Reference*: <<_common_requirements>>
.. *Test Type*: Capabilities

=== A.5.2 WKT Serialization
==== A.5.2.1 `/conf/rdfs-entailment-extension/wkt-geometry-types`
*Requirement*: `/req/rdfs-entailment-extension/wkt-geometry-types`

Implementations shall support graph patterns involving terms from an RDFS/OWL class hierarchy of geometry types consistent with the one in the specified version of Simple Features <<OGCSFACA>> <<ISO19125-1>>.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving WKT Geometry types returns the correct result for a test dataset using the specified version of Simple Features. 
.. *Reference*: <<_geometry_class_hierarchy>>
.. *Test Type*: Capabilities

=== A.5.3 GML Serialization
==== A.5.3.1 `/conf/rdfs-entailment-extension/gml-geometry-types`
*Requirement*: `/req/rdfs-entailment-extension/gml-geometry-types` 

Implementations shall support graph patterns involving terms from an RDFS/OWL class hierarchy of geometry types consistent with the GML schema that implements GM_Object using the specified version of GML <<OGC07-036>>.

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that a set of SPARQL queries involving GML Geometry types returns the correct result for a test dataset using the specified version of GML.
.. *Reference*: <<_geometry_class_hierarchy_2>>
.. *Test Type*: Capabilities

== A.6 Conformance Class: Query Rewrite Extension

*Conformance Class IRI*: `/conf/query-rewrite-extension`

=== A.6.1 Simple Features Relation Family
==== A.6.1.1 `/conf/query-rewrite-extension/sf-query-rewrite`
*Requirement*: `/req/query-rewrite-extension/sf-query-rewrite`

Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime <<SPARQLENT>> for the RIF rules <<RIFCORE>> 
http://www.opengis.net/def/rule/geosparql/sfEquals[`geor:sfEquals`], 
http://www.opengis.net/def/rule/geosparql/sfDisjoint[`geor:sfDisjoint`], 
http://www.opengis.net/def/rule/geosparql/sfIntersects[`geor:sfIntersects`], 
http://www.opengis.net/def/rule/geosparql/sfTouches[`geor:sfTouches`], 
http://www.opengis.net/def/rule/geosparql/sfCrosses[`geor:sfCrosses`], 
http://www.opengis.net/def/rule/geosparql/sfWithin[`geor:sfWithin`], 
http://www.opengis.net/def/rule/geosparql/sfContains[`geor:sfContains`] and 
http://www.opengis.net/def/rule/geosparql/sfOverlaps[`geor:sfOverlaps`].

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving the following query transformation rules return the correct result for a test dataset when using the specified serialization and version: http://www.opengis.net/def/rule/geosparql/sfEquals[`geor:sfEquals`], http://www.opengis.net/def/rule/geosparql/sfDisjoint[`geor:sfDisjoint`], http://www.opengis.net/def/rule/geosparql/sfIntersects[`geor:sfIntersects`], http://www.opengis.net/def/rule/geosparql/sfTouches[`geor:sfTouches`], http://www.opengis.net/def/rule/geosparql/sfCrosses[`geor:sfCrosses`], http://www.opengis.net/def/rule/geosparql/sfWithin[`geor:sfWithin`], http://www.opengis.net/def/rule/geosparql/sfContains[`geor:sfContains`] and http://www.opengis.net/def/rule/geosparql/sfOverlaps[`geor:sfOverlaps`].
.. *Reference*: <<Simple Features Relation Family>>
.. *Test Type*: Capabilities

=== A.6.2 Egenhofer Relation Family
==== A.6.2.1 `/conf/query-rewrite-extension/eh-query-rewrite`
*Requirement*: `/req/query-rewrite-extension/eh-query-rewrite`

Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime <<SPARQLENT>> for the RIF rules <<RIFCORE>> 
http://www.opengis.net/def/rule/geosparql/ehEquals[`geor:ehEquals`], 
http://www.opengis.net/def/rule/geosparql/ehDisjoint[`geor:ehDisjoint`], 
http://www.opengis.net/def/rule/geosparql/ehMeet[`geor:ehMeet`], 
http://www.opengis.net/def/rule/geosparql/ehOverlap[`geor:ehOverlap`],
http://www.opengis.net/def/rule/geosparql/ehCovers[`geor:ehCovers`], 
http://www.opengis.net/def/rule/geosparql/ehCoveredBy[`geor:ehCoveredBy`], 
http://www.opengis.net/def/rule/geosparql/ehInside[`geor:ehInside`] and 
http://www.opengis.net/def/rule/geosparql/ehContains[`geor:ehContains`].

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving the following query transformation rules return the correct result for a test dataset when using the specified serialization and version: http://www.opengis.net/def/rule/geosparql/ehEquals[`geor:ehEquals`], http://www.opengis.net/def/rule/geosparql/ehDisjoint[`geor:ehDisjoint`], http://www.opengis.net/def/rule/geosparql/ehMeet[`geor:ehMeet`], http://www.opengis.net/def/rule/geosparql/ehOverlap[`geor:ehOverlap`], http://www.opengis.net/def/rule/geosparql/ehCovers[`geor:ehCovers`], http://www.opengis.net/def/rule/geosparql/ehCoveredBy[`geor:ehCoveredBy`], http://www.opengis.net/def/rule/geosparql/ehInside[`geor:ehInside`], http://www.opengis.net/def/rule/geosparql/ehContains[`geor:ehContains`].
.. *Reference*: <<Egenhofer Relation Family>>
.. *Test Type*: Capabilities

=== A.6.3 RCC8 Relation Family
==== A.6.3.1 `/conf/query-rewrite-extension/rcc8-query-rewrite`
*Requirement*: `/req/query-rewrite-extension/rcc8-query-rewrite`

Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime <<SPARQLENT>> for the RIF rules <<RIFCORE>> 
http://www.opengis.net/def/rule/geosparql/rcc8eq[`geor:rcc8eq`], 
http://www.opengis.net/def/rule/geosparql/rcc8dc[`geor:rcc8dc`], 
http://www.opengis.net/def/rule/geosparql/rcc8ec[`geor:rcc8ec`], 
http://www.opengis.net/def/rule/geosparql/rcc8po[`geor:rcc8po`], 
http://www.opengis.net/def/rule/geosparql/rcc8tppi[`geor:rcc8tppi`], 
http://www.opengis.net/def/rule/geosparql/rcc8tpp[`geor:rcc8tpp`], 
http://www.opengis.net/def/rule/geosparql/rcc8ntpp[`geor:rcc8ntpp`] and 
http://www.opengis.net/def/rule/geosparql/rcc8ntppi[`geor:rcc8ntppi`].

.. *Test purpose*: Check conformance with this requirement
.. *Test method*: Verify that queries involving the following query transformation rules return the correct result for a test dataset when using the specified serialization and version: http://www.opengis.net/def/rule/geosparql/rcc8eq[`geor:rcc8eq`], http://www.opengis.net/def/rule/geosparql/rcc8dc[`geor:rcc8dc`], http://www.opengis.net/def/rule/geosparql/rcc8ec[`geor:rcc8ec`], http://www.opengis.net/def/rule/geosparql/rcc8po[`geor:rcc8po`], http://www.opengis.net/def/rule/geosparql/rcc8tppi[`geor:rcc8tppi`], http://www.opengis.net/def/rule/geosparql/rcc8tpp[`geor:rcc8tpp`], http://www.opengis.net/def/rule/geosparql/rcc8ntpp[`geor:rcc8ntpp`], http://www.opengis.net/def/rule/geosparql/rcc8ntppi[`geor:rcc8ntppi`].
.. *Reference*: <<RCC8 Relation Family>>
.. *Test Type*: Capabilities
