=== Annex C 
=== (informative)
=== Best-practice: A GeoSPARQL-enabled triple stores as a backend of an OGC web service

This annex wants to present best practices of write linked data backends to OGC webservices 

==== C.1 Accessing geospatial features in a SPARQL endpoint

Geospatial features in SPARQL endpoints as defined in the GeoSPARQL standard are instances of subclasses of geo:Feature.
They include one or many geo:hasGeometry relations and a set of further properties which may or may not refer to further instances related to the geospatial feature. 
Similarly to SQL backends of OGC webservices, geospatial featurecollections are made explicit by defining a SPARQL query retrieving a set of triples which may be converted to a geodata format.

==== C.2 Mappings from CQL statements to GeoSPARQL queries


===== C2.1 Filter Functions

GeoSPARQL includes equivalents of many CQL filter functions as can be seen in the table below.

| First Header  | Second Header |
| ------------- | ------------- |
| geometry1 CONTAINS geometry2  | FILTER(geof:sfContains(?geometry1,?geometry2))  |
| geometry1 CROSSES geometry2  | FILTER(geof:sfCrosses(?geometry1,?geometry2))  |
| geometry1 DISJOINT geometry2  | FILTER(geof:sfDisjoint(?geometry1,?geometry2))  |
| geometry1 EQUALS geometry2  | FILTER(geof:sfEquals(?geometry1,?geometry2))  |
| geometry1 INTERSECTS geometry2  | FILTER(geof:sfIntersects(?geometry1,?geometry2))  |
| geometry1 OVERLAPS geometry2  | FILTER(geof:sfOverlaps(?geometry1,?geometry2))  |
| geometry1 TOUCHES geometry2  | FILTER(geof:sfTouches(?geometry1,?geometry2))  |
| geometry1 WITHIN geometry2  | FILTER(geof:sfWithin(?geometry1,?geometry2))  |

===== C2.2 Geospatial Operators

===== C2.3 Temporal Operators

Temporal operators are currently not part of the GeoSPARQL standard. 
