[abstract]
== Abstract 

GeoSPARQL coexists with a number of other well known ontologies that are either used with it or could be. The aim of this Best Practice Document is to describe alignments between GeoSPARQL and these other ontologies.

[.preface]
== Preface

The OGC GeoSPARQL Standard defines:

* A formal _profile_;
* **this document;**
* A core RDF/OWL ontology for geographic information representation;
* A set of SPARQL extension functions;
* A Functions & Rules vocabulary, derived from the ontology;
* A Simple Features geometry types vocabulary;
* SHACL shapes for RDF data validation.

This document aims to encourage broad use of GeoSPARQL by informatively describing alignments between several of these components and other well known ontologies that are either used with GeoSPARQL or could be.

[.preface]
== Keywords

Open Geospatial Consortium, OGC, spatial, ontology, Knowledge Graph, Semantic Web, Linked Data, RDF, Resource Description Framework, Web Ontology Language, OWL, SPARQL, Simple Features, feature, geometry

[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
[%header, cols="1, 3"]
|===
|Contact | Company
| Joseph Abhayaratna | Geoscape Australia
| Timo Homburg | Mainz University Of Applied Sciences
| Matthew Perry | Oracle America
| Nicholas J. Car | KurrawongAI
|===

[.preface]
== Submitting organizations

The following organizations submitted this Implementation Standard to the Open Geospatial Consortium Inc.:

* CSIRO
* Cubewerx Inc.
* Defence Science and Technology Laboratory (DSTL)
* Geonovum
* Geoscape Australia
* Geoscience Australia
* KurrawongAI
* Mainz University Of Applied Sciences
* Oracle America
* OSGeo
* SURROUND Australia Pty Ltd.
