:CSname: Extended Well Known Binary (EWKB)
:Title: {CSname} Community Standard Work Item Justification
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments
:year: 2025

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <yyyy-mm-dd>
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    25-020
|Category: OGC(R) Community Standard Work Item Justification
|Authors:   GeoSPARQL SWG
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) {year} Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

== Introduction

This document provides a justification to the OGC Technical Committee (TC) for consideration of {CSname} as a Community standard. This justification, along with the submitted candidate Community standard, will form the basis for TC review and vote to approve the start of a Work Item as the first step in the Community standard process for this standard.

The submitters agree to abide by the TC Policies and Procedures and OGC Intellectual Property Rights Policy (http://www.opengeospatial.org/ogc/policies) during the processing of this submission.

Once approved, the Community standard Work Item defined by this document is valid for six (6) months.

== Overview of proposed submission

Extended Well Known Binary (EWKB) is an open specification designed to extend OGC's Well Known Binary (WKB) encoding to address the following shortcomings:

[start=1]
. WKB made no allowance for more than an X and Y coordinate, such as the Z and M coordinates that are common in GIS applications.
. WKB made no allowance for embedding a spatial reference identifier (SRID), which made it unusable as a database import/export format.

== Motivation of supporting OGC Members for this submission

The membership of the GeoSPARQL Standards Working Group (SWG) support the submission of EWKB as a Community Standard to support the development of GeoSPARQL 1.3 which adds 3D capabilities to the standard. As a commonly supported spatial format, WKB is considered an essential geometry encoding. However, the ability to support 3D use cases as well as embedding of an SRID, along with its backwards compatibility with the OGC WKB standard, make EWKB the logical choice for achieving this requirement.

The GeoSPARQL SWG requires a normative reference for the encoding, which in turn creates the requirement for adoption of EWKB as a Community Standard.

== Relationship to other OGC Standards

EWKB has the following relationships to other OGC standards:

[start=1]
. Simple Features, which provides the definitions of spatial features and Well Known Binary (WKB), upon which EWKB is based.
. GeoSPARQL 1.3, which requires it as an encoding. 

== Alignment with OGC Standards Baseline

EWKB is a direct extension of WKB, maintaining backwards compatability to promote adoption and interoperability whilst addressing core shortcomings that bring WKB into line with current and future requirements of the binary format.

== Evidence of implementation

The following implementations use the proposed Community standard.

=== *Implementation name:* PostGIS

*Date of most recent version:* 3.5.3

*Implementation description:* PostGIS extends the capabilities of PostgreSQL relational database by adding support for storing, indexing and querying geospatial data.

*Implementation URL:* https://postgis.net/

*Is implementation complete?*

* [x] Yes
* [ ] No

=== *Implementation name:* GEOS

*Date of most recent version:* 3.13.1

*Implementation description:* GEOS is a C/C++ library for computational geometry with a focus on algorithms used in geographic information systems (GIS) software.

*Implementation URL:* https://libgeos.org

*Is implementation complete?*

* [x] Yes
* [ ] No

=== *Implementation name:* GDAL

*Date of most recent version:* 3.11.0

*Implementation description:* GDAL is a translator library for raster and vector geospatial data formats.

*Implementation URL:* https://gdal.org

*Is implementation complete?*

* [x] Yes
* [ ] No

=== *Implementation name:* JTS Topology Suite

*Date of most recent version:* 1.20.0

*Implementation description:* The JTS Topology Suite is a Java library for creating and manipulating vector geometry.

*Implementation URL:* https://github.com/locationtech/jts

*Is implementation complete?*

* [x] Yes
* [ ] No

== Information on adoption

////
Describe the breadth of adoption of the proposed Community Standard. For example, are the implementations widely used in the geospatial community or subsets of the community? Are implementations limited, but used by most organizations that need the capabilities of the proposed Community Standard? Does the proposed Community Standard serve an emerging part of the geospatial community?
////

The referenced implementations are amongst the most widely used open source software or libraries of their kinds, which is the primary reason this standard was selected by the GeoSPARQL SWG.

== Public availability

Is the proposed Community standard currently publicly available?

* [x] Yes
* [ ] No

URL: https://github.com/postgis/postgis/blob/master/doc/ZMSgeoms.txt.

== Supporting OGC Members

The Submitting OGC Members for this work item are:

[start=1]
. Geoscape Australia
. Oracle (Voting Member)
. Kurrawong AI
. Defence Science & Technology Labs (DSTL) (Voting Member)

== Intellectual Property Rights

Will the contributor retain intellectual property rights?

* [x] Yes
* [ ] No

If yes, the contributor will be required to work with OGC staff to properly attribute the submitter’s intellectual property rights.

If no, the contributor will assign intellectual property rights to the OGC.
