= GeoSPARQL 1.0 Profile

This is a 'profile declaration' for the GeoSPARQL 1.0 specification (standard) as originally published in 2012. It describes the multiple parts of the specification and how the standard relates to other standards. It is formulated according to the Profiles Vocabulary.

NOTE: Profile declarations are used to allow data to identify specifications in a way that allows data to make conformance claims to them - a broader conformance claim than that made to individual 'conformance classes' that are commonly found in recent OGC specifications. Profile declarations are also used to describe and relate the often multiple parts of specifications: ontologies, specification 'documents', vocabularies, validators and so on. This declaration describes where those parts are, what form (format) they take, what information models they implement and what roles they play.

== Profile Resources

[cols="1,2,1,1,1,1"]
|===
| Title | Description | Format | Conforms To | Role | Link

| GeoSPARQL Functions & Rules vocabulary | all GeoSPARQL functions and rules presented as a SKOS vocabulary | text/turtle | https://www.w3.org/TR/skos-reference/ | Vocabulary | http://defs-dev.opengis.net/static/definitions/conceptschemes/functions_geosparql.ttl
| GeoSPARQL Specification Document as a PDF | None | application/pdf |  | Specification | https://portal.ogc.org/files/?artifact_id=47664
| GeoSPARQL Ontology | The GeoSPARQL 1.1 ontology in RDF (turtle) | application/rdf+xml | http://www.w3.org/TR/owl2-rdf-based-semantics/ | None | http://schemas.opengis.net/geosparql/1.0/geosparql_vocab_all.rdf
|===
