== Scope of Work

This Scope of Work is motivated by outstanding change requests for the existing OGC GeoSPARQL standard and a revision is required. The change requests have been submitted to the OGC Standards Tracker. Initially, review and prioritization of these change requests will be conducted by the SWG followed by work to create a candidate revision of the standard for public review. During and after public review, the SWG will consider submissions to further enhance GeoSPARQL and alignments with it to other, related, standards. A final GeoSPARQL revision will then be submitted for consideration by the OGC as a new or revised standard.


=== Statement of relationship of planned work to the current OGC standards baseline

The scope of this proposed SWG is only the revision of the current GeoSPARQL standard. This revision may result in both specific enhancements - to cater for community requirements - and also a revision of the "upper ontology" structuring of GeoSPARQL - to provide direction for future enhancements and alignments with other ontologies.

There are possible alignments of a future GeoSPARQL to other ontologies, perhaps the W3C and OGC's Time ontology in OWL.

There are possible relationships between a future GeoSPARQL and more spatial referencing systems than were considered by GeoSPARQL 1.0, like Discrete Global Grid Systems (DGGSs).

There are possible alignments of a future GeoSPARQL with advancements in Coordinate Reference Systems that will need to be considered in consultation with related working groups.

=== What is Out of Scope?

Out of scope is work that does not result in a revised GeoSPARQL standard. This includes investigation of property graphs, though coordination with property graph related working groups will be undertaken.


=== Specific Existing Work Used as Starting Point

* GeoSPARQL (https://www.opengeospatial.org/standards/geosparql)

* GeoSemantics DWG's White Paper on "OGC Benefits of Representing Spatial Data Using Semantic and Graph Technologies" (https://github.com/opengeospatial/geosemantics-dwg/tree/master/white_paper)

GeoSemantics DWG's suggestions for spatial ontology investigations:

* OGC & W3C's Time Ontology in OWL [3]

* CRMgeo v1.4 (https://github.com/erlangen-crm/ecrmgeo)

* GeoSPARQL Extensions Ontology [5]

* ISO's TC-211 Group on Ontology Management ontology repository (https://github.com/ISO-TC211/GOM/)

* Geometry Metadata Ontology (GOM) [6]

* Ontology for Managing Geometry (OMG) [7]

* File Ontology for Geometry formats (FOG) [8]

* NSG Enterprise Ontology (NEO) [9]

=== Is This a Persistent SWG

[x] YES

[ ] NO

=== When can the SWG be Inactivated

The SWG can be inactivated once the final standard has been developed and change requests become minimal or not applicable for consideration. The SWG can be re-activated at any time.
