== Description of deliverables

This SWG aims to revise and extend the GeoSPARQL standard.

Initial goals of the working group are to incorporate several major and minor extension proposals to the GeoSPARQL standard which have been summarized in a published OGC white paper and were collected on the OGC Standards Tracker.

Some of the proposed extensions include support for additional geospatial literal types, and support for coverage data, spatiotemporal representations and different semantic representations of CRS.

To organize the working group we propose the following preliminary schedule.

 * 1st meeting: Review and prioritization of issues submitted to the OGC Standards Tracker

 * Next months: Work towards a candidate standard for public review

 * Release of the candidate standard for public review

 * Iterative approach to improve the candidate standard by considering comments and further upcoming issues

 * Final revision of the standard

 * Recommendation of the final standard to the OGC


=== Initial Deliverables

The initial deliverables are based on the initial selection and prioritization of issues from the OGC Standards tracker. This selection will be determined in the first meetings of the working group and subsequently updated in this working group charter.

After deciding on the initial issues to be worked on, this SWG will publish a roadmap to be used to manage scope and timeframes for delivery of a modular revision of the GeoSPARQL standard.


=== Additional SWG Tasks

Additional SWG tasks will be added iteratively when new change requests and issues become apparent or gain priority. The SWG is planned as a long term working group so that new change requests may arise during the development of the initial deliverables. These will be prioritized and periodically classified as additional SWG tasks.
