== Business Value Proposition

////
This section provides a statement describing the value of this standards activity in relation to the OGC Membership, the geospatial community, and the wider IT community. This statement can be in terms of the interoperability problem being solved, processing Change requests to meet market (and Member requirements), a policy requirement and/or some other business value proposition. The proposition described in this section does not have to be in economic terms.
////
Since the release of GeoSPARQL [1] in 2012, there has been growth of both the Semantic Web and spatial information represented in Semantic Web [2] form. GeoSPARQL is widely used for spatial Semantic Web data and systems so it is clearly a success.

As with many standards/systems that are developed and then see wide use, suggestions for enhancements and extensions are made by users as they extend beyond the domain of the original standard's creators. Perhaps also, new knowledge or technical developments since the initial standard allow for new possibilities.

=== Value to the OGC
To maintain its place as the premier way of representing spatial information in the Semantic Web, a major update of GeoSPARQL will need to be created to incorporate both ontology constructs that users have found useful but have had to implement elsewhere and, optimally, constructs that will allow for formulaic future extension and the use of GeoSPARQL with related domain ontologies, perhaps such as the OGC & W3C's Time ontology in OWL [3]. If it can do this, the GeoSPARQL update will assist the OGC in "advancing geospatial location information and services" for the Semantic Web and the related mechanics of Linked Data that are growing in their use.

=== Value to the OGC Membership
OGC members themselves are increasingly using Semantic Web approaches to answer questions involving the Internet and Internet data. For example, recent Testbed activity (Testbed 16: Discrete Global Grid System [4]) is considering RDF back-ends and data exchange mechanisms for DGGS implementations. Enhancing the OGC's own standard for spatial Semantic Web data will therefore assist OGC members to make the most use of spatial + Semantic Web. OGC members will not have to implement their own, non-standard, handling of spatial concept representation not handled by GeoSPARQL.

=== Value to the geospatial community
The larger geospatial community will benefit from the OGC continuing to lead in the spatial + Semantic Web space as this will provide a cohesiveness of approach (standardization) to spatial + Semantic Web, and also the sharing of best practices where community members can learn from early implementers. Also, without this GeoSPARQL enhancement, the geospatial community using the Semantic Web will not have a clear indication that there is a lead body in this field (the OGC) and thus no obvious place to go for community discussion. Seen negatively: if the OGC is not seen to be continuing its leadership in the growth area of the Semantic Web, it will erode its member base as geospatial community members look elsewhere for leadership.

=== Value to the wider IT community
This wider IT community is growing its volumes of spatial data as spatially-enabled devices and services continue to grow. The wider IT community is also expanding its use of the Semantic Web with large-scale initiatives such as schema.org, applying Semantic Web approaches to large numbers of Internet information publishers. Due to these two trends, the combination of spatial + Semantic Web is becoming more mainstream. This means the OGC can potentially grow its membership as new wider IT community members become spatial + Semantic Web community members.
