[abstract]
== Abstract 

GeoSPARQL contains a small spatial domain OWL ontology that allow literal representations of geometries to be associated with spatial features and for features to be associated with other features using spatial relations.

GeoSPARQL also contains SPARQL extension function definitions that can be used to calculate relations between spatial objects.

Several other supporting assets are also contained within GeoSPARQL such as vocabularies of Simple Feature types and data validators.

[.text-center]
====
The namespace for the GeoSPARQL ontology is `http://www.opengis.net/ont/geosparql#`

The suggested prefix for this namespace is `geo`

The namespace for the GeoSPARQL functions is `http://www.opengis.net/def/function/geosparql/`

The suggested prefix for this namespace is `geof`

The namespace for the GeoSPARQL rules is `http://www.opengis.net/def/rule/geosparql/`

The suggested prefix for this namespace is `geor`
====

[.preface]
== Preface
The OGC GeoSPARQL Standard defines:

* A formal _profile_;
* **this document;**
* A core RDF/OWL ontology for geographic information representation;
* A set of SPARQL extension functions;
* A Functions & Rules vocabulary, derived from the ontology;
* A Simple Features geometry types vocabulary;
* SHACL shapes for RDF data validation.

This document authoritatively defines many of the Standard's elements, including the ontology classes and properties, SPARQL functions, and function and rule vocabulary concepts. Complete descriptions of the Standard's parts and their roles are given in the Introduction in the section <<GeoSPARQL Standard structure>>.

[.preface]
== Keywords

Open Geospatial Consortium, OGC, spatial, ontology, Knowledge Graph, Semantic Web, Linked Data, RDF, Resource Description Framework, Web Ontology Language, OWL, SPARQL, Simple Features, feature, geometry

[.preface]
== Clarifications

* The terms <<spatial reference system, Spatial Reference System (SRS)>> and <<coordinate reference system, Coordinate Reference System (CRS)>> are no longer interchangeable. Spatial Reference System is now taken to be a broader category than Coordinate Reference System. These are defined in the <<Terms and definitions>> section.
* Class definitions were updated to be more self-contained and easier to understand for people without a background in geoinformatics. The definitions are no longer dependent on other standards' definitions, only informed by them.
* A section was added on <<Recommendation for specification of units of measurement,the specification of units of measurement>>.
* A section was added on the <<Influence of Coordinate Reference Systems on geometric computations>>.

[.preface]
== v. Changes to the OGC® Abstract Specification
The OGC® Abstract Specification does not require changes to accommodate this OGC® standard.

== Foreword
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights. However, to date, no such rights have been claimed or identified.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the specification set forth in this document, and to provide supporting documentation.


[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
[%header, cols="1, 3"]
|===
|Contact | Company
| Simon J.D. Cox | CSIRO
| Panagiotis (Peter) A. Vretanos | Cubewerx Inc.
| Paul Cripps | DSTL
| Linda van den Brink | Geonovum
| Joseph Abhayaratna | Geoscape Australia
| Irina Bastrakova | Geoscience Australia
| Timo Homburg | Mainz University Of Applied Sciences
| Matthew Perry | Oracle America
| Nicholas J. Car | SURROUND Australia Pty Ltd.
|===

[.preface]
== Submitting Organizations

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* CSIRO
* Cubewerx Inc
* Defence Science and Technology Laboratory (DSTL)
* Geonovum
* Geoscape Australia
* Geoscience Australia
* Mainz University Of Applied Sciences
* Oracle America
* OSGeo
* SURROUND Australia Pty Ltd.



