[bibliography,normative=true]
== Normative references

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document. For more recent dated references, subsequent amendments to, or revisions of, any of these publications do not apply. However, parties to agreements based on this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below. For undated references, the latest edition of the normative document referred to applies.

* [[[WKT, ISO 19125-1:2004]]] {blank}
* [[[ISO_19156:2011, ISO 19156:2011]]] {blank}
* [[[GML, OGC 07-036]]] {blank}
* [[[IRI, IETF RFC 3987]]] {blank}
* [[[OWL2, W3C REC-owl2-overview-20121211]]] {blank}
* [[[RDFC, W3C REC-rdf11-concepts-20140225]]] {blank}
* [[[RDFSC, W3C REC-rdf-schema-20140225]]] {blank}
* [[[RIF, W3C REC-rif-core-20130205]]] {blank}
* [[[SPQL, W3C REC-sparql11-query-20130321]]] {blank}
* [[[SPQLE, W3C REC-sparql11-entailment-20130321]]] {blank}
* [[[SPQLP, W3C REC-sparql11-protocol-20130321]]] {blank}
* [[[SPQLX, W3C REC-rdf-sparql-XMLres-20130321]]] {blank}
* [[[SPQLJ, W3C REC-sparql11-results-json-20130321]]] {blank}
