== Conventions

=== Symbols and abbreviated terms

In this specification, the following common acronyms are used:

[%unnumbered]
[frame=none, grid=none, cols="1, 6"]
|===
| CRS | Coordinate Reference System
| DGGS | Discrete Global Grid System
| GeoJSON | Geographic JavaScript Object Notation
| GFM | General Feature Model (as defined in ISO 19109)
| GIS | Geographic Information System
| GML | Geography Markup Language
| IRI | Internationalized Resource Identifier
| KML | Keyhole Markup Language
| OWL | OWL 2 Web Ontology Language
| RCC | Region Connection Calculus
| RDF | Resource Description Framework
| RDFS | RDF Schema
| RIF | Rule Interchange Format
| SPARQL | SPARQL Protocol and RDF Query Language
| SQL | Structured Query Language
| SRS | Spatial Reference System
| URI | Universal Resource Identifier
| WKT | Well Known Text (as defined by Simple Features or ISO 19125) 
| W3C | World Wide Web Consortium (https://www.w3.org)
| XML | Extensible Markup Language
|===

=== Namespaces

The following IRI namespace prefixes are used throughout this document:

[%unnumbered]
[frame=none, grid=none, cols="1, 6"]
|===
| dcat: | http://www.w3.org/ns/dcat#
| dcterms: | http://purl.org/dc/terms/
| ex: | http://example.com/
| geo: | http://www.opengis.net/ont/geosparql#
| geof: | http://www.opengis.net/def/function/geosparql/
| geor: | http://www.opengis.net/def/rule/geosparql/
| gml: | http://www.opengis.net/ont/gml#
| my: | http://example.org/ApplicationSchema#
| ogc: | http://www.opengis.net/
| owl: | http://www.w3.org/2002/07/owl#
| rdf: | http://www.w3.org/1999/02/22-rdf-syntax-ns# 
| rdfs: | http://www.w3.org/2000/01/rdf-schema#
| sf: | http://www.opengis.net/ont/sf#
| skos: | http://www.w3.org/2004/02/skos/core#
| xsd: | http://www.w3.org/2001/XMLSchema#
|===

=== Placeholder IRIs

All of these namespace prefixes in the previous section resolve to resources that contain their namespace content except for `eg:` (`http://example.com/`), which is used just for examples, and `ogc:` (`http://www.opengis.net/`), which is used in requirement specifications as a placeholder for the geometry literal serialization used in a fully-qualified conformance class, e.g. http://www.opengis.net/ont/geosparql#wktLiteral[`+<http://www.opengis.net/ont/geosparql#wktLiteral>+`].

=== Data Types for Spatial Aggregate Functions

In this specification we use the placeholder URI ogc:geomLiteral to describe any geometry literal which is defined in this specification.
To express a list of such literals, for example as input parameters for spatial aggregate functions, we use the notation ogc:geomLiteral[].
We do not define the order of ogc:geomLiteral[]. The order is to be determined by implementers.

=== RDF Serializations

Three RDF serializations are used in this document. Terse RDF Triple Language (turtle) <<TURTLE>> is used for RDF snippets placed within the main body of the document, and turtle, JSON-LD <<JSON-LD>> & RDF/XML <<RDFXML>> is used for the examples in <<GeoSPARQL Examples>>.

