== Topology Vocabulary Extension

This clause establishes the _Topology Vocabulary Extension_ parameterized Requirements class. The IRI base is `/req/topology-vocab-extension`, which has a single corresponding Conformance Class _Topology Vocabulary Extension_, with IRI `/conf/topology-vocab-extension`. This Requirements class defines a vocabulary for asserting and querying topological relations between spatial objects. The class is parameterized so that different families of topological relations may be used, such as RCC8 and Egenhofer. These relations are generalized so that they may connect features as well as geometries.

[requirements_class,identifier="/req/topology-vocab-extension",subject="Implementation Specification"]
.Topology Vocabulary Extension
====
requirement:: /req/topology-vocab-extension/sf-spatial-relations
requirement:: /req/topology-vocab-extension/eh-spatial-relations
requirement:: /req/topology-vocab-extension/rcc8-spatial-relations
====

A Dimensionally Extended 9-Intersection Model <<DE-9IM>> pattern, which specifies the spatial dimension of the intersections of the interiors, boundaries and exteriors of two geometric objects, is used to describe each spatial relation. Possible pattern values are `-1 (empty)`, `0, 1, 2, T (true) = {0, 1, 2}`, `F (false) = {-1}`, `* (don't care) = {-1, 0, 1, 2}`. In the following descriptions, the notation `X/Y` is used to denote applying a spatial relation to geometry types `X` and `Y` (i.e., `x` _relation_ `y` where `x` is of type `X` and `y` is of type `Y`). The symbol `P` is used for 0-dimensional geometries (e.g. points). The symbol `L` is used for 1-dimensional geometries (e.g. lines), and the symbol `A` is used for 2-dimensional geometries (e.g. polygons). Consult the Simple Features specification <<OGCSFACA>> <<ISO19125-1>> for a more detailed description of DE-9IM intersection patterns.

=== Parameters

The following parameter is defined for the _Topology Vocabulary Extension_ Requirements.

*relation_family*: Specifies the set of topological spatial relations to support.

=== Simple Features Relation Family

This clause defines Requirements for the _Simple Features_ relation family.

[#req_topology-vocab-extension_sf-spatial-relations]
[requirement,identifier="/req/topology-vocab-extension/sf-spatial-relations"]
.Simple Feature Spatial Relations
====
Implementations shall allow the properties 
<<Property: geo:sfEquals, `geo:sfEquals`>>, 
<<Property: geo:sfDisjoint, `geo:sfDisjoint`>>, 
<<Property: geo:sfIntersects, `geo:sfIntersects`>>, 
<<Property: geo:sfTouches, `geo:sfTouches`>>, 
<<Property: geo:sfCrosses, `geo:sfCrosses`>>, 
<<Property: geo:sfWithin, `geo:sfWithin`>>, 
<<Property: geo:sfContains, `geo:sfContains`>> and 
<<Property: geo:sfOverlaps, `geo:sfOverlaps`>> 
to be used in SPARQL graph patterns.
====

Topological relations in the _Simple Features_ family are summarized in <<sf_relations>>. Multi-row intersection patterns should be interpreted as a logical `OR` of each row.

[[sf_relations]]
.Simple Features Topological Relations
|===
|Relation Name | Relation IRI | Domain/Range | Applies To Geometry Types | DE-9IM Intersection Pattern

|[[geo:sfEquals]]equals | http://www.opengis.net/ont/geosparql#sfEquals[`geo:sfEquals`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `(TFFFTFFFT)`
|[[geo:sfDisjoint]]disjoint | http://www.opengis.net/ont/geosparql#sfDisjoint[`geo:sfDisjoint`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `+(FF**FF****)+`
|[[geo:sfIntersects]]intersects | http://www.opengis.net/ont/geosparql#sfIntersects[`geo:sfIntersects`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `+(T******** *T******* ***T***** ****T****)+`
|[[geo:sfTouches]]touches | http://www.opengis.net/ont/geosparql#sfTouches[`geo:sfTouches`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All except P/P` | `+(FT******* F**T***** F***T****)+`
|[[geo:sfWithin]]within | http://www.opengis.net/ont/geosparql#sfWithin[`geo:sfWithin`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `+(T*F**F***)+`
|[[geo:sfContains]]contains | http://www.opengis.net/ont/geosparql#sfContains[`geo:sfContains`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `+(T*****FF*)+`
|[[geo:sfOoverlaps]]overlaps | http://www.opengis.net/ont/geosparql#sfOverlaps[`geo:sfOverlaps`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `A/A, P/P, L/L` | `+(T*T***T**) for A/A, P/P+`; `+(1*T***T**) for L/L+`
|[[geo:sfCrosses]]crosses | http://www.opengis.net/ont/geosparql#sfCrosses[`geo:sfCrosses`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `P/L, P/A, L/A, L/L` | `+(T*T***T**) for P/L, P/A,
L/A+`; `+(0********) for L/L+`
|===

=== Egenhofer Relation Family

This clause defines Requirements for the 9-intersection model for the binary topological relations (_Egenhofer_) relation family. The reader should consult references <<FORMAL>> and <<CATEG>> for a more detailed discussion of _Egenhofer_ relations.

[#req_topology-vocab-extension_eh-spatial-relations]
[requirement,identifier="/req/topology-vocab-extension/eh-spatial-relations"]
.Egenhofer Spatial Relations
====
Implementations shall allow the properties 
<<Property: geo:ehEquals, `geo:ehEquals`>>, 
<<Property: geo:ehDisjoint, `geo:ehDisjoint`>>, 
<<Property: geo:ehMeet, `geo:ehMeet`>>, 
<<Property: geo:ehOverlap, `geo:ehOverlap`>>, 
<<Property: geo:ehCovers, `geo:ehCovers`>>, 
<<Property: geo:ehCoveredBy, `geo:ehCoveredBy`>>, 
<<Property: geo:ehInside, `geo:ehInside`>> and
<<Property: geo:ehContains, `geo:ehContains`>> 
to be used in SPARQL graph patterns.
====

Topological relations in the _Egenhofer_ family are summarized in <<egenhofer_relations>>. Multi-row intersection patterns should be interpreted as a logical `OR` of each row.

[[egenhofer_relations]]
.Egenhofer Topological Relations
|===
|Relation Name | Relation IRI | Domain/Range | Applies To Geometry Types | DE-9IM Intersection Pattern

|[[geo:ehEquals]]equals | http://www.opengis.net/ont/geosparql#ehEquals[`geo:ehEquals`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `(TFFFTFFFT)`
|[[geo:ehDisjoint]]disjoint | http://www.opengis.net/ont/geosparql#ehDisjoint[`geo:ehDisjoint`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `+(FF*FF****)+`
|[[geo:ehMeet]]meet | http://www.opengis.net/ont/geosparql#ehMeet[`geo:ehMeet`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All except P/P` | `+(FT******* F**T***** F***T****)+`
|[[geo:ehOverlap]]overlap | http://www.opengis.net/ont/geosparql#ehOverlap[`geo:ehOverlap`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `+(T*T***T**)+`
|[[geo:ehCovers]]covers | http://www.opengis.net/ont/geosparql#ehCovers[`geo:ehCovers`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `A/A, A/L, L/L` | `+(T*TFT*FF*)+`
|[[geo:ehCoveredBy]]covered by | http://www.opengis.net/ont/geosparql#ehCoveredBy[`geo:ehCoveredBy`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `A/A, L/A, L/L` | `+(TFF*TFT**)+`
|[[geo:ehInside]]inside | http://www.opengis.net/ont/geosparql#ehInside[`geo:ehInside`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `+(TFF*FFT**)+`
|[[geo:ehContains]]contains | http://www.opengis.net/ont/geosparql#ehContains[`geo:ehContains`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>> | `All` | `+(T*TFF*FF*)+`
|===

=== RCC8 Relation Family

This clause defines Requirements for the region connection calculus basic 8 (_RCC8_) relation family. The reader should consult references <<QUAL>> and <<LOGIC>> for a more detailed discussion of _RCC8_ relations.

[#req_topology-vocab-extension_rcc8-spatial-relations]
[requirement,identifier="/req/topology-vocab-extension/rcc8-spatial-relations"]
.RCC8 Spatial Relations
====
Implementations shall allow the properties 
<<Property: geo:rcc8eq, `geo:rcc8eq`>>, 
<<Property: geo:rcc8dc, `geo:rcc8dc`>>, 
<<Property: geo:rcc8ec, `geo:rcc8ec`>>, 
<<Property: geo:rcc8po, `geo:rcc8po`>>, 
<<Property: geo:rcc8tppi, `geo:rcc8tppi`>>, 
<<Property: geo:rcc8tpp, `geo:rcc8tpp`>>, 
<<Property: geo:rcc8ntpp, `geo:rcc8ntpp`>>, 
<<Property: geo:rcc8ntppi, `geo:rcc8ntppi`>> 
to be used in SPARQL graph patterns.
====

Topological relations in the _RCC8_ family are summarized in <<rcc8_relations>>.

[[rcc8_relations]]
.RCC8 Topological Relations
|===
|Relation Name | Relation IRI | Domain/Range | Applies To Geometry Types | DE-9IM Intersection Pattern

|[[geo:rcc8eq]]equals | http://www.opengis.net/ont/geosparql#rcc8eq[`geo:rcc8eq`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>>  | `A/A` | `(TFFFTFFFT)`
|[[geo:rcc8dc]]disconnected | http://www.opengis.net/ont/geosparql#rcc8dc[`geo:rcc8dc`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>>  | `A/A` | `(FFTFFTTTT)`
|[[geo:rcc8ec]]externally connected | http://www.opengis.net/ont/geosparql#rcc8ec[`geo:rcc8ec`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>>  | `A/A` | `(FFTFTTTTT)`
|[[geo:rcc8po]]partially overlapping | http://www.opengis.net/ont/geosparql#rcc8po[`geo:rcc8po`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>>  | `A/A` | `(TTTTTTTTT)`
|[[geo:rcc8tppi]]tangential proper part inverse | http://www.opengis.net/ont/geosparql#rcc8tppi[`geo:rcc8tppi`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>>  | `A/A`  | `(TTTFTTFFT)`
|[[geo:rcc8tpp]]tangential proper part | http://www.opengis.net/ont/geosparql#rcc8tpp[`geo:rcc8tpp`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>>  | `A/A` | `(TFFTTFTTT)`
|[[geo:rcc8ntpp]]non-tangential proper part | http://www.opengis.net/ont/geosparql#rcc8ntpp[`geo:rcc8ntpp`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>>  | `A/A` | `(TFFTFFTTT)`
|[[geo:rcc8ntppi]]non-tangential proper part inverse | http://www.opengis.net/ont/geosparql#rcc8ntppi[`geo:rcc8ntppi`] | <<Class: geo:SpatialObject, `geo:SpatialObject`>>  | `A/A` | `(TTTFFTFFT)`
|===


=== Equivalent RCC8, Egenhofer and Simple Features Topological Relations

<<relation_equivalences>> summarizes the equivalences between _Egenhofer_, _RCC8_ and _Simple Features_ spatial relations for closed, non-empty regions. The symbol `+` denotes logical `OR`, and the symbol `¬` denotes negation.

[#relation_equivalences]
.Equivalent Simple Features, RCC8 and Egenhofer relations
|===
|Simple Features | RCC8 | Egenhofer

|equals | equals | equals
|disjoint | disconnected | disjoint
|intersects | `¬` disconnected | `¬` disjoint
|touches | externally connected | meet
|within | non-tangential proper part `+` tangential proper part | inside `+` coveredBy
|contains | non-tangential proper part inverse `+` tangential proper part inverse | contains `+` covers
|overlaps | partially overlapping | overlap
|===
