== Geometry 3D Extension

This clause defines the _Geometry 3D Extension_ parameterized Requirements class with the base IRI `/req/geometry3d-extension`. There is a single corresponding conformance class _Geometry 3D Extension_, with the IRI `/conf/geometry3d-extension`. These Requirements define a vocabulary for asserting and querying information about geometry data, and define query functions for operating on geometry data.

[requirements_class,identifier="/req/geometry3d-extension",subject="Implementation Specification"]
.Geometry Extension
====
requirement:: /req/geometry-extension/geometry3d-class
requirement:: /req/geometry-extension/geometry3d-collection-class
requirement:: /req/geometry-extension/feature-properties
requirement:: /req/geometry-extension/geometry-properties
requirement:: /req/geometry-extension/query-functions
requirement:: /req/geometry-extension/srid-function
requirement:: /req/geometry-extension/sa-functions
====

As part of the vocabulary, RDFS datatypes are defined for encoding detailed geometry information as a literal value. A literal representation of a geometry is needed so that geometric values may be treated as a single unit. Such a representation allows geometries to be passed to external functions for computations and to be returned from a query.

=== Rationale

Other schemes for encoding simple geometry data in RDF have been implemented. The W3C Basic Geo vocabularyfootnote:[http://www.w3.org/2003/01/geo/] was an early (2003) RDF vocabulary for "representing lat(itude), long(itude) and other information about spatially-located things. Geo specifies WGS84 as the reference datum". Further, many widely used Semantic Web vocabularies contain some spatial data support. For example, _Dublin Core Terms_ provides a _Location_ classfootnote:[http://purl.org/dc/terms/Location] for "A spatial region or named place." and _schema.org_ provides a number of spatial object and geometry classes, such as `GeoCoordinates` footnote:[https://schema.org/GeoCoordinates] and `GeoShape` footnote:[https://schema.org/GeoShape]. 

Many vocabularies such as the above provide little specific support for detailed geometries and only specify using the WGS84 Coordinate Reference System (CRS).

Since the first version of GeoSPARQL, many ontologies have imported GeoSPARQL. For example, the _ISA Programme Location Core Vocabulary_ footnote:[https://www.w3.org/ns/locn] whose usage notes provide examples containing GeoSPARQL literals and the use of GeoSPARQL's "geometry class". The W3C's more recent _Data Catalog Vocabulary, Version 2_ (DCAT2) standardfootnote:[https://www.w3.org/TR/vocab-dcat/#spatial-properties] similarly contains usage notes for `geometry`, `bbox` and other properties that suggest the use of GeoSPARQL literals.

Some of the properties defined in these vocabularies, such as DCAT2's https://www.w3.org/TR/vocab-dcat-2/#Property:dataset_spatial_resolution[`dcat:spatialResolution`] have motivated the inclusion of new properties in this version of GeoSPARQL. In this case the equivalent property is <<Property: geo:hasSpatialResolution, `geo:hasSpatialResolution`>>. The GeoSPARQL 1.1 Standards Working Group charter <<CHARTER>> contains references to a number of vocabularies/ontologies that were influential in the generation of this version of GeoSPARQL.

=== GeoSPARQL and Simple Features 3D (SFA-CA)

The GeoSPARQL Geometry Extension is largely based on the ISO/OGC Simple Features Access - Common Architecture (SFA-CA) Standard <<OGC06-103r4>>. Contrary to what the name may imply, SFA-CA is about Geometry and not about Features. SFA-CA describes simple geometry, meaning that geometric shapes are based on points and straight lines (linear interpolations) between points. Within a single Geometry, these lines may not cross.

Neither GeoSPARQL nor SFA-CA support full three-dimensional geometry. Coordinates may be three-dimensional, which means that points may have a Z-coordinate next to an X- and Y-coordinate. The Z-coordinate then holds the value of height or depth. However, lines or surfaces can only have one Z value for any explicit or interpolated X,Y pair. This approach is often referred to as 2.5 dimensional geometry. Geometric functions working with Geometries that have Z values will ignore Z values in calculations and first project geometry onto the Z=0 level.

SFA-CA also describes M coordinate values that may be part of geometry encodings. The M value represents a measure, a value that can be used in information systems that support linear referencing. GeoSPARQL at the moment does not support linear referencing. Like Z values in coordinates, M values are to be ignored.

SFA-CA specifies a class hierarchy for Geometry. Although these classes are not part of the GeoSPARQL ontology, the GeoSPARQL SWG does publish a vocabulary of Simple Features geometry: http://www.opengis.net/ont/sf. Geometry types defined in this vocabulary can be considered safe to use with GeoSPARQL. The two Geometry serializations that were specified in GeoSPARQL 1.0, WKT and GML, fully support all SFA-CA geometry types. However, the two Geometry serializations that were introduced in GeoSPARQL 1.1 do not. Some SFA-CA geometry types are not supported by either the OGC KML <<OGC12-007r2>> or the GeoJSON format. For example, neither KML nor GeoJSON support the Triangulated Integrated Network (TIN) or Triangle geometry types.

=== Recommendation for units of measure

For geometric data to be interpreted and used correctly, the units of measure should be known. Typically, the particular Spatial Reference System (SRS) that is associated with a Geometry instance will specify a unit of measurement. However, some elements of GeoSPARQL allow arbitrary units of distance to be used, for example the property <<Property: geo:hasSpatialResolution, `geo:hasSpatialResolution`>> or the function <<Function: geof:buffer, `geof:buffer`>>. In those cases it is advisable to make use of a well-known web vocabulary for units of measurement. Making the unit of measurement explicit will improve data interoperability. The recommended vocabulary for units of measurement for GeoSPARQL is the _Quantities, Units, Dimensions and Types (QUDT)_ ontologyfootnote:[http://www.qudt.org] but others may be used, as long as they are well-described.

=== Influence of Reference Systems on computations

A Geometry object consists of a set of coordinates and a specification on how the coordinates should be interpreted. This specification is known as a Spatial reference System (SRS). Taken together, coordinates and SRS allow performing computations on Geometry objects. For example, sizes can be calculated or new Geometry objects can be created. Some Spatial Reference Systems describe a two-dimensional flat space. In that case, coordinates are understood to be Cartesian, and Cartesian geometric computations can be performed. But Spatial Reference Systems can describe other types of spaces, to which Cartesian computations are not applicable. For example, if CRS http://www.opengis.net/def/crs/OGC/1.3/CRS84[`+<http://www.opengis.net/def/crs/OGC/1.3/CRS84>+`] is used, coordinates are to be interpreted as decimal degrees of latitude and longitude, designating positions on a spheroid. The distance between two points using this CRS is different from the distance between two points that have the same coordinates but are based on a Cartesian CRS or other SRS.

To avoid erroneous computations involving Geometry, data publishers are recommended to clearly indicate the type of space that is described by the SRS.

=== Parameters

The following parameters are defined for the _Geometry Extension_ Requirements.

serialization:: Specifies the serialization standard to use when generating geometry literals as well as the supported geometry types.

[NOTE,keep-separate=true]
====
A serialization strongly affects the geometry conceptualization. The WKT serialization aligns the geometry types with _ISO 19125 Simple Features_ <<OGC06-103r4>> <<ISO19125-1>>; the GML serialization aligns the geometry types with _ISO 19107 Spatial Schema_ <<ISO19107>>.
====

version:: Specifies the version of the serialization format used.

=== Geometry 3D Class

A single root geometry class is defined: <<Class: geo:Geometry, `geo:Geometry`>>. In addition, properties are defined for describing geometry data and for associating geometries with features.

One container class is defined: <<Class: geo:GeometryCollection, Geometry Collection>>. 

==== Class: geo:Geometry

The class http://www.opengis.net/ont/geosparql#Geometry[`geo:Geometry`] is conceptually derived from UML class `Geometry` in <<ISO19107>> which is that standard's "root class of the geometric object taxonomy and supports interfaces common to all geographically referenced geometric objects". `geo:Geometry` is defined by the following:

[%unnumbered]
[source,turtle]
----
geo:3DGeometry 
    a rdfs:Class, owl:Class ;
    rdfs:isDefinedBy geo: ; 
    skos:prefLabel "Geometry"@en ;
    rdfs:subClassOf geo:Geometry ;
    owl:disjointWith geo:Feature;
    skos:definition "A geometry with at least three dimensions."@en ;
    skos:note "Geometry can be used as a representation of the shape, extent or 
              location of a Feature and may exist as a self-contained entity."@en ;
.
----

[[req_geometry-extension_3dgeometry-class]]
[requirement,identifier="/req/geometry-extension/geometry-class"]
.3DGeometry Class
====
Implementations shall allow the RDFS class <<Class: geo:3DGeometry, `geo:3DGeometry`>> to be used in SPARQL graph patterns.
====

[[geometry_properties]]
=== Standard Properties for geo:3DGeometry

Properties are defined for describing geometry metadata.

[requirement,identifier="/req/geometry-extension/geometry-properties"]
.Geometry 3D Properties
====
Implementations shall allow the properties 
<<Property: geo:textures, `geo:textures`>>, 
<<Property: geo:vertices, `geo:vertices`>>, 
<<Property: geo:faces, `geo:faces`>>, 
<<Property: geo:rotation, `geo:rotation`>>, 
<<Property: geo:position, `geo:position`>>, 
<<Property: geo:scale, `geo:scale`>> and
<<Property: geo:translation, `geo:translation`>> 
to be used in SPARQL graph patterns.
====

==== Property: geo:textures

The property http://www.opengis.net/ont/geosparql#textures[`geo:textures`] links one or many surfaces to a texture that covers, the surface or part of its surface. Textures may be linked using a property like foaf image.

[%unnumbered]
[source,turtle]
----
geo:dimension 
    a rdf:Property, owl:ObjectProperty ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "dimension"@en ;
    skos:definition "One or many texture instances linked to a Geometry object."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range sf3d:Texture ;
.
----

==== Property: geo:vertices

The property http://www.opengis.net/ont/geosparql#vertices[`geo:vertices`] is defined to link a Geometry object to the dimension of direct positions (coordinate tuples) used in the Geometry's definition.

[%unnumbered]
[source,turtle]
----
geo:coordinateDimension 
    a rdf:Property, owl:DatatypeProperty;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "coordinate dimension"@en ;
    skos:definition "The number of measurements or axes needed to describe the
                    position of this Geometry in a coordinate system."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range xsd:integer ;
.
----

[[query_functions]]
=== Non-topological Query Functions

This Requirements class defines SPARQL functions for performing non-topological spatial operations on 3D geometries.

[[req_geometry_extension_query-functions-non-sf]]
[requirement,identifier="/req/geometry-extension/query-functions-non-sf"]
.Non-topological Query Functions (Non Simple Features)
====
Implementations shall support the functions 
<<Function: geof:metricLength, `geof:metricLength`>>
as SPARQL extension functions which are defined in this standard, for non-DGGS geometry literals.
====

////

Functions from this Requirements class are listed below, alphabetically.

==== Function notes
These notes apply to all of the following functions in this section.

An invocation of any of the following functions with invalid arguments produces an error. An invalid argument includes any of the following:

* An argument of an unexpected type
* An invalid geometry literal value
* A non-fitting geometry type for the given function
* A geometry literal from a spatial reference system that is incompatible with the spatial reference system used for calculations
* An invalid unit IRI

A more detailed description of expected inputs and expected outputs of the given functions is shown in Annex B.

Unless otherwise stated in the function definition, the following behaviors should be followed by all SPARQL extension functions defined in the GeoSPARQL standard:

* Functions returning a new geometry literal should follow the literal format of the first geometry literal input parameter. If no geometry literal input parameter is present, a WKT literal shall be returned.
* Functions returning a new geometry literal should follow the SRS defined in the literal format of the first geometry literal input parameter. If no geometry literal input parameter is present, a geometry result should be returned in the CRS84 SRS.

For further discussion of the effects of errors during FILTER evaluation, consult Section 17footnote:[<https://www.w3.org/TR/sparql11-query/#expressions>] of the SPARQL specification <<SPARQL>>.

Note that returning values instead of raising an error serves as an extension mechanism of SPARQL.

From Section 17.3.1footnote:[<https://www.w3.org/TR/sparql11-query/#operatorExtensibility>] of the SPARQL specification <<SPARQL>>:

[quote]
SPARQL language extensions may provide additional associations between operators and operator functions; ... No additional operator may yield a result that replaces any result other ... . The consequence of this rule is that SPARQL `FILTER` s will produce at least the same intermediate bindings after applying a `FILTER` as an unextended implementation.

This extension mechanism enables GeoSPARQL implementations to simultaneously support multiple geometry serializations. For example, a system that supports <<RDFS Datatype: geo:wktLiteral, WKT Literal>> serializations may also support <<RDFS Datatype: geo:gmlLiteral, GML Literal>> serializations and consequently would not raise an error if it encounters multiple geometry datatypes while processing a given query.

[NOTE,keep-separate=true]
====
Several non-topological query functions use a unit of measure IRI. See the <<Recommendation for units of measure,  Recommendation for units of measure>>. Also, the OGC has recommended units of measure vocabularies for use, see the OGC Definitions Serverfootnote:[https://www.ogc.org/def-server].
====

==== Function: geof:azimuth

[%unnumbered]
[source,turtle]
----
geof:azimuth (geom1: ogc:geomLiteral, geom2: ogc:geomLiteral): xsd:double
----

The function http://www.opengis.net/def/function/geosparql/azimuth[`geof:azimuth`] returns the azimuth of a segment between two points clockwise from the North (0,1) in radians:
The function does not return any value if the given geometries are not points.


==== Function: geof:closestPoint

[%unnumbered]
[source,turtle]
----
geof:closestPoint (geom1: ogc:geomLiteral, geom2: ogc:geomLiteral): ogc:geomLiteral
----

The function http://www.opengis.net/def/function/geosparql/closestPoint[`geof:closestPoint`] returns the first closest point of a `geom1` to `geom2` in the literal format and spatial reference system of the first parameter given to the function.

==== Function: geof:compactnessRatio

[%unnumbered]
[source,turtle]
----
geof:compactnessRatio (geom1: ogc:geomLiteral): xsd:double
----

The function http://www.opengis.net/def/function/geosparql/compactnessRatio[`geof:compactnessRatio`] returns the compactness ratio of a geometry.

==== Function: geof:minDepth

[%unnumbered]
[source,turtle]
----
geof:minDepth (geom: ogc:geomLiteral, depth: xsd:double, unit: xsd:anyURI): xsd:boolean
----

The function http://www.opengis.net/def/function/geosparql/minDepth[`geof:minDepth`] returns true if `geom` is of at least a minimum depth (Z-extent). 

==== Function: geof:maxDepth

[%unnumbered]
[source,turtle]
----
geof:maxDepth (geom: ogc:geomLiteral, depth: xsd:double, unit: xsd:anyURI): xsd:boolean
----

The function http://www.opengis.net/def/function/geosparql/maxDepth[`geof:maxDepth`] returns true if `geom` is of a most a maximum depth (Z-extent).
