== Geometry 3D Extension

This clause defines the _Geometry 3D Extension_ parameterized Requirements class with the base IRI `/req/geometry3d-extension`. There is a single corresponding conformance class _Geometry 3D Extension_, with the IRI `/conf/geometry3d-extension`. These Requirements define a vocabulary for asserting and querying information about geometry data, and define query functions for operating on geometry data.

[requirements_class,identifier="/req/geometry3d-extension",subject="Implementation Specification"]
.Geometry Extension
====
requirement:: /req/geometry-extension/geometry3d-class
requirement:: /req/geometry-extension/geometry3d-collection-class
requirement:: /req/geometry-extension/feature-properties
requirement:: /req/geometry-extension/geometry-properties
requirement:: /req/geometry-extension/query-functions
requirement:: /req/geometry-extension/srid-function
requirement:: /req/geometry-extension/sa-functions
requirement:: /req/geometry-extension/ply-literal
requirement:: /req/geometry-extension/ply-literal-default-srs
requirement:: /req/geometry-extension/ply-axis-order
requirement:: /req/geometry-extension/ply-literal-empty
requirement:: /req/geometry-extension/geometry-as-ply-literal
requirement:: /req/geometry-extension/asPLY-function
requirement:: /req/geometry-extension/gltf-literal
requirement:: /req/geometry-extension/gltf-literal-empty
requirement:: /req/geometry-extension/geometry-as-gltf-literal
requirement:: /req/geometry-extension/asGLTF-function
requirement:: /req/geometry-extension/x3d-literal
requirement:: /req/geometry-extension/x3d-literal-empty
requirement:: /req/geometry-extension/geometry-as-3d-literal
requirement:: /req/geometry-extension/asX3D-function
requirement:: /req/geometry-extension/obj-literal
requirement:: /req/geometry-extension/obj-literal-srs
requirement:: /req/geometry-extension/obj-literal-empty
requirement:: /req/geometry-extension/geometry-as-obj-literal
requirement:: /req/geometry-extension/asOBJ-function
====

As part of the vocabulary, RDFS datatypes are defined for encoding detailed geometry information as a literal value. A literal representation of a geometry is needed so that geometric values may be treated as a single unit. Such a representation allows geometries to be passed to external functions for computations and to be returned from a query.

=== Rationale

Other schemes for encoding simple geometry data in RDF have been implemented. The W3C Basic Geo vocabularyfootnote:[http://www.w3.org/2003/01/geo/] was an early (2003) RDF vocabulary for "representing lat(itude), long(itude) and other information about spatially-located things. Geo specifies WGS84 as the reference datum". Further, many widely used Semantic Web vocabularies contain some spatial data support. For example, _Dublin Core Terms_ provides a _Location_ classfootnote:[http://purl.org/dc/terms/Location] for "A spatial region or named place." and _schema.org_ provides a number of spatial object and geometry classes, such as `GeoCoordinates` footnote:[https://schema.org/GeoCoordinates] and `GeoShape` footnote:[https://schema.org/GeoShape]. 

Many vocabularies such as the above provide little specific support for detailed geometries and only specify using the WGS84 Coordinate Reference System (CRS).

Since the first version of GeoSPARQL, many ontologies have imported GeoSPARQL. For example, the _ISA Programme Location Core Vocabulary_ footnote:[https://www.w3.org/ns/locn] whose usage notes provide examples containing GeoSPARQL literals and the use of GeoSPARQL's "geometry class". The W3C's more recent _Data Catalog Vocabulary, Version 2_ (DCAT2) standardfootnote:[https://www.w3.org/TR/vocab-dcat/#spatial-properties] similarly contains usage notes for `geometry`, `bbox` and other properties that suggest the use of GeoSPARQL literals.

Some of the properties defined in these vocabularies, such as DCAT2's https://www.w3.org/TR/vocab-dcat-2/#Property:dataset_spatial_resolution[`dcat:spatialResolution`] have motivated the inclusion of new properties in this version of GeoSPARQL. In this case the equivalent property is <<Property: geo:hasSpatialResolution, `geo:hasSpatialResolution`>>. The GeoSPARQL 1.1 Standards Working Group charter <<CHARTER>> contains references to a number of vocabularies/ontologies that were influential in the generation of this version of GeoSPARQL.

=== GeoSPARQL and Simple Features 3D (SFA-CA)

The GeoSPARQL Geometry Extension is largely based on the ISO/OGC Simple Features Access - Common Architecture (SFA-CA) Standard <<OGC06-103r4>>. Contrary to what the name may imply, SFA-CA is about Geometry and not about Features. SFA-CA describes simple geometry, meaning that geometric shapes are based on points and straight lines (linear interpolations) between points. Within a single Geometry, these lines may not cross.

Neither GeoSPARQL nor SFA-CA support full three-dimensional geometry. Coordinates may be three-dimensional, which means that points may have a Z-coordinate next to an X- and Y-coordinate. The Z-coordinate then holds the value of height or depth. However, lines or surfaces can only have one Z value for any explicit or interpolated X,Y pair. This approach is often referred to as 2.5 dimensional geometry. Geometric functions working with Geometries that have Z values will ignore Z values in calculations and first project geometry onto the Z=0 level.

SFA-CA also describes M coordinate values that may be part of geometry encodings. The M value represents a measure, a value that can be used in information systems that support linear referencing. GeoSPARQL at the moment does not support linear referencing. Like Z values in coordinates, M values are to be ignored.

SFA-CA specifies a class hierarchy for Geometry. Although these classes are not part of the GeoSPARQL ontology, the GeoSPARQL SWG does publish a vocabulary of Simple Features geometry: http://www.opengis.net/ont/sf. Geometry types defined in this vocabulary can be considered safe to use with GeoSPARQL. The two Geometry serializations that were specified in GeoSPARQL 1.0, WKT and GML, fully support all SFA-CA geometry types. However, the two Geometry serializations that were introduced in GeoSPARQL 1.1 do not. Some SFA-CA geometry types are not supported by either the OGC KML <<OGC12-007r2>> or the GeoJSON format. For example, neither KML nor GeoJSON support the Triangulated Integrated Network (TIN) or Triangle geometry types.

=== Recommendation for units of measure

For geometric data to be interpreted and used correctly, the units of measure should be known. Typically, the particular Spatial Reference System (SRS) that is associated with a Geometry instance will specify a unit of measurement. However, some elements of GeoSPARQL allow arbitrary units of distance to be used, for example the property <<Property: geo:hasSpatialResolution, `geo:hasSpatialResolution`>> or the function <<Function: geof:buffer, `geof:buffer`>>. In those cases it is advisable to make use of a well-known web vocabulary for units of measurement. Making the unit of measurement explicit will improve data interoperability. The recommended vocabulary for units of measurement for GeoSPARQL is the _Quantities, Units, Dimensions and Types (QUDT)_ ontologyfootnote:[http://www.qudt.org] but others may be used, as long as they are well-described.

=== Influence of Reference Systems on computations

A Geometry object consists of a set of coordinates and a specification on how the coordinates should be interpreted. This specification is known as a Spatial reference System (SRS). Taken together, coordinates and SRS allow performing computations on Geometry objects. For example, sizes can be calculated or new Geometry objects can be created. Some Spatial Reference Systems describe a two-dimensional flat space. In that case, coordinates are understood to be Cartesian, and Cartesian geometric computations can be performed. But Spatial Reference Systems can describe other types of spaces, to which Cartesian computations are not applicable. For example, if CRS http://www.opengis.net/def/crs/OGC/1.3/CRS84[`+<http://www.opengis.net/def/crs/OGC/1.3/CRS84>+`] is used, coordinates are to be interpreted as decimal degrees of latitude and longitude, designating positions on a spheroid. The distance between two points using this CRS is different from the distance between two points that have the same coordinates but are based on a Cartesian CRS or other SRS.

To avoid erroneous computations involving Geometry, data publishers are recommended to clearly indicate the type of space that is described by the SRS.

=== Parameters

The following parameters are defined for the _Geometry Extension_ Requirements.

serialization:: Specifies the serialization standard to use when generating geometry literals as well as the supported geometry types.

[NOTE,keep-separate=true]
====
A serialization strongly affects the geometry conceptualization. The WKT serialization aligns the geometry types with _ISO 19125 Simple Features_ <<OGC06-103r4>> <<ISO19125-1>>; the GML serialization aligns the geometry types with _ISO 19107 Spatial Schema_ <<ISO19107>>.
====

version:: Specifies the version of the serialization format used.

=== Geometry 3D Class

A single root geometry class is defined: <<Class: geo:Geometry, `geo:Geometry`>>. In addition, properties are defined for describing geometry data and for associating geometries with features.

One container class is defined: <<Class: geo:GeometryCollection, Geometry Collection>>. 

==== Class: geo:Geometry

The class http://www.opengis.net/ont/geosparql#Geometry[`geo:Geometry`] is conceptually derived from UML class `Geometry` in <<ISO19107>> which is that standard's "root class of the geometric object taxonomy and supports interfaces common to all geographically referenced geometric objects". `geo:Geometry` is defined by the following:

[%unnumbered]
[source,turtle]
----
geo:3DGeometry 
    a rdfs:Class, owl:Class ;
    rdfs:isDefinedBy geo: ; 
    skos:prefLabel "Geometry"@en ;
    rdfs:subClassOf geo:Geometry ;
    owl:disjointWith geo:Feature;
    skos:definition "A geometry with at least three dimensions."@en ;
    skos:note "Geometry can be used as a representation of the shape, extent or 
              location of a Feature and may exist as a self-contained entity."@en ;
.
----

[[req_geometry-extension_3dgeometry-class]]
[requirement,identifier="/req/geometry-extension/geometry-class"]
.3DGeometry Class
====
Implementations shall allow the RDFS class <<Class: geo:3DGeometry, `geo:3DGeometry`>> to be used in SPARQL graph patterns.
====

[[geometry_properties]]
=== Standard Properties for geo:3DGeometry

Properties are defined for describing geometry metadata.

[requirement,identifier="/req/geometry-extension/geometry-properties"]
.Geometry 3D Properties
====
Implementations shall allow the properties 
<<Property: geo:textures, `geo:textures`>>, 
<<Property: geo:vertices, `geo:vertices`>>, 
<<Property: geo:faces, `geo:faces`>>, 
<<Property: geo:rotation, `geo:rotation`>>, 
<<Property: geo:position, `geo:position`>>, 
<<Property: geo:scale, `geo:scale`>> and
<<Property: geo:translation, `geo:translation`>> 
to be used in SPARQL graph patterns.
====

==== Property: geo:textures

The property http://www.opengis.net/ont/geosparql#textures[`geo:textures`] links one or many surfaces to a texture that covers, the surface or part of its surface. Textures may be linked using a property like foaf image.

[%unnumbered]
[source,turtle]
----
geo:dimension 
    a rdf:Property, owl:ObjectProperty ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "dimension"@en ;
    skos:definition "One or many texture instances linked to a Geometry object."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range sf3d:Texture ;
.
----

==== Property: geo:vertices

The property http://www.opengis.net/ont/geosparql#vertices[`geo:vertices`] is defined to link a Geometry object to the dimension of direct positions (coordinate tuples) used in the Geometry's definition.

[%unnumbered]
[source,turtle]
----
geo:coordinateDimension 
    a rdf:Property, owl:DatatypeProperty;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "coordinate dimension"@en ;
    skos:definition "The number of measurements or axes needed to describe the
                    position of this Geometry in a coordinate system."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range xsd:integer ;
.
----


=== 3D Geometry Serializations

This section establishes the Requirements class for representing 3D Geometry data in RDF literals, according to different non-RDF systems.

GeoSPARQL presents specializations of the `geo:hasSerialization` property for indicating particular serializations and specialized datatype literals for containing them. It does not provide comprehensive definitions of their content since these are given in standards external to GeoSPARQL, all of which are referenced.

GeoSPARQL does present some Requirements for literal structure which extend the serialization-defining standards, for example the requirement to allow indications of spatial reference systems within WKT geometry representations.

[[NOTE]]
====
GeoSPARQL's expectation of RDF literal representations of geometry data is that it is related to the _Simple Features Access_ (SFA) <<OGC06-103r4>> <<ISO19125-1>> standard's conceptualization of geometry which defines classes such as `Point`, `Curve` and `Surface` and specialized variants of them which it presents in a hierarchy. All SFA classes are represented in OWL in the _Simple Features Vocabulary_ presented within GeoSPARQL as an independent profile element, see <<GeoSPARQL Standard structure, GeoSPARQL Standard structure>>.

Some geometry representation systems given here do not use the same terminology as SFA, in particular Discrete Global Grid Systems. To know the extent to which geometry literal representations listed here support SFA, or map to SFA, please see their definitions.
====

==== Polygon File Format (PLY)

This section establishes the requirements for representing Geometry data in RDF based on the Polygon File Format (PLY). It defines one RDFS Datatype: <<RDFS Datatype: geo:plyLiteral, PLY Literal>> and one property, <<Function: geof:asPLY, as PLY>>.

===== RDFS Datatype: geo:plyLiteral

The datatype http://www.opengis.net/ont/geosparql#plyLiteral[`geo:plyLiteral`] is used to contain the Polygon File Format (PLY) serialization of a Geometry.

[%unnumbered]
[source,turtle]
----
geo:wktLiteral 
    a rdfs:Datatype ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "PLY literal"@en ;
    skos:definition "A PLY Text serialization of a Geometry object."@en ;
.
----

[[req_geometry_extension_ply-literal-empty]]
[requirement,identifier="/req/geometry-extension/ply-literal-empty"]
.Empty PLY Literal
====
An empty RDFS Literal of type <<RDFS Datatype: geo:plyLiteral, `geo:plyLiteral`>> shall be interpreted as an empty Geometry.
====

An empty Geometry in PLY is equivalent to the following representation.
[source,turtle]
----
ply
format ascii 1.0
element vertex 0 
property float x 
property float y 
property float z 
element face 0 
property list uchar int vertex_indices
end_header 
----

[[geo_asply]]
===== Property: geo:asPLY

The property http://www.opengis.net/ont/geosparql#asPLY[`geo:asPLY`] is defined to link a Geometry with its PLY serialization.

[[req_geometry_extension_geometry-as-wkt-literal]]
[requirement,identifier="/req/geometry-extension/geometry-as-ply-literal"]
.asPLY Property
====
Implementations shall allow the RDF property <<Property: geo:asPLY, `geo:asPLY`>> to be used in SPARQL graph patterns.
====

[%unnumbered]
[source,turtle]
----
geo:asPLY 
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:subPropertyOf geo:hasSerialization ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "as PLY"@en ;
    skos:definition "The PLY serialization of a Geometry."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range geo:plyLiteral ;
.
----

===== Function: geof:asPLY

[%unnumbered]
[source,turtle]
----
geof:asPLY (geom: ogc:geomLiteral): geo:plyLiteral
----

The function http://www.opengis.net/def/function/geosparql/asPLY[`geof:asPLY`] converts `geom` to an equivalent PLY representation preserving the spatial reference system. 
If `geom` represents a 2D geometry its Z coordinates shall be set to 0.

[[req_geometry_extension_asPLY-function]]
[requirement,identifier="/req/geometry-extension/asPLY-function"]
.asPLY Function
====
Implementations shall support <<Function: geof:asPLY, `geof:asPLY`>> as a SPARQL extension function.
====

==== Graphics Library Transmission Format

This section establishes the requirements for representing Geometry data in RDF based on Graphics Library Transmission Format (GLTF). 
It defines the RDFS Datatype: <<RDFS Datatypes: geo:gltfLiteral, GLTF Literal>> and one property, <<Property: geo:asGLTF, as GLTF>>. 

===== RDFS Datatypes: geo:gltfLiteral

The datatype http://www.opengis.net/ont/geosparql#gltfLiteral[`geo:gltfLiteral`] is used to contain the Graphics Library Transmission Format (GLTF) serialization of a Geometry.

[source,turtle]
----
geo:gltfLiteral 
    a rdfs:Datatype ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "GLTF literal"@en ;
    skos:definition "A GLTF serialization of a Geometry object."@en ;
.
----
[#req_geometry_extension_gltf-literal]

[#req_geometry_extension_gltf-literal-empty]
|===
| *Req 18* An empty RDFS Literal of type <<RDFS Datatypes: geo:gltfLiteral, `geo:gltfLiteral`>> shall be interpreted as an empty Geometry.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/gltf-literal-empty[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/gltf-literal-empty`]
|===

An empty Geometry in GLTF is equivalent to the following representation.
[source,turtle]
----
{
"meshes":[]
}
----

===== Property: geo:asGLTF

The property http://www.opengis.net/ont/geosparql#asGLTF[`geo:asGLTF`] is defined to link a Geometry with its GLTF serialization.

[#req_geometry_extension_geometry-as-gltf-literal]
|===
| *Req {counter:req}* Implementations shall allow the RDF property <<Property: geo:asGLTF, `geo:asGLTF`>> to be used in SPARQL graph patterns.
|http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-as-gltf-literal[`http://www.opengis.net/spec/geosparql/1.0/req/geometry-extension/geometry-as-gltf-literal`]
|===

[source,turtle]
----
geo:asGLTF
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:subPropertyOf geo:hasSerialization ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "as GLTF"@en ;
    skos:definition "The GLTF serialization of a Geometry."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range geo:gltfLiteral ;
.
----

===== Function: geof:asGLTF

.asGLTF Function
----
geof:asGLTF (geom: ogc:geomLiteral): geo:gltfLiteral
----

The function http://www.opengis.net/def/function/geosparql/asGLTF[`geof:asGLTF`] converts `geom` to an equivalent GLTF representation preserving the spatial reference system. 
If `geom` represents a 2D geometry its Z coordinates shall be set to 0.

[#req_geometry_extension_asGLTF-function]
|===
| *Req {counter:req}* Implementations shall support <<Property: geo:asGLTF, `geo:asGLTF`>> as a SPARQL extension function.
|http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asGLTF-function[`http://www.opengis.net/spec/geosparql/1.1/req/geometry-extension/asGLTF-function`]
|===

==== Extensible 3D (X3D)

This section establishes a Requirements class for representing Geometry data in RDF as defined by the Extensible 3D (X3D) Encoding Standard. It defines one RDFS Datatype:
<<RDFS Datatype: geo:x3dLiteral, X3D Literal>> and one property, <<Function: geof:asX3D, as X3D>>.

===== RDFS Datatype: geo:x3dLiteral

The datatype http://www.opengis.net/ont/geosparql#x3dLiteral[`geo:x3dLiteral`] is used to contain the Extensible 3D (X3D) serialization of a Geometry.

[%unnumbered]
[source,turtle]
----
geo:x3dLiteral 
    a rdfs:Datatype ;
    rdfs:isDefinedBy geo: ; 
    skos:prefLabel "X3D literal"@en ;
    skos:definition "The datatype of X3D literal values"@en ;
.
----

[[req_geometry_extension_x3d-literal]]
[requirement,identifier="/req/geometry-extension/x3d-literal"]
.X3D Literal
====
All <<RDFS Datatype: geo:x3dLiteral, `geo:x3dLiteral`>> instances shall consist of a valid element from the GML schema that implements a subtype of `GM_Object` as defined in <<OGC07-036>>.
====

[[req_geometry_extension_x3d-literal-empty]]
[requirement,identifier="/req/geometry-extension/x3d-literal-empty"]
.Empty X3D Literal
====
An empty <<RDFS Datatype: geo:x3dLiteral, `geo:x3dLiteral`>> shall be interpreted as an empty Geometry.
====

===== Property: geo:asX3D

The property http://www.opengis.net/ont/geosparql#asX3D[`geo:asX3D`] is defined to link a Geometry with its GML serialization.

[[req_geometry_extension_geometry-as-x3d-literal]]
[requirement,identifier="/req/geometry-extension/geometry-as-x3d-literal"]
.asX3D Property
====
Implementations shall allow the RDF property <<Property: geo:asX3D, `geo:asX3D`>> to be used in SPARQL graph patterns.
====

[%unnumbered]
[source,turtle]
----
geo:asX3D 
    a rdf:Property ; 
    rdfs:subPropertyOf geo:hasSerialization ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "as X3D"@en ;
    skos:definition "The X3D serialization of a Geometry."@en ; 
    rdfs:domain geo:Geometry ;
    rdfs:range geo:x3dLiteral ;
.
----

===== Function: geof:asX3D

[%unnumbered]
[source,turtle]
----
geof:asX3D (geom: ogc:geomLiteral, gmlProfile: xsd:string): geo:x3dLiteral
----

The function http://www.opengis.net/def/function/geosparql/asX3D[`geof:asX3D`] converts `geom` to an equivalent X3D representation preserving the coordinate reference system. 
If `geom` represents a 2D geometry its Z coordinates shall be set to 0.

[[req_geometry_extension_asX3D-function]]
[requirement,identifier="/req/geometry-extension/asX3D-function"]
.asX3D Function
====
Implementations shall support <<Function: geof:asX3D, `geof:asX3D`>> as a SPARQL extension function.
====

==== Wavefront OBJ

This section establishes a Requirements class for representing Geometry data in RDF based on Wavefront OBJ (OBJ). It defines one RDFS Datatype: <<RDFS Datatype: geo:objLiteral, OBJ Literal>> and one property, <<Function: geof:asOBJ, as OBJ>>.

===== RDFS Datatype: geo:objLiteral

The datatype http://www.opengis.net/ont/geosparql#gmlLiteral[`geo:objLiteral`] is used to contain the OBJ serialization of a Geometry.

[%unnumbered]
[source,turtle]
----
geo:objLiteral a rdfs:Datatype ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "OBJ Literal"@en ;
    skos:definition "A OBJ serialization of a Geometry object."@en .
----

Valid <<RDFS Datatype: geo:objLiteral, OBJ Literal>> instances are formed by encoding Geometry information as a Geometry object.

[[req_geometry_extension_obj-literal]]
[requirement,identifier="/req/geometry-extension/obj-literal"]
.OBJ Literal
====
All <<RDFS Datatype: geo:objLiteral, `geo:objLiteral`>> instances shall consist of the Geometry objects as defined in the OBJ specification.
====

[[req_geometry_extension_obj-literal-empty]]
[requirement,identifier="/req/geometry-extension/obj-literal-empty"]
.Empty OBJ Literal
====
An empty RDFS Literal of type <<RDFS Datatype: geo:objLiteral, `geo:objLiteral`>> shall be interpreted as an empty Geometry .
====

===== Property: geo:asOBJ

The property http://www.opengis.net/ont/geosparql#asOBJ[`geo:asOBJ`] is defined to link a Geometry with its OBJ serialization.

[[req_geometry_extension_obj-as-obj-literal]]
[requirement,identifier="/req/geometry-extension/geometry-as-obj-literal"]
.asOBJ Property
====
Implementations shall allow the RDF property <<Property: geo:asOBJ, `geo:asOBJ`>> to be used in SPARQL graph patterns.
====

[%unnumbered]
[source,turtle]
----
geo:asOBJ 
    a rdf:Property, owl:DatatypeProperty ;
    rdfs:subPropertyOf geo:hasSerialization ;
    rdfs:isDefinedBy geo: ;
    skos:prefLabel "as OBJ"@en ;
    skos:definition "The OBJ serialization of a Geometry."@en ;
    rdfs:domain geo:Geometry ;
    rdfs:range geo:objLiteral ;
.
----

===== Function: geof:asOBJ

[%unnumbered]
[source,turtle]
----
geof:asOBJ (geom: ogc:geomLiteral): geo:objLiteral
----

The function http://www.opengis.net/def/function/geosparql/asOBJ[`geof:asOBJ`] converts `geom` to an equivalent OBJ representation. 
If `geom` represents a 2D geometry its Z coordinates shall be set to 0.

[[req_geometry_extension_asOBJ-function]]
[requirement,identifier="/req/geometry-extension/asOBJ-function"]
.asOBJ Function
====
Implementations shall support <<Function: geof:asOBJ, `geof:asOBJ`>> as a SPARQL extension function.
====

[[query_functions]]
=== Non-topological Query Functions

This Requirements class defines SPARQL functions for performing non-topological spatial operations on 3D geometries.

[[req_geometry_extension_query-functions-non-sf]]
[requirement,identifier="/req/geometry-extension/query-functions-non-sf"]
.Non-topological Query Functions (Non Simple Features)
====
Implementations shall support the functions 
<<Function: geof:metricLength, `geof:metricLength`>>
as SPARQL extension functions which are defined in this standard, for non-DGGS geometry literals.
====

////

Functions from this Requirements class are listed below, alphabetically.

==== Function notes
These notes apply to all of the following functions in this section.

An invocation of any of the following functions with invalid arguments produces an error. An invalid argument includes any of the following:

* An argument of an unexpected type
* An invalid geometry literal value
* A non-fitting geometry type for the given function
* A geometry literal from a spatial reference system that is incompatible with the spatial reference system used for calculations
* An invalid unit IRI

A more detailed description of expected inputs and expected outputs of the given functions is shown in Annex B.

Unless otherwise stated in the function definition, the following behaviors should be followed by all SPARQL extension functions defined in the GeoSPARQL standard:

* Functions returning a new geometry literal should follow the literal format of the first geometry literal input parameter. If no geometry literal input parameter is present, a WKT literal shall be returned.
* Functions returning a new geometry literal should follow the SRS defined in the literal format of the first geometry literal input parameter. If no geometry literal input parameter is present, a geometry result should be returned in the CRS84 SRS.

For further discussion of the effects of errors during FILTER evaluation, consult Section 17footnote:[<https://www.w3.org/TR/sparql11-query/#expressions>] of the SPARQL specification <<SPARQL>>.

Note that returning values instead of raising an error serves as an extension mechanism of SPARQL.

From Section 17.3.1footnote:[<https://www.w3.org/TR/sparql11-query/#operatorExtensibility>] of the SPARQL specification <<SPARQL>>:

[quote]
SPARQL language extensions may provide additional associations between operators and operator functions; ... No additional operator may yield a result that replaces any result other ... . The consequence of this rule is that SPARQL `FILTER` s will produce at least the same intermediate bindings after applying a `FILTER` as an unextended implementation.

This extension mechanism enables GeoSPARQL implementations to simultaneously support multiple geometry serializations. For example, a system that supports <<RDFS Datatype: geo:wktLiteral, WKT Literal>> serializations may also support <<RDFS Datatype: geo:gmlLiteral, GML Literal>> serializations and consequently would not raise an error if it encounters multiple geometry datatypes while processing a given query.

[NOTE,keep-separate=true]
====
Several non-topological query functions use a unit of measure IRI. See the <<Recommendation for units of measure,  Recommendation for units of measure>>. Also, the OGC has recommended units of measure vocabularies for use, see the OGC Definitions Serverfootnote:[https://www.ogc.org/def-server].
====

==== Function: geof:metricLength

[%unnumbered]
[source,turtle]
----
geof:metricLength (geom: ogc:geomLiteral): xsd:double
----

The function http://www.opengis.net/def/function/geosparql/metricLength[`geof:metricLength`] returns the length of `geom` in meters. The longest length from any one dimension is returned. This is for example the length of a line from its beginning point to its endpoint or the length of the boundary of a polygon. This function is similar to <<Function: geof:length, `geof:length`>> but does not need a specification of measurement unit.

==== Function: geof:minDepth

[%unnumbered]
[source,turtle]
----
geof:minDepth (geom: ogc:geomLiteral, depth: xsd:double, unit: xsd:anyURI): xsd:boolean
----

The function http://www.opengis.net/def/function/geosparql/minDepth[`geof:minDepth`] returns true if `geom` is of at least a minimum depth (Z-extent). 

==== Function: geof:maxDepth

[%unnumbered]
[source,turtle]
----
geof:maxDepth (geom: ogc:geomLiteral, depth: xsd:double, unit: xsd:anyURI): xsd:boolean
----

The function http://www.opengis.net/def/function/geosparql/maxDepth[`geof:maxDepth`] returns true if `geom` is of a most a maximum depth (Z-extent).

==== Function: geof:closestPoint

[%unnumbered]
[source,turtle]
----
geof:closestPoint (geom1: ogc:geomLiteral, geom2: ogc:geomLiteral): ogc:geomLiteral
----

The function http://www.opengis.net/def/function/geosparql/closestPoint[`geof:closestPoint`] returns the first closest point of a `geom1` to `geom2` in the literal format and spatial reference system of the first parameter given to the function.

==== Function: geof:compactnessRatio

[%unnumbered]
[source,turtle]
----
geof:compactnessRatio (geom1: ogc:geomLiteral): xsd:double
----

The function http://www.opengis.net/def/function/geosparql/compactnessRatio[`geof:compactnessRatio`] returns the compactness ratio of a geometry.

