== Query Rewrite Extension

This clause establishes the _Query Rewrite Extension_ parameterized Requirements class with base IRI `/req/query-rewrite-extension`, which has a single corresponding conformance class _Query Rewrite Extension_, with IRI `/conf/query-rewrite-extension`. These Requirements define a set of RIF rules <<RIF>> that use topological extension functions defined in <<Geometry Extension>> to establish the existence of direct topological predicates defined in <<Topology Vocabulary Extension>>. One possible implementation strategy is to transform a given query by expanding a triple pattern involving a direct spatial predicate into a series of triple patterns and an invocation of the corresponding extension function as specified in the RIF rule.

[requirements_class,identifier="/req/query-rewrite-extension",subject="Implementation Specification"]
.Query Rewrite Extension
====
requirement:: /req/query-rewrite-extension/sf-query-rewrite
requirement:: /req/query-rewrite-extension/eh-query-rewrite
requirement:: /req/query-rewrite-extension/rcc8-query-rewrite

====

The following rule specified using the RIF Core Dialect <<RIFCORE>> and shown in _Presentation Syntax_ is used as a template to describe rules in the remainder of this clause. `ogc:relation` is used as a placeholder for the spatial relation IRIs defined in Clause 7, and `ogc:function` is used as a placeholder for the spatial functions defined in <<Geometry Extension>>. `ogc:asGeomLiteral` is used to indicate one of the properties that link `Geometry` instances to serializations, such as <<prop-aswkt, `asWKT`>> or <<prop-asgeojson, `asGeoJSON`>>. The variables `?so1` and `?so2` represent <<class-spatialobject, `SpatialObject`>> instances (<<class-feature, `Feature`>> or <<class-geometry, `Geometry`>> instances), `?g1` and `?g2` <<class-geometry, `Geometry`>> instances only and `?g1Serial` and `?g2Serial` represent <<class-geometry, `Geometry`>> instance serializations, e.g. <<prop-aswkt, `asWKT`>> etc. literals.

[%unnumbered]
[source,rif]
----
Forall ?so1 ?so2 ?g1 ?g2 ?g1Serial ?g2Serial (
    ?so1[ogc:relation->?so2] :- Or (
        And (
            # feature - feature rule 
            ?so1[geo:hasDefaultGeometry->?g1]
                ?so2[geo:hasDefaultGeometry->?g2] 
                ?g1[ogc:asGeomLiteral->?g1Serial] 
                ?g2[ogc:asGeomLiteral->?g2Serial]
                External(ogc:function(?g1Serial, ?g2Serial))
        )
        And (
            # feature - geometry rule 
            ?so1[geo:hasDefaultGeometry->?g1]
                ?g1[ogc:asGeomLiteral->?g1Serial]
                ?so2[ogc:asGeomLiteral->?g2Serial] 
                External(ogc:function(?g1Serial, ?g2Serial))
        )
        And (
            # geometry - feature rule 
            ?so1[ogc:asGeomLiteral->?g1Serial]
                ?so2[geo:hasDefaultGeometry->?g2]
                ?g2[ogc:asGeomLiteral->?g2Serial] 
                External(ogc:function(?g1Serial, ?g2Serial))
        )
        And (
            # geometry - geometry rule 
            ?so1[ogc:asGeomLiteral->?g1Serial] 
                ?so2[ogc:asGeomLiteral->?g2Serial]
                External(ogc:function(?g1Serial, ?g2Serial))
        ) 
    )
)
----

=== Parameters

* *relation_family*: Specifies the set of topological spatial relations to support.
* *serialization*: Specifies the serialization standard to use for geometry literals.
* *version*: Specifies the version of the serialization format used.

[[query_rewrite_sf]]
=== Simple Features Relation Family

This clause defines Requirements for the _Simple Features_ relation family. <<sf_query_transformation_rules>> specifies the function and property substitutions for each rule in the _Simple Features_ relation family.

[[req_query-rewrite-extension_sf-query-rewrite]]
[requirement,identifier="/req/query-rewrite-extension/sf-query-rewrite"]
.Simple Features Query Transformation Rules
====
Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime <<SPARQLENT>> for the RIF rules <<RIFCORE>> 
<<rule-sfequals, `sfEquals`>>,
<<rule-sfdisjoint, `sfDisjoint`>>,
<<rule-sfintersects, `sfIntersects`>>,
<<rule-sftouches, `sfTouches`>>,
<<rule-sfcrosses, `sfCrosses`>>,
<<rule-sfwithin, `sfWithin`>>,
<<rule-sfcontains, `sfContains`>> and
<<rule-sfoverlaps, `sfOverlaps`>>.
====

[[sf_query_transformation_rules]]
.Simple Features Query Transformation Rules
|===
|Rule | ogc:relation | ogc:function

| [[rule-sfequals]]`sfEquals` | <<Simple Features Relation Family, `sfEquals`>> | <<simple_features_query_functions, `sfEquals`>>
| [[rule-sfdisjoint]]`sfDisjoint` | <<Simple Features Relation Family, `sfDisjoint`>> | <<simple_features_query_functions, `sfDisjoint`>>
| [[rule-sfintersects]]`sfIntersects` | <<Simple Features Relation Family, `sfIntersects`>> | <<simple_features_query_functions, `sfIntersects`>>
| [[rule-sftouches]]`sfTouches` | <<Simple Features Relation Family, `sfTouches`>> | <<simple_features_query_functions, `sfTouches`>>
| [[rule-sfcrosses]]`sfCrosses` | <<Simple Features Relation Family, `sfCrosses`>> | <<simple_features_query_functions, `sfCrosses`>>
| [[rule-sfwithin]]`sfWithin` | <<Simple Features Relation Family, `sfWithin`>> | <<simple_features_query_functions, `sfWithin`>>
| [[rule-sfcontains]]`sfContains` | <<Simple Features Relation Family, `sfContains`>> | <<simple_features_query_functions, `sfContains`>>
| [[rule-sfoverlaps]]`sfOverlaps` | <<Simple Features Relation Family, `sfOverlaps`>> | <<simple_features_query_functions, `sfOverlaps`>>
|===

[[query_rewrite_eh]]
=== Egenhofer Relation Family

This clause defines Requirements for the _Egenhofer_ relation family. <<eh_query_transformation_rules>> specifies the function and property substitutions for each rule in the _Egenhofer_ relation family.

[[req_query-rewrite-extension_eh-query-rewrite]]
[requirement,identifier="/req/query-rewrite-extension/eh-query-rewrite"]
.Egenhofer Query Transformation Rules
====
Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime <<SPARQLENT>> for the RIF rules <<RIFCORE>> 
<<rule-ehequals, `ehEquals`>>,
<<rule-ehdisjoint, `ehDisjoint`>>,
<<rule-ehmeet, `ehMeet`>>,
<<rule-ehoverlap, `ehOverlap`>>,
<<rule-ehcovers, `ehCovers`>>,
<<rule-ehcoveredby, `ehCoveredBy`>>,
<<rule-ehinside, `ehInside`>> and
<<rule-ehcontains, `ehContains`>>.
====

[[eh_query_transformation_rules]]
.Egenhofer Query Transformation Rules
|===
|Rule | ogc:relation | ogc:function

| [[rule-ehequals]]`ehEquals` | <<Egenhofer Relation Family, `ehEquals`>> | <<egenhofer_query_functions, `ehEquals`>>
| [[rule-ehdisjoint]]`ehDisjoint` | <<Egenhofer Relation Family, `ehDisjoint`>> | <<egenhofer_query_functions, `ehDisjoint`>>
| [[rule-ehmeet]]`ehMeet` | <<Egenhofer Relation Family, `ehMeet`>> | <<egenhofer_query_functions, `ehMeet`>>
| [[rule-ehoverlap]]`ehOverlap` | <<Egenhofer Relation Family, `ehOverlap`>> | <<egenhofer_query_functions, `ehOverlap`>>
| [[rule-ehcovers]]`ehCovers` | <<Egenhofer Relation Family, `ehCovers`>> | <<egenhofer_query_functions, `ehCovers`>>
| [[rule-ehcoveredby]]`ehCoveredBy` | <<Egenhofer Relation Family, `ehCoveredBy`>> | <<egenhofer_query_functions, `ehCoveredBy`>>
| [[rule-ehinside]]`ehInside` | <<Egenhofer Relation Family, `ehInside`>> | <<egenhofer_query_functions, `ehInside`>>
| [[rule-ehcontains]]`ehContains` | <<Egenhofer Relation Family, `ehContains`>> | <<egenhofer_query_functions, `ehContains`>>
|===

[[query_rewrite_rcc8]]
=== RCC8 Relation Family

This clause defines Requirements for the _RCC8_ relation family. <<rcc8_query_transformation_rules>> specifies the function and property substitutions for each rule in the _RCC8_ relation family.

[[req_query-rewrite-extension_rcc8-query-rewrite]]
[requirement,identifier="/req/query-rewrite-extension/rcc8-query-rewrite"]
.RCC8 Query Transformation Rules
====
Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime <<SPARQLENT>> for the RIF rules <<RIFCORE>> 
<<rule-rcc8eq, `rcc8eq`>>,
<<rule-rcc8dc, `rcc8dc`>>,
<<rule-rcc8ec, `rcc8ec`>>,
<<rule-rcc8po, `rcc8po`>>,
<<rule-rcc8tppi, `rcc8tppi`>>,
<<rule-rcc8tpp, `rcc8tpp`>>,
<<rule-rcc8ntpp, `rcc8ntpp`>> and
<<rule-rcc8ntppi, `rcc8ntppi`>>.
====

[[rcc8_query_transformation_rules]]
.RCC8 Query Transformation Rules
|===
|Rule | ogc:relation | ogc:function

| [[rule-rcc8eq]]`rcc8eq` | <<RCC8 Relation Family, `rcc8eq`>> | <<rcc8_query_functions, `rcc8eq`>>
| [[rule-rcc8dc]]`rcc8dc` | <<RCC8 Relation Family, `rcc8dc`>> | <<rcc8_query_functions, `rcc8dc`>>
| [[rule-rcc8ec]]`rcc8ec` | <<RCC8 Relation Family, `rcc8ec`>> | <<rcc8_query_functions, `rcc8ec`>>
| [[rule-rcc8po]]`rcc8po` | <<RCC8 Relation Family, `rcc8po`>> | <<rcc8_query_functions, `rcc8po`>>
| [[rule-rcc8tppi]]`rcc8tppi` | <<RCC8 Relation Family, `rcc8tppi`>> | <<rcc8_query_functions, `rcc8tppi`>>
| [[rule-rcc8tpp]]`rcc8tpp` | <<RCC8 Relation Family, `rcc8tpp`>> | <<rcc8_query_functions, `rcc8tpp`>>
| [[rule-rcc8ntpp]]`rcc8ntpp` | <<RCC8 Relation Family, `rcc8ntpp`>> | <<rcc8_query_functions, `rcc8ntpp`>>
| [[rule-rcc8ntppi]]`rcc8ntppi` | <<RCC8 Relation Family, `rcc8ntppi`>>| <<rcc8_query_functions, `rcc8ntppi`>>
|===

=== Special Considerations

The applicability of GeoSPARQL rules in certain circumstances has intentionally been left undefined.

The first situation arises for triple patterns with unbound predicates. Consider the query pattern below:

[%unnumbered]
[source,sparql]
----
{ my:feature1 ?p my:feature2 }
----

When using a query transformation strategy, this triple pattern could invoke none of the GeoSPARQL rules or all of the rules. Implementations are free to support either of these alternatives.

The second situation arises when supporting GeoSPARQL rules in the presence of RDFS Entailment. The existence of a topological relation (possibly derived from a GeoSPARQL rule) can entail other RDF triples. For example, if <<Simple Features Relation Family, `sfOverlaps`>> has been defined as an http://www.w3.org/2000/01/rdf-schema#subPropertyOf[`rdfs:subPropertyOf`] the property `my:overlaps`, and the RDF triple `my:feature1 geo:sfOverlaps my:feature2` has been derived from a GeoSPARQL rule, then the RDF triple `my:feature1 my:overlaps my:feature2` can be entailed. Implementations may support such entailments but are not required to.
