.Preface

This document provides the set of revision notes for OGC GeoSPARQL 1.1 [OGC <document number>] and does not modify that standard.

This document provides the details of edits, deficiency corrections, and enhancements of the above-referenced standard. It also documents those items that have been deprecated. Finally, this document provides implementations details related to issues of backwards compatibility.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[abstract]
== Abstract

GeoSPARQL defines a core set of Semantic Web classes, properties and datatypes for the representation of spatial information on the web and SPARQL extension functions for spatial data queries.
