== Terms and definitions

This document uses the terms defined in Sub-clause 5.3 of <<OGC06-121r9>>, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== administrative change

change that does not alter the conformance abstract tests for any requirements

NOTE: An administrative change includes typographical errors, changes in wording to improve clarity or consistency, and perfunctory changes such as changes in version numbers.

=== critical Change

change that alters requirements in a way that is known to cause reverse compatibility issues

=== substantive change

change that alters requirements in a way that is not deemed to have a high risk for causing reverse compatibility issues


=== example term

term used for exemplary purposes

[.source]
<<ISO19101-1>>

NOTE: An example note.

[example]
Here's an example of an example term.

////
// List any abbreviations and their full expansions that are used in this document, if any.
=== Abbreviations

EX:: Example
////
