ask
where {
    ?f <http://www.opengis.net/ont/geosparql#sfEquals> ?f2 .
    ?f geov:expectedResult ?expresult .
    ?f <http://www.opengis.net/ont/geosparql#hasGeometry> ?fgeom . ?fgeom <http://www.opengis.net/ont/geosparql#asWKT> ?fgwkt .
    ?f2 <http://www.opengis.net/ont/geosparql#hasGeometry> ?f2geom . ?f2geom <http://www.opengis.net/ont/geosparql#asWKT> ?f2gwkt .
    FILTER (<http://www.opengis.net/def/function/geosparql/sfEquals>(?fgwkt,?f2gwkt)=true)
}