[.preface]
[[metanorma_extension]]
== Metanorma-Extension

[[user_css]]
=== user-css

[source,css]
----
details > figure,
details > figure > pre {
  font-size: 1em !important;
  overflow-x: auto !important;
  overflow-y: visible !important;
  scrollbar-color: #78909c #e1eef1;
  scrollbar-width: thin;
}

details > figure > pre::-webkit-scrollbar {
  height: 8px;
  background-color: #e1eef1;
}

details > figure > pre::-webkit-scrollbar-track {
  background-color: #e1eef1;
}

details > figure > pre::-webkit-scrollbar-thumb {
  background-color: #78909c;
  border: 2px solid #e1eef1;
  border-radius: 4px;
}
----

[abstract]
[[abstract]]
== Abstract

GeoSPARQL contains a small spatial domain OWL ontology that allow literal representations of geometries to be associated with spatial features and for features to be associated with other features using spatial relations.

GeoSPARQL also contains SPARQL extension function definitions that can be used to calculate relations between spatial objects.

Several other supporting assets are also contained within GeoSPARQL such as vocabularies of Simple Feature types and data validators.

[.text-center]
====
The namespace for the GeoSPARQL ontology is `http://www.opengis.net/ont/geosparql#`

The suggested prefix for this namespace is `geo`

The namespace for the GeoSPARQL functions is `http://www.opengis.net/def/function/geosparql/`

The suggested prefix for this namespace is `geof`

The namespace for the GeoSPARQL RIF rules is `http://www.opengis.net/def/rule/geosparql/`

The suggested prefix for this namespace is `geor`
====

[.preface]
[[preface]]
== Preface

The OGC GeoSPARQL Standard defines:

* A formal _profile_;
* **this document;**
* A core RDF/OWL ontology for geographic information representation;
* A set of SPARQL extension functions;
* A Functions & Rules vocabulary, derived from the ontology;
* A Simple Features geometry types vocabulary;
* SHACL shapes for RDF data validation.

This document authoritatively defines many of the Standard's elements, including the ontology classes and properties, SPARQL functions, and function and rule vocabulary concepts. Complete descriptions of the Standard's parts and their roles are given in the Introduction in the section <<geosparql_standard_structure>>.

[.preface]
[[keywords]]
== Keywords

Open Geospatial Consortium, OGC, spatial, ontology, Knowledge Graph, Semantic Web, Linked Data, RDF, Resource Description Framework, Web Ontology Language, OWL, SPARQL, Simple Features, feature, geometry

[.preface]
[[clarifications]]
== Clarifications

* The terms <<spatial_reference_system, Spatial Reference System (SRS)>> and <<coordinate_reference_system, Coordinate Reference System (CRS)>> are no longer interchangeable. Spatial Reference System is now taken to be a broader category than Coordinate Reference System. These are defined in the <<terms_and_definitions>> section.
* Class definitions were updated to be more self-contained and easier to understand for people without a background in geoinformatics. The definitions are no longer dependent on other standards' definitions, only informed by them.
* A section was added on <<recommendation_for_units_of_measure, the specification of units of measurement>>.
* A section was added on the <<influence_of_reference_systems_on_computations, influence of Reference Systems on computations>>.

[.preface]
[[changes_to_the_ogc_abstract_specification]]
== Changes to the OGC® Abstract Specification
The OGC® Abstract Specification does not require changes to accommodate this OGC® standard.

[.preface]
[[submitting_organizations]]
== Submitting organizations

The following organizations submitted this Implementation Standard to the Open Geospatial Consortium Inc.:

* CSIRO
* Cubewerx Inc.
* Defence Science and Technology Laboratory (DSTL)
* Geonovum
* Geoscape Australia
* Geoscience Australia
* KurrawongAI
* Mainz University Of Applied Sciences
* Oracle America
* OSGeo

[.preface]
[[submitters]]
== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

[%unnumbered]
[%header, cols="1, 3"]
|===
|Name | Affiliation
| Nicholas J. Car _(editor)_ | KurrawongAI
| Timo Homburg _(editor)_ | Mainz University Of Applied Sciences
| Matthew Perry _(editor)_ | Oracle America
| Joseph Abhayaratna _(editor)_ | Geoscape Australia
| Paul Cripps _(editor)_ | DSTL
| Simon J.D. Cox | CSIRO
| Panagiotis (Peter) A. Vretanos | Cubewerx Inc.
| Linda van den Brink | Geonovum
| Irina Bastrakova | Geoscience Australia
|===
