[bibliography,normative=true]
== Normative references

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. However, parties to agreements based on this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below. For undated references, the latest edition of the normative document referred to applies.

Items in this list are linked to their full citation <<Bibliography>>.

* [[[ISO19125-1,local-file(ISO19125-1)]]]
* [[[ISO19156,local-file(ISO19156)]]]
* [[[GML,local-file(GML)]]]
* [[[IETF3987,local-file(IETF3987)]]]
* [[[OWL2,local-file(OWL2)]]]
* [[[RDF,local-file(RDF)]]]
* [[[RDFS,local-file(RDFS)]]]
* [[[RIFCORE,local-file(RIFCORE)]]]
* [[[SPARQL,local-file(SPARQL)]]]
* [[[SPARQLENT,local-file(SPARQLENT)]]]
* [[[SPARQLPROT,local-file(SPARQLPROT)]]]
* [[[SPARQLRESX,local-file(SPARQLRESX)]]]
* [[[SPARQLRESJ,local-file(SPARQLRESJ)]]]
