== Preface
This standard defines a set of SPARQL extension functions [W3C SPARQL], a set of RIF rules [W3C RIF Core], and a core RDF/OWL [12,14,16] vocabulary for geographic information based on the General Feature Model [7], Simple Features [ISO 19125-1], Feature Geometry [6] and SQL MM [4].

== Submitting organizations
The following organizations submitted this Implementation Specification to the Open Geospatial Consortium Inc.:

a) Australian Bureau of Meteorology

b) Bentley Systems, Inc.

c) CSIRO

d) Defence Geospatial Information Working Group (DGIWG)

e) GeoConnections - Natural Resources Canada

f) Interactive Instruments GmbH

g) Oracle America

h) Ordnance Survey

i) Raytheon Company

j) Traverse Technologies, Inc.

k) US Geological Survey (USGS)


== Submission contact points
All questions regarding this submission should be directed to the editor or the submitters:

|===
|CONTACT | COMPANY

| Matthew Perry | Oracle America
|John Herring | Oracle America
|===

== Revision history

|===
|Date | Release | Author | Paragraph modified | Description

| 27 Oct. 2009 | Draft | Matthew Perry | Clause 6 | Technical Draft
| 11 Nov. 2009 | Draft | John R. Herring | All | Creation
| 6 Jan. 2010 | Draft | John R. Herring | All | Comment responses
| 30 March 2010 | Draft | Matthew Perry | All | Comment responses
| 26 Oct. 2010 | Draft | Matthew Perry | All | Revision based on working group discussion
| 28 Jan. 2011 | Draft | Matthew Perry | All | Revision based on working group discussion

| 18 April 2011 | Draft | Matthew Perry | All | Restructure with multiple conformance classes
| 02 May 2011 | Draft | Matthew Perry | Clause 6 and Clause 8 | Move Geometry Class from core to geometryExtension
| 05 May 2011 | Draft | Matthew Perry | All | Update URIs
| 13 Jan. 2012 | Draft | Matthew Perry | All | Revision based on Public RFC
| 16 April 2012 | Draft | Matthew Perry | All | Revision based on adoption vote comments
| 19 July 2012 |1.0 | Matthew Perry | All | Revision of URIs based on OGC Naming Authority recommendations
|===

== Changes to the OGC® Abstract Specification
The OGC® Abstract Specification does not require changes to accommodate this OGC®
standard.

== Forward
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights. However, to date, no such rights have been claimed or identified.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the specification set forth in this document, and to provide supporting documentation.