== i. Abstract

GeoSPARQL contains a small spatial domain OWL ontology that allow literal representations of geometries to be associated with spatial features and for features to be associated with other features using spatial relations.

GeoSPARQL also contains SPARQL extension function definitions that can be used to calculate relations between spatial objects.

Several other supporting assets are also contained within GeoSPARQL such as vocabularies of Simple Feature types and data validators.

[.text-center]
====
The namespace for the GeoSPARQL ontology is `http://www.opengis.net/ont/geosparql#`

The suggested prefix for this namespace is `geo`

The namespace for the GeoSPARQL functions is `http://www.opengis.net/def/function/geosparql/`

The suggested prefix for this namespace is `geof`
====

== ii. Keywords

Open Geospatial Consortium, OGC, spatial, ontology, Knowledge Graph, Semantic Web, Linked Data, RDF, Resource Description Framework, Web Ontology Language, OWL, SPARQL, Simple Features, feature, geometry

== iii. Preface
The OGC GeoSPARQL Standard defines:

* A formal _profile_;
* **this document;**
* A core RDF/OWL ontology for geographic information representation;
* A set of SPARQL extension functions;
* A Functions & Rules vocabulary, derived from the ontology;
* A Simple Features geometry types vocabulary;
* SHACL shapes for RDF data validation.

This document authoritatively defines many of the Standard's elements, including the ontology classes and properties, SPARQL functions, and function and rule vocabulary concepts. Complete descriptions of the Standard's parts and their roles are given in the Introduction in the section <<GeoSPARQL Standard structure>>.

== iv. Submitting organizations
The following organizations submitted this Implementation Standard to the Open Geospatial Consortium Inc.:

[loweralpha]
.. CSIRO
.. Cubewerx Inc.
.. Defence Science and Technology Laboratory (DSTL)
.. Geonovum
.. Geoscape Australia
.. Geoscience Australia
.. KurrawongAI
.. Mainz University Of Applied Sciences
.. Oracle America
.. OSGeo
.. SURROUND Australia Pty Ltd.


=== v. Submission contact points
All questions regarding this submission should be directed to the editor or the submitters:

[frame=none, grid=none, cols="1, 3"]
|===
|Contact | Affiliation

| Simon J.D. Cox | CSIRO
| Panagiotis (Peter) A. Vretanos | Cubewerx Inc.
| Paul Cripps | DSTL
| Linda van den Brink | Geonovum
| Joseph Abhayaratna | Geoscape Australia
| Irina Bastrakova | Geoscience Australia
| Nicholas J. Car | KurrawongAI and SURROUND Australia Pty Ltd.
| Timo Homburg | Mainz University Of Applied Sciences
| Matthew Perry | Oracle America
| Dimitris Kotzinos | OSGeo
|===

== vi. Clarifications

* The terms <<spatial reference system, Spatial Reference System (SRS)>> and <<coordinate reference system, Coordinate Reference System (CRS)>> are no longer interchangeable. Spatial Reference System is now taken to be a broader category than Coordinate Reference System. These are defined in the <<Terms and definitions>> section.
* Class definitions were updated to be more self-contained and easier to understand for people without a background in geoinformatics. The definitions are no longer dependent on other standards' definitions, only informed by them.
* A section was added on <<Recommendation for units of measure,the specification of units of measurement>>.
* A section was added on the <<Influence of Reference Systems on computations,influence of Reference Systems on computations>>.

== vii. Changes to the OGC® Abstract Specification
The OGC® Abstract Specification does not require changes to accommodate this OGC® standard.
