== Normative references

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. However, parties to agreements based on this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below. For undated references, the latest edition of the normative document referred to applies.

Items in this list are linked to their full citation in the <<Bibliography>>.

* <<OGCSFACA>> <<ISO19125-1>>, OGC: _OpenGIS Implementation Specification for Geographic information - Simple feature access — Part 1: Common architecture_ (also ISO 19125-1)

* <<OGCOM>> <<ISO19156>>, OGC: _Abstract Specification Topic 20 - Observations and measurements_ (also ISO 19156)

* <<GML>>, OGC: _OGC 07-036: Geography Markup Language (GML) Encoding Standard_

* <<IETF3987>>, IETF: _RFC 3987: Internationalized Resource Identifiers (IRIs)_

* <<OWL2>> W3C: _OWL 2 Web Ontology Language Document Overview (Second Edition)_

* <<RDF>>, W3C: _RDF 1.1 Concepts and Abstract Syntax_

* <<RDFS>> W3C: _RDF Schema 1.1_

* <<RIFCORE>>, W3C: _RIF Core Dialect (Second Edition)_

* <<SPARQL>>, W3C: _SPARQL 1.1 Query Language_

* <<SPARQLENT>>, W3C: _SPARQL 1.1 Entailment Regimes_

* <<SPARQLPROT>>, W3C: _SPARQL 1.1 Protocol_

* <<SPARQLRESX>>, W3C: _SPARQL Query Results XML Format (Second Edition)_

* <<SPARQLRESJ>>, W3C: _SPARQL 1.1 Query Results JSON Format_