
.Preface
This OGC Community Standard was an outcome of the development of GeoSPARQL 1.3, to satisfy the requirement for a Normative Reference for a binary encoding that supports more than two dimensions and includes a spatial reference system.

[.preface]
== Source of the content for this OGC document

The majority of the content in this OGC document is a direct copy of the content originally contained in the following documents: https://github.com/postgis/postgis/blob/master/doc/ZMSgeoms.txt and  https://libgeos.org/specifications/wkb/#extended-wkb. No normative changes have been made to the content. This OGC document does contain content not in the original sources. Specifically, the Abstract, Keywords, Preface, Terms and Definitions and Reference sections in this document are not found in the original sources.

[.preface]
== Validity of content

The Submission Team has reviewed and certified that the snapshot content in this Community Standard is true and accurate. The snapshot for OGC Extended WKB Version 1.0 was taken on 9 July 2025 from the libGEOS website.

[.preface]
== Future work

The GeoSPARQL SWG will attempt to keep this OGC Community Standard in sync with developments within the Open Source community that maintains the PostGIS and libGEOS documents. Changes to this Community Standard apart from the sections maintained by the GeoSPARQL SWG will not occur.


[.preface]
== Submitting Organizations

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* Defence Science & Technology Labs (DSTL)
* Geoscape Australia
* Kurrawong AI
* Mainz University of Applied Sciences
* Ontotext
* Oracle

[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or submitters:

* Joseph Abhayaratna (editor) Geoscape Australia
* Nicholas Car (contributor) Kurrawong AI
* Arkadiusz Chadzynski (contributor) Ontotext
* Paul Cripps (contributor) DSTL
* Timo Homburg (contributor) Mainz University of Applied Sciences
* Matthew Perry (contributor) Oracle
