
.Preface
This OGC Community Standard was an outcome of the development of GeoSPARQL 1.3, to satisfy the requirement of a Normative Reference for a binary encoding that supports more than two dimensions and inclusion of a spatial reference identifier (SRID).

[.preface]
== Source of the content for this OGC document

The majority of the content in this OGC document is a direct copy of the content originally contained at https://libgeos.org/specifications/wkb/#extended-wkb. No normative changes have been made to the content. This OGC document does contain content not in the original source libGEOS webpage. Specifically, the Abstract, Keywords, Preface, Terms and Definitions and Reference sections in this document are not found in the original libGEOS source.

[.preface]
== Validity of content

The Submission Team has reviewed and certified that the snapshot content in this Community Standard is true and accurate. The snapshot for OGC Extended WKB Version 1.0 was taken on 9 July 2025 from the libGEOS website.

[.preface]
== Future work

The GeoSPARQL SWG will attempt to keep this OGC Community Standard in sync with developments within the Open Source community that maintains the libGEOS documents. Changes to this Community Standard apart from the sections maintained by the GeoSPARQL SWG will not occur.