
== Scope

The Well Known Binary (WKB) representation of geometry was defined by the Open Geospatial Consortium (OGC) in 2004 as part of the Simple Features Access Part 1 Common Architecture standard. It is used to encode two dimensional geometries, and does not cater for storage of a spatial reference identifier (SRID).

As GeoSPARQL 1.3 is an update of the standard to support 3D use cases, and an SRS is a required component of the encoding, WKB does not explicitly meet the needs of a binary encoding for GeoSPARQL. Extended WKB, defined by the libGEOS project, recognises these shortcomings of the standard and extends it through backwards compatible addition of extra dimensions (e.g., Z and M that are commonly used by GIS applications) and an SRID. All content used for this document was sourced from the following webpages: https://github.com/postgis/postgis/blob/master/doc/ZMSgeoms.txt and https://libgeos.org/specifications/wkb/#extended-wkb. As such, the OGC does not assert any Intellectual Property over this standard.

Therefore, this OGC Community Standard was an outcome of the development of GeoSPARQL 1.3, to satisfy the requirement of a Normative Reference for a binary encoding.
