
[bibliography]
== References
The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

* [[[OGCSFACA,Simple Features Access - Part 1: Common Architecture]]],
_Simple Features Access - Part 1: Common Architecture_.
International Organization for Standardization (2004)
* [[[GeoSPARQL,GeoSPARQL]]],
_GeoSPARQL_.
Open Geospatial Consortium (2024)
* [[[ISO19101-1,Geographic Information - Reference model - Part 1]]],
_Geographic Information - Reference model - Part 1_.
International Organization for Standardization (2014)

The following non-normative documents are used as the main source of this document. The bulk of this standard is directly copied from these two reference documents. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

* [[[ZM-GEOM,ZM values and SRID for Simple Features]]],
_ZM values and SRID for Simple Features_.
Santilli, Sandro (2005)
* [[[EWKB,Extended Well Known Binary]]],
_Extended Well Known Binary_.
libGEOS.
